### ISSUE TITLE
Custom actions in column templates

### ISSUE THREAD

**Issue by bmac** [onechiporenko/ember-models-table#1]
Hi @onechiporenko. Awesome addon.

I am interested in using this addon for a table where I have some custom buttons that I would like to trigger actions that my app could respond to. I would like to do something like this:

```js
Ember.Controller.extend({
  actions: {
    delete: function(record) {
        // Custom code here
    }
  },
  columns: [
  {
      propertyName: 'actions',
      title: 'Actions',
      template: 'edit-delete-column'
    }
]
});
```

#### Template for Controller
```hbs
{{models-table
  delete='delete'
  content=model
  columns=columns
}}
```

#### edit-delete-column Template
```hbs
<div class="row-edit">
  <button class="form-button" {{action 'delete' record}}>Delete</button>
</div>
```

Unfortunately because of the `models-table` component isolates actions from inside its templates I can't do that at the moment. Would you be interested in a pr that defines a `sendAction` action on the `models-table` component to make it easy to define custom actions. 

I would imagine the `sendAction` component would look like this:
```js
//...
  sendAction: function() {
    this.sendAction.apply(this, arguments);
  }
//...
```

And it would allow users to define custom actions in their component like this:

```hbs
<div class="row-edit">
  <button class="form-button" {{action 'sendAction' 'delete' record}}>Delete</button>
</div>
```

Also if there is a better way to achieve what I'm trying to do please let me know.

**Comment by onechiporenko** [comment]
Hi, @bmac! Sure, I'll be glad to see PR with described functionality!

**Comment by andessen** [comment]
Ah, this is great. I was about to ask the same thing. Can future pull requests like this add a little something to the read me so as to not hunt down old issues / PRs?

**Comment by onechiporenko** [comment]
@andessen, I'm trying to add some specific features to the [demo](http://onechiporenko.github.io/ember-models-table/). Custom actions are described there (thanks to PR-author)
