### ISSUE TITLE
ember-get-helper is deprecated after ember 2.0, causing warning

### ISSUE THREAD

**Issue by escobera** [onechiporenko/ember-models-table#105]
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-get-helper`
```
Ember 2.6.2
Ember-cli 2.6.2

**Comment by onechiporenko** [comment]
Hi, I know about this. But `ember-models-table` is used with 1.13 too. Unfortunately, I don't know how to add `ember-get` as a dependency to the 1.13 only.

**Comment by listepo** [comment]
@onechiporenko I think they will need to explicitly specify this dependence
