### ISSUE TITLE
When filtering, update other columns' select boxes to include only available choices?

### ISSUE THREAD

**Issue by arnebit** [onechiporenko/ember-models-table#107]
Example: "Filtering with select-box" at http://onechiporenko.github.io/ember-models-table: Pick a last name, e.g. "Brown". The select box for first name still contains all first names from the original data, which now means more entries than there are rows in the table remaining. 

Can the select box content be updated on a displayDataChanged event, such that it include only options for which the resulting table will be non-empty?

**Comment by onechiporenko** [comment]
Hi, @arnebit. Sorry, but it can't be done.

**Comment by arnebit** [comment]
I managed to implement this now using `componentForFilterCell`, two of them to be precise, both with templates more or less looking like [the filterWithSelect-relevant line of header-row-filtering.hbs](https://github.com/onechiporenko/ember-models-table/blob/master/app/templates/components/models-table/header-row-filtering.hbs#L14) while

- one contains an additional observer that on changes of `column.filterString` resets _another_ column's filterString
- another that retrieves the filterString of a column (the one using the former component), calculates the filterOptions for this column based only on the data filtered for that filterString.

My actual use case involves main categories and subcategories, by the way. Would it be of general interest to add an example using this approach to the documentation?
