### ISSUE TITLE
Passing component actions to nested components in a partial

### ISSUE THREAD

**Issue by duro** [onechiporenko/ember-models-table#109]
I am using `models-table` inside a component. Here is the template for said component:

```
{{models-table
  data=tableData
  columns=columns}}
```

I have an action in the component.js, that has an action that I want to call from a partial that I am using to render a column. Here is the component.js

```
import Ember from 'ember';

export default Ember.Component.extend({
  tableData: Ember.computed('users.[]', function() {
    return this.get('users').filter(user => user.get('id') !== 'me');
  }),
  columns: [
    {
      propertyName: "id",
      title: "ID",
      mayBeHidden: true
    },
    {
      propertyName: "firstName",
      title: "First Name",
      mayBeHidden: true
    },
    {
      propertyName: "lastName",
      title: "Last Name",
      mayBeHidden: true
    },
    {
      title: "Promote User",
      template: "components/users-table/promote-user"
    }
  ],
  actions: {
    handlePromote() {
      console.log('hit');
    }
  }
});
```

The partial uses a component from the `ember-bootstrap` library to implement a button that will used to trigger the action. Here is that partial template:

```
{{#bs-button action=(action 'handlePromote')}}Promote{{/bs-button}}
```

When I click on this button I get the following error:

```
Uncaught Error: An action named 'handlePromote' was not found in <zg-dashboard@component:models-table::ember754>.
```

Looking at the docs, you are using the `sendAction` action to trigger things. I tried this:

```
{{#bs-button action=(action 'sendAction' 'handlePromote' record)}}Promote{{/bs-button}}
```

However, this does not seem to send actions to the component. I assume it is sending them up the enclosing controller. However, I am trying to keep my components atomic and self-contained, letting the route template pass in the actions that are needed.

I don't seem to see a good way to do this. Help.

**Comment by duro** [comment]
Ok, I figured this out on my own. I'll leave this here for educational purposes for others.

I had to pass the action into the actual `models-table` component.

So in my component (`users-table`) I pass in the action as an attribute to `models-table:

```
// components/users-table/template.hbs

{{models-table
  data=tableData
  columns=columns
  handlePromote=(action 'handlePromote')}}
```

Then in my column partial, I do the following:

```
// components/users-table/promote-user/template.hbs

{{#bs-button action=(action handlePromote record)}}Promote{{/bs-button}}
```

**Comment by onechiporenko** [comment]
Hi, @duro. Thanks for described solution!
