### ISSUE TITLE
Remove pagination: pageSize option not listed in documentation

### ISSUE THREAD

**Issue by stickbyatlas** [onechiporenko/ember-models-table#110]
I was trying to disable pagination altogether so the table always showed every row. I struggled with a bunch of different approaches, and then realized that I could just pass in `pageSize=x` in the Handlebars helper.

Just posting this in case anybody else is trying to disable pagination.

**Comment by skaterdav85** [comment]
thank you!

**Comment by andrei-sheina** [comment]
@stickbyatlas cudos to you my friend! 
@onechiporenko I think it would be great to add pageSize option to the docs (can insert in pagination example)

**Comment by dpatz** [comment]
This can probably be closed
