### ISSUE TITLE
populating table with computed results?

### ISSUE THREAD

**Issue by Datamance** [onechiporenko/ember-models-table#111]
Hey there @onechiporenko,

So I want to be able to repopulate the table with computed results, which come back as an array of Objects rather than a DS.Model class (I have two way interactivity with a filter bar and clickable charts).

Is it by design that I can only repopulate the table with query or findAll results?

Is there some easy way that I can convert my list of computed results (just an array of Ember Objects) into something that plays nice with your table component?

The docs [seem to say](http://onechiporenko.github.io/ember-models-table/) that I should be able to get away with this, but it's definitely not working. What suggestions do you have?

**Comment by Datamance** [comment]
Ping :)

**Comment by onechiporenko** [comment]
Hi, @Datamance.
Could you pls provide your code. Thanks

**Comment by Datamance** [comment]
Sure thing, @onechiporenko . In my router:

```
  /**
   * Injected query filter service
   */
  queryFilter: Ember.inject.service('query-filter'),

  model() {
    let queryFilter = this.get('queryFilter')
        .setup('global-change-notification');

    return {
      savedSearches: [],
      globalChangeNotifications: queryFilter.getComputedResultsFor(
          'global-change-notifications')
    };
  }
});
```

And the service method being called:

```
  getComputedResultsFor(modelName) {
    return this.get(`modelRegistry.${modelName}.computedFilter`);
  },
```

And the setup method that sets the computed filter for the model:

```
setup(modelNameList) {
    let modelNames =
        Array.isArray(modelNameList) ? modelNameList : [...arguments];

    let service = this;
    let modelRegistry = this.get('modelRegistry');
    let store = this.get('store');

    modelNames.forEach(function(modelName) {
      let model = store.modelFor(modelName);
      modelRegistry[modelName] = {
        model: model,
        queryState: new QueryState(Ember.get(model, 'attributes')),
        allRecords: store.findAll(modelName),
        computedFilter: Ember.computed.filter(
            'allRecords',
            function(record) {
                return service._areConditionsMatched(
                    record, service.getQueryForModel(modelName));
            }).volatile()
      };
    });

    return this;
  },

```

The service gets the specified items just fine. The problem is that the object shape (an array containing ComputedProperty results) seems to be something that ember-models-table can't handle. It seems to really want the results from either store.query() or store.findAll().

**Comment by Datamance** [comment]
i.e., populating that router model with this service method:

```
  getAllFor(modelName) {
    return this.get(`modelRegistry.${modelName}.allRecords`);
  },
```

works totally fine.

**Comment by Datamance** [comment]
@onechiporenko is the table only designed to work with Promises? Both DS.Store.findAll() and DS.Store.query() return promises. But if I want to do client-side filtering _outside_ of the table, then I have to use methods like .map() and .filter() that take the results out and shove them into an array (no longer a promise-wrapped object).

Do you have any suggestions for how to work around this limitation?

**Comment by Datamance** [comment]
@onechiporenko - any update on this? If I should move to ember-light-table that's fine, just let me know if you plan to support POJO/Model arrays rather than just promises - it will help me manage expectations with my project managers :)

**Comment by onechiporenko** [comment]
@Datamance, for you it's better to use addon that works in your case. I can't get quick solution for your problem with `ember-models-table`. Sorry
