### ISSUE TITLE
Small freeze after table is shown on version 1.8.0 (Ember 2.7.0)

### ISSUE THREAD

**Issue by srjpfc** [onechiporenko/ember-models-table#112]
after updating both ember-models-table and ember itself to the latest versions (1.8.0 and 2.7.0, respectively) i am noticing a small freeze right after the table is shown. the freeze is proportional to the number of rows. for instance, a simple table with 100 rows and 5 columns freezes for about 10 seconds (even seeing the beach ball on macOS for half of that time). table contents are obtained via data store in a couple of miliseconds or even cached. for 50 rows the freeze last for 1 to 2 seconds, less than that is barely noticeable.

**Comment by onechiporenko** [comment]
Hi, @srjpfc. Thanks for your feedback. I'm going to invastigate a problem/
