### ISSUE TITLE
models-table-server-paginated is not showing up 

### ISSUE THREAD

**Issue by albertonavarro087** [onechiporenko/ember-models-table#115]
I'm trying to use models-table-server-paginated component but i'm not able to make it show up

```
{{models-table-server-paginated
    data=_searchResults
    metaPagesCountProperty='pages'
    metaItemsCountProperty='total'
    columns=_columns
    showGlobalFilter=false
    showColumnsDropdown=false
    useNumericPagination=true
    filteringIgnoreCase=true
    pageSize=5
    showPageSize=false
    customIcons=icons
    customClasses=classes}}
```

```
export default Ember.Component.extend(baseComponent, tableComponent, {
_searchResults: Ember.computed(function() {
    return this.get('store').query('searchOrder', {});
  }),
  _columns: Ember.computed(function() {
    return [
      {
        propertyName: 'name',
        title: this.get('intl').t('productType.list.name')
      }
    ];
  })
});
```

Is there something that I'm missing?

**Comment by onechiporenko** [comment]
Hi, @albertonavarro087. Pls try latest code from this repo. I hope, problem won't appear

**Comment by itsfadnis** [comment]
@onechiporenko I just can't get the `models-table-server-paginated` table to show up; Same issue as what @albertonavarro087 mentioned above. 

Does this component even work? Can we have an simple example of how to set it up? Just can't understand what I'm missing.

**Comment by MahnazSheikhi** [comment]
@onechiporenko , Please set up an example for use, because I do not understand how to set it up?
