### ISSUE TITLE
In case of "template" the new value is not update automatically 

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#117]
The problem is 

I have a model with one attribute as object example - 
`policy: attr()`
Now i have used  
`template: 'table-cells/object-as-a-string',propertyName: 'policy'`
to convert the object into string and display it as as a column in table

The problem is when somebody modifies policy_details and refresh the table the modified data is fetched but the column is not updated. Because of which the particular column of the table holds old data
`
fetchPolicyDetails(policyId) {
            this.store.query('policies', {policy_id: policyId})
                .then((result) => set(this, 'policyDetails', result));
`

**Comment by onechiporenko** [comment]
Hi, @PankajWorks. Could you pls provide a demo with ember-twiddle?
