### ISSUE TITLE
Update value in columns when a particular row is modified by edit action

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#118]
Hi

I have an edit action on each row of table displayed through models-table. The job is to edit the row and save it in DB . I have a column which is of type object and have used custom template to convert the object into string. 

Now the issue is : the table is not updated with modified values. I have used 
`
columnsAreUpdateable=true
columnFieldsToCheckUpdate=predeclaredCols
`

have defined  predeclaredCols in the component 
`predeclaredCols: ["custom_attributes","table-cells/object-as-a-string"],
`
I am missing something

**Comment by onechiporenko** [comment]
Hi, @PankajWorks. Without demo with isolated problem I can't help you, sorry.
