### ISSUE TITLE
Camelize column title

### ISSUE THREAD

**Issue by mciastek** [onechiporenko/ember-models-table#12]
Hey,

I think it's a good idea to implement autogeneration `propertyName` from column titles using [camelize](http://emberjs.com/api/classes/Ember.String.html#method_camelize), when `propertyName` isn't provided.

What do you think about it?

**Comment by onechiporenko** [comment]
Hi, `propertyName` can't be auto generated because it's a object's field. It may exists and may not. If you mean to auto generate `title` using `propertyName` - I agree. It may be implemented.
