### ISSUE TITLE
Provide column text with computed property

### ISSUE THREAD

**Issue by rhyek** [onechiporenko/ember-models-table#120]
It would be great if when configuring a column I could provide a computed property for its text instead of a `propertyName` and still have sorting and filtering functionality based on that generated text.

Currently the way to do this is to modify my model definition and include that computed property there, passing its name to `propertyName`, but this might not always be desired.

**Comment by KirillSuhodolov** [comment]
Same proposal. I need dynamic sort properties based on controller CP.

**Comment by nag9329** [comment]
Same problem here

**Comment by rhyek** [comment]
Closing this issue. This is the easiest thing to accomplish using Vue.

**Comment by nag9329** [comment]
@rhyek what do you mean by Vue? How is this related to ember models table

**Comment by rhyek** [comment]
It means I am not using Ember anymore and it seems the maintainer for this addon isn't planning on implementing or even acknowledging the requested feature after almost a year.

GL!
