### ISSUE TITLE
Pressing Enter while filter's input is in focus cause error in console.

### ISSUE THREAD

**Issue by andrei-sheina** [onechiporenko/ember-models-table#121]
![image](https://cloud.githubusercontent.com/assets/11193254/18242993/8ee332d0-7361-11e6-86ee-f05b3bb406ce.png)

**Comment by andrei-sheina** [comment]
@onechiporenko I can see 2 possible solutions: 
1) bind falsy action that will always return false from models-table component.
2) You can actually remove from element and use only input.

**Comment by onechiporenko** [comment]
v1.8.1-beta.3 with fix for #121 is published
