### ISSUE TITLE
ember-models-table hangs when trying to load more than 50,000 records.

### ISSUE THREAD

**Issue by bebop23** [onechiporenko/ember-models-table#123]
The GUI becomes unresponsive.  10,000 records can load, but it takes an extremely long time.

**Comment by lcpriest** [comment]
May I ask why you aren't paginating when you have that many records?

**Comment by bebop23** [comment]
As a user, I would assume that ember-models-table takes care of pagination
for you :)

**Comment by lcpriest** [comment]
I believe it does if your API handles pagination?
http://onechiporenko.github.io/ember-models-table/examples/numeric-pagination

Have you found that loading 50k records at once doesn't cause your entire Ember app to freeze? I would think inserting that many into the store would cause it to hang regardless.

**Comment by bebop23** [comment]
Loading 50k records doesn't cause an issues.  I'm using the same dataset in
an ember-collection list and it is able to load the data just fine since it
lazy loads and only shows the rows necessary.

**Comment by itsfadnis** [comment]
Loading 50k records makes no sense, I recently switched from `models-table` to the `models-table-server-paginated` component for the same reason. Works much better.

**Comment by bebop23** [comment]
Why doesn't it make sense?  If it was truly performant, it should be able
to handle that sort if load.

**Comment by mydea** [comment]
I think the reason why showing 50k rows at once freezes is pretty clear. It's also pretty clear why ember-collection might be able to handle this (because it doesn't really render all 50k rows, whereas ember-models-table does). So basically, you have two choices: 

a) use ember-collection and hand-roll your table yourself
b) Do not show 50k rows at once in ember-models-table. Why not just use a reasonable pagination size, e.g. 200 or similar?

**Comment by bebop23** [comment]
The table has 50k+ records, but since it is paginated by default, it will only show 25 records at a time.  It will never show all 50k records at once.  Of course that would be insane.  I profiled the js code and it looks like the performance killer is spent setting up observers.  It appears models-table sets up observers on all the records even though a fraction needs to be shown.

**Comment by bebop23** [comment]
I updated to ember 2.8 and the latest version of ember-models-table (1.9.0) and the issue has been resolved.  Perhaps this is the new glimmer engine at work :)
