### ISSUE TITLE
Can provide a server side paging example?

### ISSUE THREAD

**Issue by ldcofe** [onechiporenko/ember-models-table#125]
I'm trying to use models-table-server-paginated component but i'm not able to make it show up。Can you provide an example to show how to set it up?

**Comment by onechiporenko** [comment]
Hi, @ldcofe.
Here it is: http://onechiporenko.github.io/ember-models-table/#/examples/server-table
Route: https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/routes/examples/server-table.js
Template:
```handlebars
{{my-server-table data=model columns=columns}}
```
`my-server-table`:
```javascript
import ServerModelsTable from 'ember-models-table/components/models-table-server-paginated';

export default ServerModelsTable.extend({

  filterQueryParameters: {
    globalFilter: 'globalSearch',
    sort: 'sort',
    sortDirection: 'sortDirection',
    page: 'page',
    pageSize: 'pageSize'
  }

});
```
