### ISSUE TITLE
displayDataChangedAction sent on focus-out, not on actual change

### ISSUE THREAD

**Issue by arnebit** [onechiporenko/ember-models-table#126]
When I enter something, e.g. a single letter, into a filter field in my models-table, the table content is filtered immediately and the footer is updated immediately, to (e.g. to "Showing 1 - 10 of 33" from "...of 123"). However, the displayDataChangedAction is only sent after I click outside the filter field or press tab.

This is inconventient when I want to use the filtered data elsewhere. I my case, I have a button outside the table that says "Do something with {{filteredContent.length}} datasets" and a very simple dataChangedAction like `this.set('filteredContent', currentSettings.get('filteredContent'));` and the button text and table footer numbers mismatch while the user is entering a filter string.

Can the displayDataChangedAction be sent on every change?

A probably related issue: With the latest version (1.8.1-beta3, compared to 1.8.0), the displayDataChangedAction does not seem to be sent on the first rendering of the component anymore (which meant when entering my respective route, the aformentioned button said "Do something with NaN datasets"). Is that intentional?

**Comment by onechiporenko** [comment]
Hi, @arnebit. Check pls latest version (1.8.1-beta.4). This problem may be solved.

**Comment by arnebit** [comment]
Yes it is. Thank you very much.
