### ISSUE TITLE
Second table header to bottom

### ISSUE THREAD

**Issue by DevellMen** [onechiporenko/ember-models-table#127]
How can i add another table header (thead) to bottom of table?
I need "total" row for each page (i use table with pagination).
PS:  "total" row has same static data on each page

**Comment by onechiporenko** [comment]
Hi, @DevellMen. 
You can specify your own `models-table.hbs`
https://github.com/onechiporenko/ember-models-table/blob/master/addon/templates/components/models-table.hbs
You can write your logic inside `tbody`

**Comment by DevellMen** [comment]
ok, good idea. but how i can pass data through handlebars to my custom tbody?

**Comment by onechiporenko** [comment]
```handlebars
{{! templates/components/models-table.hbs}}
....
  <tr><td colspan={{processedColumns.length}}>{{! any data }}</td></tr>
</tbody>
....
```

**Comment by DevellMen** [comment]
i mean how can i pass custom variable with data

**Comment by onechiporenko** [comment]
```handlebars
{{models-table data=model columns=columns mySuperProperty=mySuperValue}}
```
