### ISSUE TITLE
Filtering custom template content in ember-models-table

### ISSUE THREAD

**Issue by revanar** [onechiporenko/ember-models-table#129]
Hello.  I've just spent several hours trying to figure out a way to get filtering to work when displaying a hasMany relationship via a custom template in a models table.

I currently have the following:

Component Usage:

```handlebars
{{models-table
    data=model
    columns=columns
    groupedHeaders=groupedHeaders
    showColumnsDropdown=false
    filteringIgnoreCase=true
    showTableFooter=false
 }}
```

columns:
```javascript
columns: [
    {
      'propertyName':'book.name',
      'title':'Title'
    },{
      'propertyName':'book.editor.name',
      'title':'Editor'
    },{
      'propertyName':'book.year',
      'title':'Year'
    },{
      'propertyName':'song_no',
      'title':'No.'
    },{
      'propertyName':'name',
      'title':'Name'
    },{
      'template':'custom/languages',
      'title':'Text Language',
    },{
      'template':'custom/pdflink',
      'title':'Download'
    }
  ],
```

custom/languages template:
```handlebars
<ul class="csv">
  {{#each record.languages as |language|}}
    <li>{{language.name}}</li>
  {{/each}}
</ul>
```

Basically, the issue I'm having is that I want to display languages, which is a HasMany relation to songs as a comma separated list, as in this image:
![list](https://cloud.githubusercontent.com/assets/22918992/19489943/2fa96892-953b-11e6-887d-d3c53c26a4cc.png)

However, using a custom template disables filtering, and when I tried creating a filterSelectBox with predefinedFilterOptions, the filter options didn't actually work on the text provided by the custom template.

What is the best means means by which I could have a functional template that searches text in a relationship similar to this?

This is my first time posting, so please let me know if there's any important detail I've left out!  Thank you for your help!

**Comment by onechiporenko** [comment]
Hi, @revanar.
I've created small demo for you https://ember-twiddle.com/ab3b1886dd3bd0e9e9afdfe3a3b46bf1?openFiles=controllers.my-route.js%2C&route=%2Fmy-route
There are few important moments:
* `propertyName` should be defined
* `filterFunction` - custom filter function for value. It takes 3 arguments - stringified cell value (useless in this case), needed string and object (model) for table row.
* To use some predefined options for column 'Languages' you should extend component `models-table` and override `fitleredContent` (this part https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L661-L666)

**Comment by revanar** [comment]
Thank you for the response, @onechiporenko! 

I appreciate you taking the time to make this demo for me.  I'm having trouble getting it to work, because in my model, languages is a hasMany relationship of songs.  I think that replacing `return !!obj.languages.filter(({name}) => name.includes(neededStr)).length;` with something like `!!obj.get('languages').filterBy('name',neededStr).length` ought to make it work, but for some reason it's not working.  Any idea what I'm missing?
