### ISSUE TITLE
How would I reset the data without a full route model refresh?

### ISSUE THREAD

**Issue by cimtico** [onechiporenko/ember-models-table#131]
I'm using the grid in a parent outlet. However when a form submits in the nested outlet, I need to "reload" the grid's contents. is there a way to achieve that?

**Comment by cimtico** [comment]
Currently the only way I see is by changing the sort order or searching. However an attribute toggle or something of the sort could be useful to simply trigger a reload. This is in the case we are using server paginated approach.

**Comment by fenichelar** [comment]
Ever find a good solution? This seems like a very common use case.

**Comment by Ramblurr** [comment]
I too need this feature.

The ember data store can return a `AdapterPopulatedRecordArray` that has a handy `update()` function that will update the records from the adapter, however when calling this function, the table does not update the items.

**Comment by cimtico** [comment]
I haven't found a solution to it yet, and haven't had time to go back to the personal project where I was using this.

**Comment by fenichelar** [comment]
@onechiporenko I don't think the pull request above, #204, addresses this issue as it resets the sorting/filtering.
