### ISSUE TITLE
Zero page based pagination

### ISSUE THREAD

**Issue by Ramblurr** [onechiporenko/ember-models-table#133]
I'm attempting to implement models-table against an API that uses 0 as the first page.

It would be nice if the `_loadData` function also had a `paginationWrapper` to complement the `sortingWrapper`.

Or, if the paginated table exposed the final query before passing it to the store, then the client could perform any modifications they want.

**Comment by onechiporenko** [comment]
Hi, @Ramblurr.
You may use http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_normalizeQueryResponse to update payload before it's pushed to the store.

**Comment by Ramblurr** [comment]
Ah super ! This lets me use standard 1-based paging throughout the app but change it on the fly in the adapter. Thanks.
