### ISSUE TITLE
Server Side Pagination - Option to Sort and Filter data locally.

### ISSUE THREAD

**Issue by SachinR90** [onechiporenko/ember-models-table#138]
Hello,

I went through the Sample example provided for the 'Server Side Pagination' using 'models-table-server-paginated' and found out that , a call is made is for every search/filter and sort operation.  Is there an option to make search/filter and sort to operate on local data and fetch data from server via pagination.

Thanks.

**Comment by onechiporenko** [comment]
Hi, @SachinR90. Described behavior is not supported:
* `models-table` get all records and do sorting, filtering, paginating by itself.
* `models-table-server-paginated` don't do this. It just use `query` to get data from server and update this query with sorting, filtering and pagination options provided by user.
You asking about something  that is in the middle of both this components.
