### ISSUE TITLE
Server Side Pagination - How to display a loading indicator when loading a page from server

### ISSUE THREAD

**Issue by sh9189** [onechiporenko/ember-models-table#139]
I am using models-table-server-paginated for server side pagination and would like to display a custom loading indicator when loading a page of data from server. I see there is a `isLoading` property that is set when loading a page of data from server https://github.com/onechiporenko/ember-models-table/blob/eede120c9716575d0ec0afc7c0dddc517edfd363/addon/components/models-table-server-paginated.js#L11-L18, how can I use this in my template to show a custom loading indicator ?

**Comment by onechiporenko** [comment]
Hi, @sh9189.
You may create your own `templates/components/models-table.hbs` and add this part anywhere you need:
```handlebars
{{#if isLoading}}
  {{! any spinner here}}
{{/if}}
```

**Comment by sh9189** [comment]
Thanks for the quick response @onechiporenko. But I would have to duplicate everything in https://github.com/onechiporenko/ember-models-table/blob/master/addon/templates/components/models-table.hbs in my own `templates/components/models-table.hbs`. I was hoping to avoid that.

**Comment by onechiporenko** [comment]
I did my best (and not even me #97) to split one big `models-table.hbs` to several small parts. But the main one currently can't be separated.

**Comment by sh9189** [comment]
ah.. ok.. @onechiporenko Would you open for accepting a pr for adding a default loading template  that can be overridden? Something also the lines of 
```
<tbody>
  {{#if allColumnsAreHidden}}
    <tr><td colspan={{processedColumns.length}} class="{{classes.noDataCell}}">{{{messages.allColumnsAreHidden}}}</td></tr>
  {{else}}
    {{#if isLoading}}
      <tr><td colspan={{processedColumns.length}}> {{partial loadingPageTemplate}}</td></tr>
    {{else if visibleContent.length}}
      {{#each visibleContent as |record index|}}
        {{partial rowTemplate}}
      {{/each}}
    {{else}}
      <tr><td>{{{messages.noDataToShow}}}</td></tr>
    {{/if}}
  {{/if}}
</tbody>
```

**Comment by onechiporenko** [comment]
Yes, sure. `loadingTemplate` - variable. `app/components/models-table/loading` - value. And empty file in this path.
I'll be glad to merge such PR.

**Comment by onechiporenko** [comment]
One more, I think `isLoading` should be upper than `allColumnsAreHidden`.

**Comment by sh9189** [comment]
Sounds good. Will start to work on a PR.

**Comment by sihuang** [comment]
@sh9189 @onechiporenko has this PR been merged yet?
