### ISSUE TITLE
console.log() bug

### ISSUE THREAD

**Issue by ghamha1n** [onechiporenko/ember-models-table#14]
Good day,

there is console.log() left in the code is logging every time model change, i think you should remove it.

```
   contentChangedAfterPolling: function contentChangedAfterPolling() {
      console.log(arguments);
      get(this, 'filteredContent');
      this.notifyPropertyChange('filteredContent');
    },
```
[here](https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L299)

Thanks

**Comment by onechiporenko** [comment]
Thanks, @ghamha1n
