### ISSUE TITLE
`displayDataChanged`-action should contain models for selected rows

### ISSUE THREAD

**Issue by BennyAlex** [onechiporenko/ember-models-table#141]
Given the following table:
```
{{models-table
data=model
columns=columns
showTableFooter=true
useNumericPagination=true
showColumnsDropdown=true
showGlobalFilter=false
filteringIgnoreCase=true
multipleSelect=true
selectedRowIndexes=selectedRowIndexes
_selectedRowIndexes=_selectedRowIndexes}}
```
and showing the selectedRowIndexes in the template as well:

```
selectedRowIndexes: {{selectedRowIndexes}}
_selectedRowIndexes: {{_selectedRowIndexes}}
```
Sometimes it happens that _selectedRowIndexes is empty, regardless of how many rows are selected:
(the red marked got the class "selected-row")
![image](https://cloud.githubusercontent.com/assets/17402724/20382966/4ab23e18-acae-11e6-955e-c5501f984489.png)

**Comment by BennyAlex** [comment]
I noticed when the _selectedRowIndexes is empty but rows are selected the array will be updated only when I double-click a row

**Comment by onechiporenko** [comment]
Hi, @BennyAlex.
You should not set `selectedRowIndexes` and `_selectedRowIndexes`.
You may get `expandedRowIndexes` value on action with name equal to `displayDataChangedAction`-value `displayDataChanged` by default).
I didn't check behavior for passing variable to `selectedRowIndexes` and `_selectedRowIndexes` while developing.

**Comment by BennyAlex** [comment]
Hi @onechiporenko,
can you tell me exactly please which attribute can be used for to becoming the selected models or the id's of the selected rows? I am not sure if expandedRowIndexes is what I am looking for.

**Comment by onechiporenko** [comment]
@BennyAlex, `selectedRowIndexes` - it's not a set of model ids. I understand what you need. I'll model ids to the `settings` sent on `displayDataChanged`-action.

**Comment by BennyAlex** [comment]
@onechiporenko on Ember-Light-Table for example, the selection array contain all selected models. That is really smart to use, I can just access all proberties from the selected model(s)

**Comment by onechiporenko** [comment]
Got it. I'll put models to the `displayDataChanged` argument.

**Comment by onechiporenko** [comment]
@BennyAlex, check pls latest trunk

**Comment by BennyAlex** [comment]
@onechiporenko can you tell me please how can I use it now?
With "displayDataChangedAction(model, options)" or how?

**Comment by onechiporenko** [comment]
@BennyAlex, action receives 1 arguments. It has field `selectedItems` with list of selected models.
