### ISSUE TITLE
Using ember-models-table without bootstrap

### ISSUE THREAD

**Issue by shivani2692** [onechiporenko/ember-models-table#142]
Hi, I am new to Ember. I would like to know how dependent is ember-models-table on bootstrap. I would like to use ember-models-table in my project but I do not want to be dependent on bootstrap as it affects some of my other components. Is there any way using which I can use ember-models-table without being dependent on bootstrap? Is there a work-around for avoiding bootstrap dependency?

**Comment by onechiporenko** [comment]
Hi, @shivani2692. If you don't use columns dropdown, you may not use bootstrap. TB is used only for styling.

**Comment by avdmatamoros** [comment]
you can easily override the default template and classes to your own custom needs. I remember overriding it to work with ember-materialize-cli
