### ISSUE TITLE
Getting this._updateFiltersWithSelect is not a function in release 1.10.1

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#150]
hwqe-models-table.js:108 Uncaught TypeError: this._updateFiltersWithSelect is not a function(…)_setupColumns @ hwqe-models-table.js:108(anonymous function) @ models-table.js:927sendEvent @ ember.debug.js:16568Class @ ember.debug.js:36161create @ ember.debug.js:36422createComponent @ ember.debug.js:11389ComponentNodeManager_create @ ember.debug.js:11211componentHook @ ember.debug.js:8295handleRedirect @ ember.debug.js:47552inline @ ember.debug.js:47706inline @ ember.debug.js:48233(anonymous function) @ ember.debug.js:48315dirtyCheck @ ember.debug.js:48358inline @ ember.debug.js:48314RenderResult.populateNodes @ ember.debug.js:48653RenderResult.revalidateWith @ ember.debug.js:48625validateChildMorphs @ ember.debug.js:48993validateChildMorphs @ ember.debug.js:48989dirtyCheck @ ember.debug.js:48363block @ ember.debug.js:48308RenderResult.populateNodes @ ember.debug.js:48651RenderResult.revalidateWith @ ember.debug.js:48625validateChildMorphs @ ember.debug.js:48993dirtyCheck @ ember.debug.js:48363content @ ember.debug.js:48320RenderResult.populateNodes @ ember.debug.js:48655RenderResult.revalidateWith @ ember.debug.js:48625validateChildMorphs @ ember.debug.js:48993dirtyCheck @ ember.debug.js:48363content @ ember.debug.js:48320RenderResult.populateNodes @ ember.debug.js:48655RenderResult.revalidateWith @ ember.debug.js:48625validateChildMorphs @ ember.debug.js:48993dirtyCheck @ ember.debug.js:48363content @ ember.debug.js:48320RenderResult.populateNodes @ ember.debug.js:48655RenderResult.revalidateWith @ ember.debug.js:48625RenderResult.revalidate @ ember.debug.js:48602Renderer_revalidateTopLevelView @ ember.debug.js:23195exports.default._emberMetalMixin.Mixin.create._Mixin$create.revalidate @ ember.debug.js:42667invoke @ ember.debug.js:327flush @ ember.debug.js:391flush @ ember.debug.js:192end @ ember.debug.js:570run @ ember.debug.js:692join @ ember.debug.js:712run.join @ ember.debug.js:20709hash.success @ rest.js:745fire @ jquery.js:3148fireWith @ jquery.js:3260done @ jquery.js:9314callback @ jquery.js:9718

**Comment by onechiporenko** [comment]
HI, @PankajWorks. Pls update to the latest version.

**Comment by PankajWorks** [comment]
@onechiporenko  Thanks
