### ISSUE TITLE
Column model moved to private

### ISSUE THREAD

**Issue by ruzz311** [onechiporenko/ember-models-table#152]
**Groveling**  

I've really enjoyed working with this library after years of dealing with other frameworks and their "plugins" for table-data.  Thanks.

**My Issue**  

I've extended the models-table-server-paginated component to better fit my projects defaults and to deal with some differences in how our API accepts sorts/queries without it being too messy or outside of the Ember norm.

However, I've noticed that recently you moved the column definition into ```~/addon/-private/```.  Not sure why, but it makes it a little messy for me to extend the definition.  It forces me to re-write the _setupColumns function (about 70 lines) to add one line of customization.

I get that if someone really messed up the core of the definition it would make ember-models-table's component break but I would like additional properties on column available within my templates.

**Proposal**

Would the maintainers be open to a PR containing this change _(or something similar)_?  Maybe an additional "originalDefinition" property that stuffs the column definition I provided to the component?

**Comment by onechiporenko** [comment]
Hi, @ruzz311. I'm glad you are using this component.
I'm sorry, that sometimes `models-table` changes "accidentally" for users. I understand you proposal and thank you for PR.
