### ISSUE TITLE
Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by nag9329** [onechiporenko/ember-models-table#154]
I know this is not specifically related to ember models table issue. But, I don't see a way to replace the "includes" in **models-table.js** file (clickOnRow method) and **exists-in.js** file (content computed property) where it checks whether the array contains the object/class. I searched a lot in the internet to replace "includes" , for which most of the answers say replace it with "indexOf" which cannot be applied in this case, since the check is not for a simple data type, instead for a class/object in an array.

I could say this is a javascript issue which is happening only in Internet Explorer. Could you able to fix this issue because the add on is not usable in the apps that has to support Internet Explorer.

**Comment by onechiporenko** [comment]
Hi, @nag9329 
Please try to update ember/ember-cli to the latest version - it should help

**Comment by nag9329** [comment]
Hey @onechiporenko, thanks for your quick reply. 

There are so many restrictions for me to update ember-cli to the latest version. But, how come ember-cli latest version has any impact on the "includes" issue, which is happening only in Internet Explorer. Even, if I upgrade to latest ember-cli, the ember-models table still have includes in the code and the Internet Explorer is unable to check the "includes".

Please correct me If I'm wrong. Thanks

**Comment by mydea** [comment]
The latest ember version has a polyfill for includes, which lets you use it in all browsers. So you'll need to update ember to at least 2.8.

**Comment by nag9329** [comment]
Thanks @mydea, I'll try to update my ember version. For now, I'm closing this issue since this looks like a version issue. I'll update the thread if the problem still persists after upgrading the ember.
