### ISSUE TITLE
Need help multi selection of rows : How can i pass index 

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#155]
Hi,

I am trying to use the  multi selection feature. When i am selecting a row i am getting error "Assertion Failed: row index should be numeric" . How can i pass index?

**Comment by onechiporenko** [comment]
Hi, @PankajWorks. Can you please provide a demo on ember-twiddle.com and I'll be able to help you.

**Comment by PankajWorks** [comment]
@onechiporenko  thanks for responding. I will create an twiddle but if you can give some quick hint by looking at the below image it will be helpful. Somehow the index is undefined.
![image](https://cloud.githubusercontent.com/assets/12717111/21268959/d4dd89e6-c3d6-11e6-8fb6-2483cae2a67d.png)

If there is some complete example for multi select other than that on the example page, please do share 

Thanks

**Comment by onechiporenko** [comment]
@PankajWorks, do you use some custom templates? `clickOnRow` is used as click-handler for rows and should be called with row-index. 
In the latest version, this method is improved and works not with indexes and with records.

**Comment by PankajWorks** [comment]
@onechiporenko  Thanks a lot for your help. My bad there was a custom template which used the code of ember-model.hbs of 1.5.0. and some custom code for header and footer. modified the code as per 1.11.0-beta.1 and it started working. 
Thanks again for your support
