### ISSUE TITLE
custom actions with select checkbox causing deselect/select issue

### ISSUE THREAD

**Issue by nag9329** [onechiporenko/ember-models-table#156]
Hi,

I'm using ember-models-table 1.11.0-beta.1. This version has selection of checkboxes, but after adding that feature, I cannot be able to do a custom action alone. If I do a custom action, both the methods (displayDataChanged and actionsClicked) are being called. 

Below is the code of what I've explained above, I'm facing issues in creating a twiddle, I think is because 1.11.0-beta.1 has not published yet. I can update a twiddle if you have one that uses 1.11.0-beta.1.

//index.hbs
`{{my-table-with-custom-header data=model columns=columns multipleSelect=true sendDisplayDataChangedAction=true showColumnsDropdown = false multipleColumnsSorting = false globalFilterUsed = false filteringIgnoreCase = true useFilteringByColumns = false actionsClicked = 'actionsClicked'}}`

//index.js
```
export default Ember.Controller.extend({
       columns: [
               {
	             "template":"component/select-box",
	             "useFilter": false,
	              "mayBeHidden": false,
	              "templateForSortCell": 'component/select-box-all'
	       },
               {
	               "propertyName": "serverName",
	               "title": "Server"
	        },
                {
	                "propertyName": "Delete",
	                "template":"custom/delete",
	                "disableSorting":true
		},
       ]
       actions:{
              displayDataChanged(settings) {
	             console.log(settings.selectedItems);
	       },
	       actionsClicked: function (record) {
	    	     console.log(record);
	       }
        }
});
```
//custom/delete.hbs
`<button {{action 'sendAction' 'actionsClicked' record}}>Delete</button>`

On a whole, the above two action methods are being called when I click on the delete button, instead I'm looking to not select/deselect the row when the delete button is pressed.

On a side note, when I select multiple checkboxes and click on the delete button, same behavior is happening. Request you to take a look at it or if you create a twiddle link with 1.11.0, I can reproduce the issue more clearly.

Thanks,
Nagarjuna

**Comment by onechiporenko** [comment]
Hi, @nag9329.
Did you try to add `bubbles=false` to your action?

**Comment by nag9329** [comment]
Hi @onechiporenko . Thanks for your time, but when I add bubbles=false as below
`<button {{action 'sendAction' 'bubbles=false ' 'actionsClicked' record}}>Delete</button>`

actionsClicked method is not being called now, but  displayDataChanged method is invoked. This is exactly the opposite of what I'm looking for. Ideally, when I click on delete button, actionsClicked should be called and when I click on any other place displayDataChanged should be called. This is happening in your custom actions example  but not after upgrading to beta 1.11 version.

**Comment by onechiporenko** [comment]
@nag9329, `bubbles=false` should be without quotes

**Comment by nag9329** [comment]
Thanks @onechiporenko bubbles = false without quotes is working. But, what if I have some custom dropdown instead of the simple button in the delete.hbs file. Something like below.

`<li class="dropdown" style="list-style:none;">
	<a class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-cog fa-lg" style="color:gray"></i> //gear icon
	</a>
	<ul class="dropdown-menu" style="right: 0; left: auto;">
               <li {{action 'sendAction' 'configureClicked' record bubbles=false}}><a><i class="fa fa-building"></i>Configure</a></li>
		<li {{action 'sendAction' 'actionsClicked' record bubbles=false}}><a><i class="fa fa-cogs"></i>Actions</a></li>
	</ul>
</li>`

The above code will show a dropdown on click of the gear icon which invokes displayDataChanged method. If I try to put an empty action with bubbles=false at top <li> level to stop invoking displayDataChanged, it will also stop showing the dropdown. This is a bit complex scenario than a simple button. Is there a way to stop calling displayDataChanged method and show only dropdown in this case.

**Comment by onechiporenko** [comment]
@nag9329, I think answer is "not at the moment". I'll think about described situation.

**Comment by nag9329** [comment]
ok thanks I'm trying to get it work from my side too. I'll create a PR if I have something working. Please let me know if you can get this scenario working.

**Comment by onechiporenko** [comment]
Ok, thanks

**Comment by nag9329** [comment]
Hey @onechiporenko, I've been trying to get this working but there's of no luck. Most of my upcoming tables would be having the above scenario where there would be a dropdown on click of the button. Would you mind thinking about this scenario, I've been using the add-on since 4 months but because of this issue I'm finding it difficult to use and I'm a bit concerned after all working these many days.

**Comment by onechiporenko** [comment]
@nag9329, I'll check what may be done to get it work

**Comment by nag9329** [comment]
Hi @onechiporenko I figured out the issue, but it seems like a temporary fix, It would be great if the add-on has the capability to do this. Below is the way that is working for me now.

```
<li class="dropdown" style="list-style:none;">
     <a class="dropdown-toggle" data-toggle="dropdown" {{action sendAction 'gearClicked' bubbles = false}}>
          <i class="fa fa-cog fa-lg" style="color:gray"></i> //gear icon
     </a>
     <ul class="dropdown-menu" style="right: 0; left: auto;">
           <li {{action 'sendAction' 'configureClicked' record bubbles=false}}><a><i class="fa fa-building"></i>Configure</a></li>
           <li {{action 'sendAction' 'actionsClicked' record bubbles=false}}><a><i class="fa fa-cogs"></i>Actions</a></li>
     </ul>
</li>
```

and in my js file, I'm opening the dropdown programmatically as below
 
```
	    gearClicked: function () {
	    	$('.dropdown-toggle').dropdown();
	    }
```

Though it seems like a work around, I feel it would be much more elegant if the add-on itself has a way to do it. I'm closing this issue now, please feel free to open and provide a better solution if you have time. Thanks
