### ISSUE TITLE
Multi-Column support for model-table-server-pagination

### ISSUE THREAD

**Issue by ruzz311** [onechiporenko/ember-models-table#159]
There's no multi-column support in the server-paginated table.  Where there limitations that prevented this from being implemented?

**Comment by ruzz311** [comment]
I wouldn't mind looking into it but wanted to know if there was some code I'm not seeing that makes it terribly difficult.

**Comment by onechiporenko** [comment]
@ruzz311, multi-column for sorting, filtering, selecting?

P.S. I'll check your answer in the morning, because my local time is late night now.

**Comment by ruzz311** [comment]
Sorting was what I had been looking at: https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table-server-paginated.js#L259 disregards the ```component.multipleColumnsSorting``` property and is hard-coded to single sort.

**Comment by onechiporenko** [comment]
@mydea provided such behavior in #62:

> Sorting will not use multipleColumnSorting, it will only sort by one column.

**Comment by ruzz311** [comment]
@mydea did an excellent job extending models-table but I would like to point out a quote from #62 

> Sorting will not use multipleColumnSorting, it will only sort by one column.

At work we've dealt with a few idiosyncrasies when using feathersjs + sequelize as our API layer and handle those differences with this add-on in our adapter / serializers (cleaning them and setting sort/order parameters).  However I cannot get a sane dataset to do this without extending the model-table-server-pagination component.

Enabling multi-sort for DS.Model data needs a solution and I'd be glad to share mine as a PR when I have it complete (ideally utilizing the current globalFilter/Search).

**Comment by mydea** [comment]
At the time of writing, I figured multi-column sorting would introduce more complexity in how to translate the sort params to the API. You'd need to have a definable function to convert the sort params to API query params. But of course this could be done :)

**Comment by ruzz311** [comment]
Thanks @mydea - I really like the work that was started but I'm finding places where it falls just short of the power the base model-data-table component offers.  As I've been trying it out I've be submitting PR's to add functionality back or small fixes.  I've been ill for a lot of the end of December but I'll try to tag you on the PR when I figure it out so I can get your critique since you were the original author.

**Comment by onechiporenko** [comment]
Fixed in https://github.com/onechiporenko/ember-models-table/issues/328
