### ISSUE TITLE
Feature Request: Columns generated from data

### ISSUE THREAD

**Issue by ruzz311** [onechiporenko/ember-models-table#160]
**User Story:** When I'm using the models-table-server I've already defined my models, essentially giving enough config to generate a column configuration.   It would be nice if I could supply either table components a "defaultColumns" array that allows an array of propertyName strings OR an array of objects that support the same properties as "columns".

Basically this gives the ability to use the plugin without having to supply column names up-front.

Forgive the inline Ember.A, but for a pseudo-example:
```handlebars
{{models-table-server-paginated data=model defaultColumns=Ember.A(['id', 'firstName' 'lastName'])}}
```

Which should render the table showing the 3 columns you specified while automatically hiding the rest of the columns.

I've used this technique along with model attribute options to use known cell templates for defined types and other custom options such as title or description that is nice to have defined next to your model.

I've gotten pretty close to a solution that I think could be used for both components but it needs a little more work and would like to know if this new functionality interests the maintainers / user-community.

**Comment by lrsnider** [comment]
@ruzz311 I would definitely be interested in adding this config to generate column configuration from your data.

**Comment by ruzz311** [comment]
Sweet!  I had worked on this a bit ago but nobody seemed that interested - maybe you could find a better way than my PR?
