### ISSUE TITLE
Problems rendering grid with Ember 2.10

### ISSUE THREAD

**Issue by jefdeveloper** [onechiporenko/ember-models-table#161]
I'm trying to create a simple demo website using Ember Models Table, but I'm getting this error: 

> Uncaught TypeError: data.filter is not a function
    at Class.<anonymous> (models-table.js:696)
    at ComputedPropertyPrototype.get (ember.debug.js:16305)
    at get (ember.debug.js:21212)
    at Class.<anonymous> (models-table.js:744)
    at ComputedPropertyPrototype.get (ember.debug.js:16305)
    at Object.get (ember.debug.js:21212)
    at getProperties (ember.debug.js:17439)
    at Class.<anonymous> (models-table.js:783)
    at ComputedPropertyPrototype.get (ember.debug.js:16305)
    at Object.get (ember.debug.js:21212)

Here is my template code
```handlebars
<div class="row">
    <div class="col-md-12">
    {{models-table data=model columns=columns}}
    </div>
</div>
```

Here is my controller.js:
```javascript
import Ember from 'ember';

const {A} = Ember;

export default Ember.Controller.extend({

  title: 'Common table',
  model: function(params) {
    return Ember.$.getJSON('http://localhost:5000/api/subjects').then((data) => {
        return this.store.push({
            data: data
        });
    });
  },
  columns: A([
    {
      propertyName: 'name',
      title: 'Name'
    },
    {
      propertyName: 'pic',
      title: 'PIC'
    }
  ])

});
```
The API JSON return:

```javascript
[
  {
    "id": 1,
    "name": "Subject 1",
    "pic": "LAMHIQ854"
  },
  {
    "id": 2,
    "name": "Subject 2",
    "pic": "KJUIL"
  }
]
```
ember-cli: 2.10.0
node: 6.9.1
os: win32 x64

**Comment by onechiporenko** [comment]
Hi, @jefdeveloper. `Ember.$.getJSON` returns not an array. It returns `xhr`. You should receive `model` in the Route for current page in the hook `model`.

**Comment by jefdeveloper** [comment]
I transferred the model to the route, the error is not displaying , but the grid is not being rendered anymore. What I'm missing?

Here is my route code now:

"import Ember from 'ember';

const {A} = Ember;

export default Ember.Route.extend({
    model: function () {
        return [{ "name": "Subject 1", "pic": "LAMHIQ854" }, { "name": "Subject 2", "pic": "KJUIL" } ];
    }
});"

**Comment by onechiporenko** [comment]
@jefdeveloper, could you provide a whole code pls? Route, Controller, Template

**Comment by jefdeveloper** [comment]
Template:

<div class="row">
    <div class="col-md-12">
    {{models-table data=model columns=columns}}
    </div>
</div>

Route:

import Ember from 'ember';

const {A} = Ember;

export default Ember.Route.extend({
    model: function () {
        return [{ "name": "Subject 1", "pic": "LAMHIQ854" }, { "name": "Subject 2", "pic": "KJUIL" } ];
    }
});

Controller:

import Ember from 'ember';

const {A} = Ember;

export default Ember.Controller.extend({

  title: 'Common table',
  columns: A([
    {
      propertyName: 'name',
      title: 'Name'
    },
    {
      propertyName: 'pic',
      title: 'PIC'
    }
  ])

});

**Comment by jefdeveloper** [comment]
Hi @onechiporenko,

It's working now. The template is not rendering because I was not pointing the correct outlet to be rendered in application template.

Thanks for your help´.
