### ISSUE TITLE
regarding - Uncaught ReferenceError: ModelsTableColumn is not defined

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#164]
I am facing a problem a problem while writing a custom _setupColumns function.

I wish to add an export table functionality for which i need to add the code
`
nColumns.filterBy('propertyName').forEach(column => {
      var propertyName = get(column, 'propertyName');

      //custom making two-side binding for use with export-pdf, export-csv components
      if (get(column, 'isVisible')) {
        get(this, 'columns').findBy('title', get(column, 'title')).set('isVisible', true);
      };

 `

What i did is copied the complete _setupColumns()  and put that in my custom component. 
Earlier it was working fine but with latest release it is giving me error

`
Uncaught ReferenceError: ModelsTableColumn is not defined
`
How to get it corrected

**Comment by onechiporenko** [comment]
`ModelsTableColumn ` is a private instance (`addon/-private`). 
Why do you need to duplicate `_setupColumns`?

**Comment by PankajWorks** [comment]
Thanks @onechiporenko for quick reply , Basically i want to add export to pdf and export to excel functionality. With v1.5 the way i did is copy the function _setupColumns and add  the following extra lines

`
  //custom making two-side binding for use with export-pdf, export-csv components
  if (get(column, 'isVisible')) {
    get(this, 'columns').findBy('title', get(column, 'title')).set('isVisible', true);
  };
`
Is may be crude way to do it but it helped.

Is there a better way to do it

**Comment by onechiporenko** [comment]
You may handle `displayDataChangedAction` (http://onechiporenko.github.io/ember-models-table/#/examples/display-data-changed-action) to get data shown in the table and do export outside the component

**Comment by onechiporenko** [comment]
To check columns visibility you may hanfle action `columnsVisibilityChangedAction`

**Comment by PankajWorks** [comment]
Thanks @onechiporenko , i will try it will it select only visible columns or all columns

**Comment by gep13** [comment]
@PankajWorks did you get this resolved?  Do you have an example of what you did?  You mentioned an `export-pdf` and `export-csv` components.  Are those your own, or where can I find them?  Thanks!

@onechiporenko perhaps you might know the answer to the above as well, thanks!
