### ISSUE TITLE
How to add links to external source from table cell

### ISSUE THREAD

**Issue by shivani2692** [onechiporenko/ember-models-table#166]
For example: Link to JIRA from our app

<table>
<tbody>
<tr>
   <td><a href="https://jira.atlassian.com/browse/JRA-4980">JRA-4980</a></td>
</tr>
</tbody>
</table>

**Comment by shivani2692** [comment]
Currently, I am getting a string "<a href="https://jira.atlassian.com/browse/JRA-4980">JRA-4980</a>" as a string

And using transforms like:
import Transform from 'ember-data/transform';

export default Transform.extend({
  deserialize: function(serialized) {
    var el = document.createElement( 'html' );
    el.innerHTML = serialized;
    return el;
  },

  serialize: function(deserialized) {
    return deserialized.innerHTML;
  }
});


This shows up as link in table but then the links are not capable

**Comment by onechiporenko** [comment]
You may create template `custom/external-link.hbs`:
```handlebars
<a target="_blank" {{action "emptyAction" on="click" preventDefault=false}} href={{get record column.propertyName}}>Link</a>
```

Column with link should be configured like this:
```javascript
{template: 'custom/external-link', propertyName: 'href'}
```

Pls try this with latest github code. If it help you, I'll publish next release with this changes

**Comment by shivani2692** [comment]
I tried this and it is working. Thank you so much :)

FYI- I am using ember-models-table 1.10.1 in my app
