### ISSUE TITLE
Relationships in dropdown filter with predefined options

### ISSUE THREAD

**Issue by ScottShannon** [onechiporenko/ember-models-table#167]
Is it possible to use one property of a relationship as a display value and another property as the filter value?  For example, with the models provided below, let's say we want to list all of our tickets in a server paginated table and allow filtering by dropdown of the user it belongs to (setting predefinedFilterOptions with a preloaded list of users).  In this case, we would want to use the name property as the value to display and the id property as the filter value.  The only way I was successful with getting this to work was by completely overriding a few of the core methods and adding a filter template, which will quickly become a pain to keep up to date, since if the method gets updated here, the new method would need to be copied and modified to keep this functionality and the package from not breaking.
```
// user.js
export default Model.extend({
	name: attr('string'),
	tickets: hasMany('ticket')
});

// ticket.js
export default Model.extend({
	userId: belongsTo('user')
});
```

**Comment by onechiporenko** [comment]
Hi, @ScottShannon. Currently it is not possible. I'll think about adding this ability

**Comment by onechiporenko** [comment]
@ScottShannon, you may use `predevinedFilterOptions` like:
```javascript
[{value: 1, label: 'one'}, {value: 2, label: 'two'}]
