### ISSUE TITLE
Server paginated table shows wrong firstIndex

### ISSUE THREAD

**Issue by huberts** [onechiporenko/ember-models-table#169]
There is an issue with firstIndex on 'models-table-server-paginated' component. If the filter returns zero elements, then table summary displays:

> Show 1 - 0 of 0

It could be easly fixed with following code in the component:

```
firstIndex: computed('arrangedContent.[]', 'pageSize', 'currentPageNumber', function () {
  if (get(this, 'arrangedContent.length') > 0) {
    return get(this, 'pageSize') * (get(this, 'currentPageNumber') - 1) + 1;
  } else {
    return 0;
  }
}),
```

**Comment by onechiporenko** [comment]
Hi, @huberts! Thanks for report. I'll check it

**Comment by joshuataylor** [comment]
With this, it now displays: `Show 0 - 0 of 0`, but my table has results.

**Comment by onechiporenko** [comment]
@joshuataylor, I've changed only `firstIndex` and didn't do anything with `lastIndex` and `arrangedContent`. Could you provide your component usage?

**Comment by joshuataylor** [comment]
@onechiporenko I've created a PR at https://github.com/onechiporenko/ember-models-table/pull/170 to show the test that also fails with the same problem I'm experiencing.

**Comment by joshuataylor** [comment]
I'm an idiot, I realised my API wasn't returning this, only in the headers.

Couldn't figure out how to get the info from the headers, so just added the `total_entries`/`total_pages` to the meta response (using JSONAPI). Not great (from my end), but a solution.
