### ISSUE TITLE
Integers sort behavior

### ISSUE THREAD

**Issue by smottt** [onechiporenko/ember-models-table#171]
I have a column which displays integers.

For example, the values might be:

`[8738, 1931, 1284, 15, 220]`

When they get sorted (asc) they get sorted like:

`[1284, 15, 1931, 220, 8738]`

While I would expect them to be sorted like:

`[15, 220, 1284, 1931, 8738]`

Is there any way to achieve this?

**Comment by onechiporenko** [comment]
Hi, @smottt. What version of component do you use?
Almost half a year we use `Ember.compare` to compare values doing sorting. `Ember.compare` correctly handles numbers even thier string representations. 
So, I can't reproduce described issue

**Comment by smottt** [comment]
I did a bit of testing and it seems the problem is in the string representation of the integers.

Using latest versions of both the component (2.11) and Ember CLI (2.10):

controllers/demo.js:

```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
    modelData: [
        { totalString: '8738', totalInt: 8738 },
        { totalString: '1931', totalInt: 1931 },
        { totalString: '1284', totalInt: 1284 },
        { totalString: '15',   totalInt: 15 },
        { totalString: '220',  totalInt: 220 }
    ],

    tableColumns: [
        {
            propertyName: 'totalString',
            title:        'Total String'
        },
        {
            propertyName: 'totalInt',
            title: 'Total Integer'
        }
    ]
});
```

templates/demo.hbs

```javascript
{{models-table data=modelData columns=tableColumns}}
```

You can see that sorting works with integers, but not with integers that are represented as strings. Just posting this in case you are curious about it. I think this issue can be closed.
