### ISSUE TITLE
When I reorder my data I cant see the changes on the table

### ISSUE THREAD

**Issue by zardaloop** [onechiporenko/ember-models-table#172]
I have created  a template which has a two button for up and down 

```handlebars
<div class="btn-group-vertical">
  <button {{action "sortUp" record}} type="button" class="btn btn-primary"><i class="fa fa-sort-asc" aria-hidden="true"></i></button>
  <button {{action "sortDown" record}} type="button" class="btn btn-primary"><i class="fa fa-sort-desc" aria-hidden="true"></i></button>
</div>
```

 when I click on them I get the index of the the selected record and moving it up or down using this npm package https://www.npmjs.com/package/array.prototype.move
to be able to import npm package to ember I have installed 

> ember-browserify

to be clear I have extended modelsTableComponent and I am including the template when 

> reorder=true

here is the component that I have.
```javascript
import modelsTableComponent from 'ember-models-table/components/models-table';
import Ember from 'ember';

export default modelsTableComponent.extend({
  didReceiveAttrs() {
    if(this.reorder){
      this.columns.unshiftObject(
        {
          "template": "custom/reorder"
        });
    }
},
  actions: {
    sortDown(record){
      var dataList = this.get('data');
      var index = dataList.indexOf(record);
      if(index < dataList.length){
        
      dataList.move(index, index + 1);
      console.log("from index of " + index + " moved to index of " + dataList.indexOf(record));
      this.set('data', dataList);
      }
    },
    sortUp(record){
      var dataList = this.get('data');
      var index = dataList.indexOf(record);
      if(index !== 0){
      dataList.move(index, index - 1);
      console.log("from index of " + index + " moved to index of " + dataList.indexOf(record));
      this.set('data', dataList);
      }
    }
  }
});
```
and here is how I call it 

```handlebars
{{my-table
          data=table.data
          columns=table.columns
          reorder=true
          }} 
```

when I log the data it seems to be doing exactly what I expect it to do but I can't see that change on the table. Do I need to do set some sort of property to be able to see the changes on the table ? Thanks

**Comment by onechiporenko** [comment]
Hi, @zardaloop. `array.prototype.move` doesn't trigger dependent properties to be updated. `move` updates `data` internaly, but `filteredContent` dependent on it (`data.[]`) is not updated. You should force updading in your actions using: 
```javascript
Ember.propertyWillChange(this, 'data');
this.set('data', dataList);
Ember.propertyDidChange(this, 'data');
```
I didn't check this solution, but it should help you.

**Comment by zardaloop** [comment]
Many thanks @onechiporenko  notifyPropertyChange did the trick. Also I had a little bit of bug on the code above which I have fixed so the correct functions are as follows if in case you might decide to add the sorting example to the demo page :) or you might have a better solution than this .

```
     sortDown(record){
       var dataList = this.get('data');
       var index = dataList.indexOf(record);
       if(index < dataList.length -1 ){        
         dataList.move(index, index + 1);
         this.set('data', dataList);
         this.notifyPropertyChange('data');
      }

    },
    sortUp(record){
      var dataList = this.get('data');
      var index = dataList.indexOf(record);
      if(index !== 0){
         dataList.move(index, index - 1);
         this.set('data', dataList);
         this.notifyPropertyChange('data');
      }
    }
```
