### ISSUE TITLE
search box and pagination not work

### ISSUE THREAD

**Issue by davidjonz2005** [onechiporenko/ember-models-table#175]
Hi @onechiporenko 

i have problem with filter in both global and column input and pagination.

i install this add on by 

> ember install ember-models-table

 and my ember is 

> DEBUG: -------------------------------  vendor.js:20574:5
> DEBUG: Ember              : 2.11.0  vendor.js:20574:5
> DEBUG: Ember Data         : 2.11.0  vendor.js:20574:5
> DEBUG: jQuery             : 3.1.1  vendor.js:20574:5
> DEBUG: Ember Models Table : 1.11.0  vendor.js:20574:5
> DEBUG: Ember Simple Auth  : 1.2.0  vendor.js:20574:5
> DEBUG: -------------------------------  vendor.js:20574:5

i installed bootstrap 3.3.7 and import it's library to ember-cli-build.js 

i created a route foo and below is foo.hbs

> `{{my-server-table data=model columns=columns}}`

below is my foo.js in routes
```
import Ember from 'ember';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';
export default Ember.Route.extend(AuthenticatedRouteMixin,{
  model() {
    return this.get('store').query('foodatafromdjango', {});
  },
  setupController(controller) {
    controller.set('columns', [
      {propertyName: 'id'},
      {propertyName: 'name'},
      {propertyName: 'email'},
      {propertyName: 'phone'},
      {propertyName: 'totalrequest'},
      {propertyName: 'acceptancerate'},
      {propertyName: 'status'},
      {propertyName: 'action'}

    ]);
    return this._super(...arguments);
  }
});
```
and below is 

> my-server-table.js

  in 

> ember-foo/app/component

 folder

```
import ServerModelsTable from 'ember-models-table/components/models-table-server-paginated';

export default ServerModelsTable.extend({

  filterQueryParameters: {
    globalFilter: 'globalSearch',
    sort: 'sort',
    sortDirection: 'sortDirection',
    page: 'page',
    pageSize: 'pageSize'
  }

});
```

**Comment by davidjonz2005** [comment]
i found that when i search sth in a column this add-on send a GET request to backend like this e.g to find id=1  
> http://somehost/api/foo?id=1&page=1&pageSize=25

and the same reason is for page size
so i must prepare my backend

i just put this for other beginner like me

**Comment by davidjonz2005** [comment]
i found out that my django backend already paginate the response but how does your add on interpret it's response as it send ,first page ,last page , next page and previous page link and send data count and page size,
do i need to install any thing in ember ?

**Comment by onechiporenko** [comment]
Hi, @davidjonz2005. You should add options to your component `my-server-table`:
```javascript
metaPagesCountProperty: 'pagination.page',
metaItemsCountProperty: 'pagination. ????'
```

First one determines meta-key where is information about how many pages are. Second one determines meta-key where is information about overall items count (I guess it's `pagination.count` in your example).

I think it should be enough. If not fill free to ask here.

P.S. I don' know what is `id=1` in your query-string.

**Comment by davidjonz2005** [comment]
Hi, @onechiporenko ,thanks for quick reply i put those two magic line and it's working now 
this is 

> my-server-table.js

 file now i put it for other user that may have the same problem
```
import ServerModelsTable from 'ember-models-table/components/models-table-server-paginated';
export default ServerModelsTable.extend({
  metaPagesCountProperty: 'pagination.pages',
  metaItemsCountProperty: 'pagination.count',
  filterQueryParameters: {
    globalFilter: 'globalSearch',
    sort: 'sort',
    sortDirection: 'sortDirection',
    page: 'page',
    pageSize: 'pageSize'

  }

});
```
but about P.S , i searched in id column 

> 1

and i notice it sends 

>http://localhost:8000/api/foo?id=1&page=1&pageSize=10
on network to catch result from backend as it sends some url parameter when changing other parameter like pagesize 
 

> http://localhost:8000/api/foo?page=1&pageSize=10


> http://localhost:8000/api/foo?page=1&pageSize=25

that is not working in my case because of my backend does not respond to the request and always sends all data(not query result) with pagesize =10

**Comment by davidjonz2005** [comment]
this is my solution in 

> Django Rest Framework 

to match backend with 

> Ember-models-table 

it takes me two days to understand Django and create this may help somebody so i share it here

```
from rest_framework import viewsets
from models import foo
from django.core.paginator import Paginator

class fooViewSet(viewsets.ModelViewSet):
  
    serializer_class = fooSerializer
    def perform_create(self, serializer):
    	serializer.save(user=self.request.user)
    class JSONAPIMeta:
        resource_name = "foo"
    def get_queryset(self):
        queryset = foo.objects.all()
        sqlquery = "SELECT * "
        sqlquery+=" FROM myapp_foo WHERE 1 = 1"
        index = self.request.query_params.get('id', None)
        firstname = self.request.query_params.get('firstname', None)
        lastname = self.request.query_params.get('lastname', None)
        email = self.request.query_params.get('email', None)
        phone = self.request.query_params.get('phone', None)
        totalrequest = self.request.query_params.get('totalrequest', None)
        acceptancerate = self.request.query_params.get('acceptancerate', None)
        action = self.request.query_params.get('action', None)
        status = self.request.query_params.get('status', None)
        sort = self.request.query_params.get('sort', None)
        sortDirection = self.request.query_params.get('sortDirection', None)
        page = self.request.query_params.get('page', None)
        pageSize = self.request.query_params.get('pageSize', None)
        if index is not None:
            sqlquery+=" AND id LIKE '%%"+index+"%%' "
        if firstname is not None:
            sqlquery+=" AND firstname LIKE '%%"+firstname+"%%' "
        if lastname is not None:
            sqlquery+=" AND lastname LIKE '%%"+lastname+"%%' "
        if email is not None:
            sqlquery+=" AND email LIKE '%%"+email+"%%' "
        if phone is not None:
            sqlquery+=" AND phone LIKE '%%"+phone+"%%' "
        if totalrequest is not None:
            sqlquery+=" AND totalrequest LIKE '%%"+totalrequest+"%%' "
        if acceptancerate is not None:
            sqlquery+=" AND acceptancerate LIKE '%%"+acceptancerate+"%%' "
        if action is not None:
            sqlquery+=" AND action LIKE '%%"+action+"%%' "
        if status is not None:
            sqlquery+=" AND status LIKE '%%"+status+"%%' "
        if sort is not None:
            sqlquery+=" ORDER BY "+sort
        if sortDirection is not None:
            sqlquery+=" "+sortDirection
        sqlquery+=";"
        print sqlquery
        queryset = list(Driver.objects.raw(sqlquery))
        if pageSize is not None:
            paginator = Paginator(list(queryset), pageSize)
        return queryset
```

all you must do is override 

> def get_queryset(self):
and customize your query there
