### ISSUE TITLE
[Documentation Inconsistency] Wrong attribute name in column custom component attributes

### ISSUE THREAD

**Issue by phndiaye** [onechiporenko/ember-models-table#178]
Firs of all, thanks for that amazing project 👍 

I am currently extending it for custom features and had to use Column's custom component attribute. So i saw an inconsistency between the code and the documentation.

In fact, the documentation names `row` (for current record) as one of the arguments the custom component receives (https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/templates/index.hbs#L89) but the attribute is actually `record` (https://github.com/onechiporenko/ember-models-table/blob/master/app/templates/components/models-table/row.hbs#L18)

Thanks again :)

**Comment by onechiporenko** [comment]
Hi, @phndiaye. Thanks for report!
