### ISSUE TITLE
Column search is case sensitive - should this be an option flag within the column overrides?

### ISSUE THREAD

**Issue by JonRowley** [onechiporenko/ember-models-table#18]
The global search is case insensitive but the column search is case sensitive.

eg. row contains "John Smith".
global search "john smith" returns the row.
column search "john smith" returns empty.

**Comment by onechiporenko** [comment]
Hi, @JonRowley.
I've tried to reproduce this issue on the 1st table in the http://onechiporenko.github.io/ember-models-table/
* I put `Ingeborg` in the global search and got 1 row.
* I put `Ingeborg` in the First Name column search and got 1 row too.
* I put `ingeborg` in the global search and didn't get nothing.
* I put `ingeborg` in the First Name column search and didn't get nothing too.
Are you sure that global search ignore case?

**Comment by JonRowley** [comment]
ah, It might have been due to the fact that John Smith had a username that was "@johnsmith". Is there an option to turn off case sensitivity?

**Comment by onechiporenko** [comment]
No, this option currently doesn't exist. But I'll add it.
