### ISSUE TITLE
Clickable rows

### ISSUE THREAD

**Issue by TheFragen** [onechiporenko/ember-models-table#180]
I know clickable cells is possible, but I would like to catch row clicks in an action. I've seen evidence in the source that you already have handlers for this in the addon (e.g. 'clickOnRow()'), so perhaps expose these?

Best,
Christian

**Comment by onechiporenko** [comment]
@TheFragen, sorry for such late response.
You can handle `displayDataChangedAction` (and should set `sendDisplayDataChangedAction` to `true`). This action will receive data with field `selectedItems`. It contains list of all selected items (which represent rows).
