### ISSUE TITLE
Allow for custom Empty State template

### ISSUE THREAD

**Issue by phndiaye** [onechiporenko/ember-models-table#181]
Hi! 

I think it can be nice to have the possibility to have a **custom Empty State template** for letting developers handle that state as they wish (for example, to have a nice illustration instead of some text only). Currently, if there is no data for the data table, the text defined by the `noDataShow` attribute is displayed (with default to: **No records to show**) (cf. https://github.com/onechiporenko/ember-models-table/blob/e4c37a3bf316648de5aa94f439f6645a733e2a21/addon/templates/components/models-table.hbs#L39)

What I have in mind is (like some other parts in the library) to have a `noDataShowTemplate` so we can do something like this:

```
{{#if visibleContent.length}}
  {{#each visibleContent as |record index|}}
    {{partial rowTemplate}}
  {{/each}}
{{else}}
  {{#if noDataShowTemplate}}
    {{partial noDataShowTemplate}}
  {{else}}
    <tr><td colspan="{{visibleProcessedColumns.length}}">{{{messages.noDataToShow}}}</td></tr>
  {{/if}}
{{/if}}
```

If this seems good to you, I will be glad to work on it :)

**Comment by onechiporenko** [comment]
Hi, @phndiaye. It's a good idea.
