### ISSUE TITLE
[Request]: Please add support for material-design-icons

### ISSUE THREAD

**Issue by BennyAlex** [onechiporenko/ember-models-table#184]
Hello,
would it be possible to add suport for the material design icons?
Actually they cant be used because the icons arnt class based, eg: `<i class="material-icons">arrow_drop_down</i>`

**Comment by onechiporenko** [comment]
@BennyAlex, why `customClasses` and `customIcons` can't be redeclared to use material (see docs http://onechiporenko.github.io/ember-models-table/)? Do they miss something?

**Comment by meliborn** [comment]
Does `customIcons` works in latest version? Can't find it in sources.

**Comment by onechiporenko** [comment]
@meliborn `customIcons` are for v1. Themes are used for v2. Check http://kronus.me/2017/10/theming-ember-models-table-2-x/
