### ISSUE TITLE
Need one help around filterfunction

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#187]
Hi @onechiporenko ,

Is there a sample implementation which i can use as reference for my customfilterFunction. 

Thanks for this beautiful library

~Pankaj

**Comment by onechiporenko** [comment]
Hi, @PankajWorks.
Check `filtering by columns with custom functions` (https://github.com/onechiporenko/ember-models-table/blob/master/tests/integration/components/models-table-test.js#L651).
`signFilter` is defined in the top of file with tests.

**Comment by PankajWorks** [comment]
@onechiporenko  Thanks it will help
