### ISSUE TITLE
[Request]: 'expand all' and 'collapse all' abilities for tables with expandable rows.

### ISSUE THREAD

**Issue by CmdrChaos** [onechiporenko/ember-models-table#193]
provide ability to expand all records and collapse all records for tables with expandable rows.

**Comment by onechiporenko** [comment]
Hi, @CmdrChaos. I'll think what can be done here

**Comment by CmdrChaos** [comment]
I appreciate it!  I have several scenarios where this would be very useful.
Cheers.

**Comment by onechiporenko** [comment]
@CmdrChaos, please check `expandable rows` example to see, how to use "Expand/Collapse All".

**Comment by CmdrChaos** [comment]
Thank you.  Will do!
