### ISSUE TITLE
[Question]: How to passing action into column template

### ISSUE THREAD

**Issue by BennyAlex** [onechiporenko/ember-models-table#199]
@onechiporenko 
I have a button template:
```
//table-button.hbs
<button onclick="{{action column.onClick record}}">click here</button>
```

and I have my table columns:
```
//my-component.js

import Ember from "ember";
const {A, Component} = Ember;

export default Component.extend({
columns: A([
    {
      title: "button",
      disableSorting: true,
      disableFiltering: true,
      template: 'models-table/table-button',

      onClick: function (item) {
        this.send('myAction', item);
      }
  ]),
actions: {
   myAction(item) {
     console.log(item);
}
});

```
I want to passing the myAction to the table-button, but when click on the button I get an error.
Can you help me, please?

**Comment by onechiporenko** [comment]
@BennyAlex, what kind of error did you get?

**Comment by BennyAlex** [comment]
@onechiporenko 
The myAction is not defined in models-table. I know why this happens, because the template will be rendered in the models-table context because of the partitial helper. So how can I say that myAction from my-component should be called?

**Comment by onechiporenko** [comment]
@BennyAlex, maybe https://github.com/DockYard/ember-route-action-helper can help you?

**Comment by arnebit** [comment]
@BennyAlex I think you simply need an arrow function (where the context is not set to the caller on evaluation):

`onClick: item => this.send('myAction', item)`

Of course, if your action is rather short and not reused elsewhere, you do not even need a separate action:

`onClick: item => { console.log(item); }`

**Comment by dirkdirk** [comment]
I did it like this (not sure if this the best solution, but it works):

### Theory
1. Install ember-route-action-helper.
1. Place a button on models-table cell template that uses `route-action`.
1. Router catches the action and sends the record to the controller.
1. Controller action handles what I want to do with the record.
 
### How to

```
$ ember install ember-route-action-helper
```

```
templates/components/models-table/podcast.hbs
 
  <button class='btn btn-info' type='button' onClick={{route-action 'editPodcast' record}}>Edit</button>
```

```
routes/admin.js
 
  actions: {
    editPodcast(record) { this.controllerFor('admin').send('editPodcast', record); },
  }
```

```
controllers/admin.js

actions: {
    editPodcast(podcast) {
      // Your heart's desires here ...
    }
}
```
