### ISSUE TITLE
Sorting 

### ISSUE THREAD

**Issue by KirillSuhodolov** [onechiporenko/ember-models-table#20]
<img width="151" alt="screen shot 2015-09-20 at 15 59 47" src="https://cloud.githubusercontent.com/assets/2364406/9980844/a9c2cdec-5fb0-11e5-9158-fa5f20c7278f.png">

Can columns be sorted as number, not strings?

**Comment by onechiporenko** [comment]
Columns are sorted using [Ember.compare](http://emberjs.com/api/#method_compare).
So, if  column's data is list of numbers it will be sorted as numbers.
Example: ID-column in the all [examples](http://onechiporenko.github.io/ember-models-table/) is numerical and is sorted as numbers.

**Comment by josefguenther** [comment]
For anyone that finds this: DS.Model.id is always a string. No easy solution but a custom property...
