### ISSUE TITLE
How to access the selected Rows?

### ISSUE THREAD

**Issue by BennyAlex** [onechiporenko/ember-models-table#201]
@onechiporenko @mydea  @PhilipTsv 

Hello guys,
How I can access the selected Rows? I want the selected Items(models)?

**Comment by onechiporenko** [comment]
@BennyAlex, check http://onechiporenko.github.io/ember-models-table/#/examples/select-rows-with-checkboxes example

* set option `sendDisplayDataChangedAction=true`
* provide any mechanism to select row (checkboxes from the example may be used)
* Action `displayDataChanged` should exist in the controller or parent component where `models-table` is displayed. This action handles one parameter:
```javascript
displayDataChanged(e) {
  // e.selectedItems; <-- selected rows (models)
}
```

**Comment by BennyAlex** [comment]
@onechiporenko 
This has two big disadventages: 
 - You have to implement the displayDataChanged-Action in every Controller/Component where do you want to use your table. I cant create a new table and extend it from models-table (like you did it with 'my-table-with-custom-header') and place the action there, because you call sendAction and it only shows for the action in the parent controller/component.

- You cannot bind the selectedItems. In our App we have for every table an component e.g. 'company-table' and there I access the models-table there. Then in another route, I use {{company-table}}. Now I cant access the selectedItems by e.g. {{company-table selectedItems=selectedCompanies}}.

**Comment by bgantzler** [comment]
@BennyAlex Pull request https://github.com/onechiporenko/ember-models-table/pull/278 will make sendDataAction a real closure action.  May help with your point one
