### ISSUE TITLE
How to search and sort on cell template

### ISSUE THREAD

**Issue by nag9329** [onechiporenko/ember-models-table#205]
Hi,

I know that ember models table has the search and sort functionality if only the cell contains data from the model property. But, what I'm actually looking is search and sort for a cell's data which is filled from a template. 

Currently, the sorting functionality is not present for these cells and also search does not work though I see data in the table. This is especially creating confusion for the end user since the data is present in the table but does not show up when I search.

Please let me know if you need any further explanation needed about the issue. Request you to help me if I'm missing anything to make them work.

Thanks,
Nagarjuna

**Comment by onechiporenko** [comment]
Hi, @nag9329. Currently sorting and filtering by "cell.innerText" is not possible. I don't think it may be possible.
Example:
Table with 1000 rows. Only 10 are shown. Table should render **all** rows to sort by "cell.innerText". It will cause performance issues.

**Comment by nag9329** [comment]
got it. I'm closing this issue
