### ISSUE TITLE
I need help - How to work with "cell component" to make input

### ISSUE THREAD

**Issue by optikalefx** [onechiporenko/ember-models-table#206]
Hey,

I'm trying to get a cell component to work that would let me have cell inputs. I was able to get input fields, and have onChange fire. But I can't seem to get an action up out of the component so controller can implement a save action. I tried passing a function (or any custom data) into the `columns` object. But those don't seem to be accessible. Not sure what else to try here.

Thanks!

**Comment by onechiporenko** [comment]
@optikalefx, I think route-actions addon may help you (https://github.com/DockYard/ember-route-action-helper).

**Comment by optikalefx** [comment]
Great idea. Thanks!
