### ISSUE TITLE
how can I reset the checkbox items from route?

### ISSUE THREAD

**Issue by zardaloop** [onechiporenko/ember-models-table#207]
I have added multiselect function and I capture the selected items in the displayDataChangedAction function in the route. is there anyway that at point I can reset all the selected Items ? or in the otherword simulate toggleAllSelection function ?

**Comment by onechiporenko** [comment]
@zardaloop, did you check http://onechiporenko.github.io/ember-models-table/#/examples/select-rows-with-checkboxes example? `Toggle all` inside `models-table`-component is possible. But toggle on outside component is not possible (at least I don't expect it may be done currently)
