### ISSUE TITLE
Integration with ember data and relationships

### ISSUE THREAD

**Issue by andessen** [onechiporenko/ember-models-table#21]
Do you have any code examples of this working with ember data models and asynchronous relationships?

**Comment by onechiporenko** [comment]
Hi, @andessen.
No, I don't have examples with ember-data usage. But I don't see any potential problems with it. You may set `columns` like:
```javascript
columns: [
      {
        propertyName: 'id',
        title: 'ID'
      },
      {
        propertyName: 'obj.firstName',
        title: 'First Name'
      },
      {
        propertyName: 'obj.lastName',
        title: 'Last Name'
      }
    ]
```
Here `propertyName` is set as nested value.

**Comment by andessen** [comment]
I confirmed that this worked. Thanks. Unfortunately I noticed there is some kind of stickiness with the sorts. I'll look to see if that's addressed somehow.
