### ISSUE TITLE
Change models-select pageSizeOptions from select to custom HTML?

### ISSUE THREAD

**Issue by noahgelman** [onechiporenko/ember-models-table#212]
I have the hard to style UI components of my site (checkboxes, radios, selects) as custom HTML. I would like the models-select that lists pageSizeOptions as custom HTML.

I've put my html in the components/models-table/component-footer file. Is there an action I can attach to the HTML that on click will update the table pageSizeOptions?

I can make the dropdown elements in my fake select box buttons if that conforms better to your code which grabs the .val() of the element I believe.

**Comment by onechiporenko** [comment]
@noahgelman, you should change `pageSize`. You may pass it to your custom component (as it done in the `app/templates/components/models-table/page-size.hbs`).

**Comment by jfbaquerocelis** [comment]
Hi @onechiporenko, I want to know... How can I change the `pageSizeOptions` property?

So, I generate a component `ember g component table-select`:

`components/table-select.js`
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  pageSize : 10,
  pageSizeOptions : [10, 25, 50, 100]
});
```

`templates/components/table-select.hbs`
```handlebars
<div class="col-md-2 col-sm-2 col-xs-2">
  <div class="pull-right">
    {{models-select
      options=pageSizeOptions
      value=pageSize
      class=(concat classes.input " changePageSize")
    }}
  </div>
</div>
```

But, I see the component doesn't change. Should I do it otherwise?

Thanks :+1: :smiley:

**Comment by mydea** [comment]
You can set this via pageSizeValues:

```hbs
{{models-select pageSizeValues=pageSizeOptions}}
```

**Comment by jfbaquerocelis** [comment]
Hi @mydea. just now I tried but it doesn't work. I've read a bit about the code, the `pageSizeOptions` property is a *Object* but my custom component doesn't let me to change this properties. I supose this isn't possible.

For example, when I print off the properties these show their default values defined on `ember-models-table/addon/components/models-table.js` and I cannot changed it.

`components/table-select.js`
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  willRender() {
    this._super(...arguments);

    this.set(this, 'pageSize', 50);
    this.set(this, 'pageSizeOptions', [
      { label : 10, value : 10 },
      { label : 50, value : 50 },
      { label : 100, value : 100 },
      { label : 1000, value : 1000 },
    ]);
  }
});
```
`templates/components/table-select.hbs`
```handlebars
<p>The pageSize value is: {{pageSize}}</p>
{{#each pageSizeOptions as |option|}}
  <span> {{option.value}} </span>
{{/each}}
```
output:
```
The pageSize value is: 10
10 25 50
```

**Comment by mydea** [comment]
I'm a bit confused. I think you are overthinking this. You just need to set "pageSizeValues" to an array of numbers. There is no object involved here. So basically:

```js
// components/my-table/component.js
import Ember from 'ember';
export default Ember.Component.extend({
  initialPageSize: 100,
  myPageSizes: Ember.computed(function() {
    return [10, 50, 100, 1000];
  })
});
```

```hbs
{{! components/my-table/template.hbs }}
{{models-table
  pageSize=initialPageSize
  pageSizeValues=myPageSizes
}}
```

**Comment by jfbaquerocelis** [comment]
Oh man! It works! Thanks for you explain me :+1:
