### ISSUE TITLE
Table css not working with ember-bootstrap 4

### ISSUE THREAD

**Issue by PankajWorks** [onechiporenko/ember-models-table#215]
Hi @onechiporenko ,

Need one help here.
I have ember-bootstrap with version 4 installed. When i used ember-models table i found that columns drop down is not working.

Any ideas will be helpful.
![image](https://cloud.githubusercontent.com/assets/12717111/25913087/2753349c-35d7-11e7-996f-76e3fa0aec4c.png)

{{models-table
        data = result
        columns = resultColumns
 }}

**Comment by onechiporenko** [comment]
Hi, @PankajWorks. BS4 requires some code changes to be done - CSS-classes migration etc.
Some of them may be changed via `customClasses` and some templates should be changed too (I didn't check which of them)

**Comment by dipeshpp** [comment]
I have ember-bootstrap@1.0.0-alpha.12 (which I believe uses bootstrap 3 by default) but the drop-down is still not working. Any ideas?

**Comment by onechiporenko** [comment]
@dipeshpp, please check conversation after this comment https://github.com/onechiporenko/ember-models-table/issues/188#issuecomment-286519464
