### ISSUE TITLE
Link to route, click row

### ISSUE THREAD

**Issue by snaketoo** [onechiporenko/ember-models-table#217]
How to add route action for a row click event. Click on row -> route to other page

**Comment by onechiporenko** [comment]
Hi, @snaketoo. Sorry for late response.
You should extend `models-table` component and override action `clickOnRow`. You may add some extra behavior like transition to route there.

**Comment by MLeganes** [comment]
Thank you for the clue. I am working in this topic and I can not get the idea how to extend the component. Where can i find more information about how to do it?
I am new with ember.
Thank you in advance!!
