### ISSUE TITLE
server tables not working.

### ISSUE THREAD

**Issue by GeminPatel** [onechiporenko/ember-models-table#218]
There is not action performed when I can the pagination size. There are also no pagination buttons present. When I add pagination with numbers: It only shows 1 button with 1 in it. Clicking does nothing. There is just the first time hit on server and then nothing. Search also does nothing. The 'models-table' works perfectly fine.

**Comment by onechiporenko** [comment]
Hi, @GeminPatel. Without demo and logs I can't help you, sorry.

**Comment by dipeshpp** [comment]
@onechiporenko Does this table support server-side filtering, pagination, and sorting? I'm not able to follow the my-server-table.js example. Is there a hook that is called when the user enters a string in any of the filter boxes for each column or when the user switches to a new page?

**Comment by onechiporenko** [comment]
@dipeshpp, please check https://github.com/onechiporenko/ember-models-table/pull/62#issue-137738014
