### ISSUE TITLE
Programmatically hiding columns

### ISSUE THREAD

**Issue by Caltor** [onechiporenko/ember-models-table#226]
What is the recommended way of programmatically hiding/showing columns? At the moment I am using `cols[index].isHidden = true/false;` however this stops the Columns > Restore Defaults option from working, as this routine seems to use the `isHidden` property. Is there a better way of doing this?

**Comment by onechiporenko** [comment]
@Caltor, do you try to show/hide column outside a component?

**Comment by Caltor** [comment]
@onechiporenko Yes I'm doing it the route (index.js) `setupController` function. Does it have to be inside a component?

**Comment by okachynskyy** [comment]
I have the same question.
For example, I need a hide some columns on window resize event, and I can't simply remove item from columns array, because it cause a fetching data from server again (I use a server table), and it also will hide this columns from dropdown. But I need this columns to be visible in dropdown menu.

**Comment by Caltor** [comment]
Here is what I'm doing at the moment:
// template
{{models-table
    ...
    columns=applicatorColumns
    sendColumnsVisibilityChangedAction=true
    columnsVisibilityChangedAction='saveColumns'
    ....
}}

// controller
saveColumns(cols) {
    if (typeof(Storage) !== 'undefined') {
        localStorage.applicatorColumns = JSON.stringify(cols);
     }
}

// route
setupController: function(controller, model) {
    this._super(controller, model); // Call the parent class code to setup the controller
    
    // Check localStorage is supported by this browser
    if (typeof(Storage) !== 'undefined' && localStorage.applicatorColumns !== undefined) {

        // Restore the columns settings from browser localStorage
        let cols = controller.get('applicatorColumns');                
        let columnsVisibility = JSON.parse(localStorage.applicatorColumns);

        columnsVisibility.forEach(function(element) {
            let myCol = cols.find(x => x.propertyName === element.propertyName);
            if (myCol) {
                myCol.isHidden = element.isHidden;
            }
        }, this);
    }
}

**Comment by onechiporenko** [comment]
@Caltor, @okachynskyy, I think possible solution is:

```handlebars
{{models-table 
  data=model 
  columns=columns 
  columnsAreUpdateable=true 
  columnFieldsToCheckUpdate=columnFieldsToCheckUpdate}}
```

```javascript
// controller
Ember.Controller.extend({
  columns: [/* ... */],
  columnFieldsToCheckUpdate: ['isHidden']
});
```

**Comment by onechiporenko** [comment]
@Caltor, how does you `columns` look like?

**Comment by Caltor** [comment]
@onechiporenko 
Here is my `columns` definition from controller (index.js).

```
    applicatorColumns: [
        {
            "propertyName": 'id',
            "title": 'ID',
            "isHidden": true
        },
        {
            "propertyName": 'item.itemCode',
            "title": 'Item Code',
            "isHidden": false,
            "defaultShown": true
        },
        {
            "propertyName": 'applicator.familyId',
            "title": 'Family ID',
            "isHidden": true
        },
        {
            "propertyName": 'familyCode',
            "title": 'Family',
            "isHidden": false,
            "filterWithSelect": true,
            "sortFilterOptions": true
        },
        {
            "propertyName": 'applicator.applicatorTypeId',
            "title": 'Type ID',
            "isHidden": true
        },
        {
            "propertyName": 'typeName',
            "title": 'Type',
            "isHidden": false,
            "filterWithSelect": true,
            "sortFilterOptions": true
        },
        {
            "propertyName": 'applicator.composition',
            "title": 'Composition',
            "isHidden": true
        },
        {
            "propertyName": 'applicator.patternId',
            "title": 'Pattern ID',
            "isHidden": true
        },
        {
            "propertyName": 'patternName',
            "title": 'Pattern',
            "isHidden": false,
            "filterWithSelect": true,
            "sortFilterOptions": true
        },
        {
            "propertyName": 'applicator.gsm',
            "title": 'Weight (gsm)',
            "isHidden": true
        },
        {
            "propertyName": 'item.width',
            "title": 'Width (mm)',
            "isHidden": true
        },
        {
            "propertyName": 'item.supplierAccount',
            "title": 'Supplier',
            "isHidden": true
        },
        {
            "propertyName": 'item.supplierStockCode',
            "title": 'Supplier Ref',
            "isHidden": true
        },        
        {
            "propertyName": 'applicator.purpose',
            "title": 'Purpose',
            "isHidden": true
        },
        {
            "propertyName": 'item.country',
            "title": 'Country of Origin',
            "isHidden": true
        },
        {
            "propertyName": 'applicator.numberOfLanes',
            "title": 'Lanes',
            "isHidden": true
        },
        {
            "propertyName": 'item.statusId',
            "title": 'Status ID',
            "isHidden": true
        },
        {
            "propertyName": 'statusDesc',
            "title": 'Status',
            "isHidden": false,
            "filterWithSelect": true,
            "sortFilterOptions": true
        },
        {
            "title": '',
            "template": 'applicators/table-actions',
            "mayBeHidden": false
        }
    ]
```

**Comment by okachynskyy** [comment]
@onechiporenko 
If I add 
```
columnsAreUpdateable=true 
columnFieldsToCheckUpdate=columnFieldsToCheckUpdate}}
```
table fetches data from server every time when I change my columns array.

**Comment by Caltor** [comment]
@onechiporenko Thanks for the input. 
> Well, IDK why my solution doesn't work for you 
I kind of meant I don't know what problem you are trying to solve for me. The problem with saving columns, restoring column defaults or making column selections sticky? If you can just state a definitive way to programmatically hide/show columns without breaking the Restore Defaults then I can take it from there.

I've moved the columns to `getApplicatorColumns()` function. How do I tell the template to get the column definition from this function though? Obviously 
```
{{models-table
  columns=getApplicatorColumns
}}
```
won't work.

**Comment by lincolnpahwa** [comment]
@Caltor you can create a computed property

`columns: computed(['dependentKey',] function() {
  return [ /* ... */ ] // or in your case getApplicatorColumns()
})`
