### ISSUE TITLE
Make column selection "sticky"

### ISSUE THREAD

**Issue by Caltor** [onechiporenko/ember-models-table#227]
Please could you add a feature to make the Column selection "sticky" so that it survives page refreshes etc. The actual settings could be saved into browser local storage. Ideally have an option `stickyColumns` that can be passed to the component that allows the user to select Session or Forever or No (default for backwards compatibility). Many thanks and please keep up the good work.

**Comment by saygun** [comment]
@onechiporenko 
Instead of local storage could it be `query-params`? isn't it better?

I might offer help to implement this feature if needed ofc.

**Comment by Caltor** [comment]
How about allowing an object to be passed in that can store and retrieve
the column settings. The developer could then implement a storage mechanism
of their choice. Could be localStorage, SQL, etc whatever.

**Comment by onechiporenko** [comment]
Sorry for such late response.
Every column has property called `isHidden`. You may set its value on columns init. Presaving columns settings is a task for external context and not for table itself.

**Comment by Caltor** [comment]
The problem is that once `isHidden` has been manipulated then the `Restore Defaults` option on the columns dropdown no longer works and there isn't a property to choose what action it fires so an external context cannot achieve this.

**Comment by mydea** [comment]
You could use columnSets to build a custom restore defaults button.

See: https://github.com/onechiporenko/ember-models-table/pull/213

Basically, you could do:

```js
// component
customColumnSets: computed(function() {
  return [
     {
       label: "Restore Defaults (CUSTOM)",
       showColumns(allProcessedColumns) {
          // Do something custom here
        }
    }
  ];
})
```

```hbs
{{! template }}
{{models-table columnSets=customColumnSets}}
```

@onechiporenko it seems that this has somehow dropped from the Docs - it was there at some point I think?

**Comment by onechiporenko** [comment]
@mydea. It is in the docs - https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/templates/index.hbs#L180
I missed update github-demo....

**Comment by mydea** [comment]
Ah, that makes sense :)
