### ISSUE TITLE
Always sorted

### ISSUE THREAD

**Issue by olehkhomyk** [onechiporenko/ember-models-table#232]
How to do column always sorted, (sort up or sort down)
need to do only two states for the column.
Please help, I need that so much.
Thank you.

**Comment by olehkhomyk** [comment]
Find how tot do THET)

**Comment by pmkhoa** [comment]
Can you share how you did this? Thanks.

**Comment by olehkhomyk** [comment]
Rewrite this method 
_singleColumnSorting(column, sortedBy, newSorting) {
    const sort = "none" === newSorting ? 'asc' : newSorting;
    const sortProperties = [`${sortedBy}:${sort}`];

    get(this, 'processedColumns').setEach('sorting', 'none');
    set(column, 'sorting', sort);
    set(this, 'sortProperties', sortProperties);
  },
