### ISSUE TITLE
Ember-Models-Table not rendering data in Ember Bootstrap Modals

### ISSUE THREAD

**Issue by mwitkows** [onechiporenko/ember-models-table#234]
I am using a combination of ember models-table, and ember bootstrap modals. The table renders, but never shows data when inside a modal dialog. Is there a workaround for this?

**Comment by onechiporenko** [comment]
Hello, @mwitkows. I need a demo to invastigate a problem.

**Comment by mwitkows** [comment]
Please disregard this issue.
