### ISSUE TITLE
Addon is unusable with Ember 2.15

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#239]
- [x] All internal partials should be replaced with components
 - [x] Refactor `models-table` to use contextual components
 - [x] Refactor existing tests (use `ember-cli-mirage` and `ember-cli-page-object`)
 - [x] Add MORE tests (and for `server-paginated` table too)
 - [x] Change components nesting
 - [x] Allow to send actions from anywhere in the component to the outer context
 - [x] Add yuidocs
  - [x] Themes
 - [x] Check performance
- [x] Create separated demos for v1.13 and v2.0

**Comment by steverhoades** [comment]
@onechiporenko I just attempted to upgrade to 2.15 and see why this issue was created.

Do you know what in 2.15 broke this add-on?  I'd like to help if possible but at the moment there isn't a clear error indicating where this add-on is failing.

What I am seeing is empty rows in the table and an error being thrown on click.

```
ember-metal.js:3988 TypeError: Cannot read property 'get' of undefined
    at Class.onRowSelect (route.js:171)
    at Router$1.triggerEvent (router.js:1017)
    at trigger (router.js:111)
    at Router$1.trigger (router.js:1699)
    at Class.send (router.js:327)
    at Class.send (action_handler.js:42)
    at Class.triggerAction (target_action_support.js:89)
    at Class.sendAction (action_support.js:115)
    at Class.clickOnRow (component.js:44)
    at Class.send (action_support.js:129)
```

**Comment by onechiporenko** [comment]
Hi, @steverhoades. Something become broken with partials on Ember-2.15. Since Ember core-devs recommended to not use partials and move to the contextual components I have to do this too. Branch v2.0 (https://github.com/onechiporenko/ember-models-table/tree/v2.0) contains new version of `ember-models-table`. It's not published yet, but i'm working on it.

**Comment by mydea** [comment]
I now it is still WIP, but may I recommend that you nest the components? I think that would make it easier to grasp & to override it.

E.g.:

components/models-table.js
components/models-table/select.js
components/models-table/footer.js
components/models-table/row.js
...

You can use these nested components normally in the template, e.g. `{{models-table/row}}`.

**Comment by onechiporenko** [comment]
@mydea, thanks. I think I'll do as you said. It's a good idea!
`2.0` is big major release with great changes, so fill free to propose/ask/recommend :)

**Comment by mydea** [comment]
Awesome! Is there a place for recommendations etc, or should I just put them here?
I would also be up to help out if there is anything you'd need help with - ember-models-table is an integral part of our products, so I'm happy to give back :)

**Comment by onechiporenko** [comment]
Yes, you may put it here.
> I would also be up to help out if there is anything you'd need help with
Thanks! For now I need a "fresh outlook" (IDK, if it's a correct translation from "свежий взгляд со стороны").
"Coding part" contains next items:
 - Refactor existing tests (use `ember-cli-mirage` and `ember-cli-page-object`)
 - Add MORE tests (and for `server-paginated` table too)
 - Change components nesting
 - Allow to send actions from anywhere in the component to the outer context
 - Check performance
 - Create separated demos for v1.13 and v2.0
 - ~Take over the world~

**Comment by onechiporenko** [comment]
>  ember-models-table is an integral part of our products, so I'm happy to give back :)
I'm really glad that `ember-models-table` is useful for your products :)

**Comment by Ramblurr** [comment]
The discussion here has left me a little confused. Glad to see 2.0 is coming along :-D

But, is version 1.x going to be updated to support Ember >= 2.15?

**Comment by onechiporenko** [comment]
@Ramblurr, upgrading 1.x means that some partials (IDK all partials or only a part of them) should be combined into one template.
As for now, it's not a problem with addon itself. Yes, I've used not best practice with partials instead of components, but partials are supported currently and are not deprecated officially. Some error happens with Ember (or Glimmer or any other lib). I believe that bug emberjs/ember.js#15621 will be fixed and v1.x will continue work correctly.

**Comment by Ramblurr** [comment]
Good to hear! I didn't realize this was caused by a *bug* in Ember rather than a deprecation/change. Thanks @onechiporenko

**Comment by onechiporenko** [comment]
v2.0.0-alpha.1 is released. It's a pre-release for anyone who wants to test new design and help to improve it.

**Comment by DennisNygren** [comment]
Hey, first of all thanks for a great addon! When using Ember 2.15 with `v2.0.0-alpha.1` branch, the column `template` functionality is not working (the cells are now blank). `propertyName` cells are still showing up correctly.

Keep up the good work!

**Comment by onechiporenko** [comment]
@DennisNygren, main idea for version 2.* is replace templates (partials) with contextual and "normal" components. So, upgrade to version 2.* requires refactoring. Some migration docs will be prepared later. For now - just replace partials with components.

**Comment by onechiporenko** [comment]
`v2.0.0-beta.1` is released.

**Comment by DennisNygren** [comment]
@onechiporenko Ok thanks for your quick reply!

**Comment by arnebit** [comment]
Great work so far!

Is there a particular reason not to pass `table=this` o a [`componentForFilterCell`](componentForFilterCell) anymore? 

That used to be the case before and I relied on it (on accessing `processedColumns` in particular) to implement [filter options dependent on another filter (subcategory <- main category)](https://github.com/onechiporenko/ember-models-table/issues/107).

**Comment by onechiporenko** [comment]
@arnebit, `componentForFilterCell` receives several properties (see https://github.com/onechiporenko/ember-models-table/blob/v2.0/addon/templates/components/models-table/row-filtering.hbs#L16). Let me know if something more is needed.

Passing `table=this` is a bad practice that I shouldn't use before (but I did :cry:)

**Comment by onechiporenko** [comment]
`v2.0.0-beta.2` is released.

**Comment by cmonzon44** [comment]
I update to 2.0.0-beta.2 and common table throw me an error on console in firefox, 
`get(...) is undefined
_setupColumns@http://localhost:4200/assets/vendor.js:69428:24
exports.default<.setup<@http://localhost:4200/assets/vendor.js:69320:7`  on ember-metal:3988

Here my controller,
 `import Ember from 'ember';
export default Ember.Controller.extend({
  columns: [{ propertyName: 'title', title: 'name' },
            { propertyName: 'artist', title: 'artis' },
            { propertyName: 'songCount', title: 'song' },
            ],
});`

and here my simple model,  `import DS from 'ember-data';
export default DS.Model.extend({
  title: DS.attr(),
    artist: DS.attr(),
    songCount: DS.attr()    
});
`

Before update version of ember and more components it was worked.

my actual versions:
`
DEBUG: Ember              : 2.15.0  index.js:158
DEBUG: Ember Data         : 2.15.0  index.js:158
DEBUG: jQuery             : 3.2.1  index.js:158
DEBUG: Ember Models Table : 2.0.0-beta.2  index.js:158
DEBUG: -------------------------------`

Have i an error?

**Comment by arnebit** [comment]
@onechiporenko Why is passing `table=this` bad? Because it would give the user...flexibility? ;-)

The aforementioned `processedColumns` aside, looking for `table.` in my project, I find I am also accessing/using 
* the `sort` action and
* `filteredContent`,
to implement a "toggle flag on all visible items" (to solve a problem similar to #214, it seems).

**Comment by onechiporenko** [comment]
Check new demo page for v.2 http://onechiporenko.github.io/ember-models-table/v.2/

**Comment by onechiporenko** [comment]
`v2.0.0-beta.3` is released.

**Comment by SakuDivya** [comment]
I am using ember-model-table 2.0beta after the issue came up with "partials" in ember 2.15.I want to know if  there is an option to customize the pagination in 2.0  such as "componentFooterTemplate" in 1.0? Pls help as it affects my app in production.

**Comment by onechiporenko** [comment]
@SakuDivya, sure. You may override [models-table/footer](http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTableFooter.html) or use block content like:

```handlebars
{{#models-table data=data columns=columns as |mt|}}
  {{#mt.footer as |footer|}}
    {{! custom markup here }}
  {{/mt.footer}}
{{/models-table}}
```

**Comment by onechiporenko** [comment]
Short diff-manual for migration from 1.x to 2.x is [here](http://kronus.me/2017/09/upgrade-ember-models-table-to-version-2/)

**Comment by SakuDivya** [comment]
Thanks for the quick reply. But if want pagination functionalities and only need to change the UI lookup of page numbers,what needs to be done.Do i have to write a separate component and write all functionalities instead of       {{footer.pagination-numeric}} ?

**Comment by onechiporenko** [comment]
@SakuDivya, pls create a separated issue. This one is like a "news-board" for 2.x.

**Comment by SakuDivya** [comment]
I have created.Pls take a look Thank u...

**Comment by onechiporenko** [comment]
`v2.0.0-beta.4` is released. Check small theming guide [en](http://kronus.me/2017/10/theming-ember-models-table-2-x/) / [ru](http://kronus.me/2017/10/%D1%82%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-ember-models-table-2-x/)

**Comment by steverhoades** [comment]
Looking really good, thanks for all the hard work @onechiporenko !

**Comment by onechiporenko** [comment]
`v2.0.0` is released.
