### ISSUE TITLE
Error just installing the component with Ember 2.1.0

### ISSUE THREAD

**Issue by jasalguero** [onechiporenko/ember-models-table#25]
I get this error, just by doing the installation:

Uncaught TypeError: Cannot read property 'reopen' of undefined
initialize                        @ ember-legacy-controllers.js:15
(anonymous function)  @ ember.debug.js:4197
(anonymous function)  @ ember.debug.js:4221
visit                              @ ember.debug.js:2257
DAG.topsort                 @ ember.debug.js:2368
_emberRuntimeSystemNamespace.default.extend._runInitializer @bmac ember.debug.js:4220
_emberRuntimeSystemNamespace.default.extend.runInitializers @ ember.debug.js:4186
_emberRuntimeSystemNamespace.default.extend.boot @ ember.debug.js:4095
_emberRuntimeSystemNamespace.default.extend.domReady @ ember.debug.js:4081
Backburner.run @ ember.debug.js:294
Backburner.join @ ember.debug.js:318
run.join @ ember.debug.js:19703
(anonymous function) @ ember.debug.js:19766
fire @ jquery.js:3099
self.fireWith @ jquery.js:3211
jQuery.extend.ready @ jquery.js:3417
completed @ jquery.js:3433

What is the add compatibility requirements?

**Comment by bmac** [comment]
Looks like this issue is coming from [ember-legacy-controllers](https://github.com/emberjs/ember-legacy-controllers/issues/8) and not `ember-models-table` the linked issue suggests installing `ember-legacy-views` to resolve the issue.

**Comment by jasalguero** [comment]
I would like to avoid that, I don't have ember-legacy-controllers dependency, that one is coming from ember-models-table, so ideally that's where the dependency should be added to not mix concerns. Would that be possible?

**Comment by onechiporenko** [comment]
@jasalguero, thanks for the report.
I've bumped version 1.3.6, where those dependencies are removed. Please, try to use it.

**Comment by jasalguero** [comment]
Thanks a lot!
