### ISSUE TITLE
Is column.template available in v2?

### ISSUE THREAD

**Issue by slavikdev** [onechiporenko/ember-models-table#252]
Hi.
I’m building custom component on top of yours. Thank you very much for your work.
The documentation and demo suggest there’s `column.template` property which allows to specify custom template for a column. I tried to use it with no luck and only when I saw package content I understood that such property isn’t there. Apparently the master branch is for older version which has different `row.hbs`.
Please clarify whether my assumptions are correct.

**Comment by onechiporenko** [comment]
Hi, @slavikdev. 
`template` is available in the 1.x versions. Ember 2.15 has a bug with partials (check pls discussion in the https://github.com/onechiporenko/ember-models-table/issues/239). I've started work on v2.x where `template` is *removed* from columns. So, for version 2.x only custom components are available (they are available in the v1.x too).
Work on 2.x is almost done (beta.2 is going to be released shortly).

**Comment by slavikdev** [comment]
Thank you very much!

**Comment by cmonzon44** [comment]
hello, an example to explain to do this custom template?

**Comment by onechiporenko** [comment]
@cmonzon44, check pls addon dummy-app. You will find examples for custom components for table cells. And one more time - **main difference between 1.x and 2.x is that 2.x version doesn't have custom templates and it only have custom components**
