### ISSUE TITLE
Add support for semantic ui 

### ISSUE THREAD

**Issue by geekyd** [onechiporenko/ember-models-table#253]
The module currently only supports `bootstrap` it would be great if we add support for other libraries like `semantic ui`.

**Comment by onechiporenko** [comment]
@geekyd, it supports any ui you need (in v2.x). Check please https://github.com/onechiporenko/ember-models-table/tree/v2.0/addon/themes
You may create your own theme extending default-theme. As for now I don't think that some markup changes are required.

**Comment by geekyd** [comment]
@onechiporenko Thanks for the update, It would be great if we could add support for semantic ui. I recently used ember-models-table with semantic ui & had to override it to add semantic ui support.

**Comment by onechiporenko** [comment]
Theming for `models-table` going to be improved (for now IDK how it's going to be), because even BS4 has different markup for dropdown (and may be some other components too) comparing to BS3. 
Ideas, PRs are welcome :)

**Comment by onechiporenko** [comment]
Well, some little demo for sematic ui is here - https://ember-twiddle.com/471b15cc58812b2a7da932f393677b37?fileTreeShown=false&numColumns=0&openFiles=templates.components.expand-all-toggle.hbs. I'm not familiar with SemanticUI but I hope this demo will help to create your own markup for it.

**Comment by onechiporenko** [comment]
Check new 2.0.0-beta.4 released
