### ISSUE TITLE
Custom pagination template in ember-models-table2.0

### ISSUE THREAD

**Issue by SakuDivya** [onechiporenko/ember-models-table#256]
I would like to have existing pagination functionalities and only need to change the UI lookup of page numbers,what needs to be done?Do i have to write a separate component and write all functionalities instead of {{footer.pagination-numeric}} and change in the ember-models-table itself ?

**Comment by onechiporenko** [comment]
@SakuDivya, you may override `templates/components/models-table/pagination-numeric` and put there any code you need. Check original template to get available variables

**Comment by SakuDivya** [comment]
Yeah I understand that.But if I do so, I can't have original ember-models-table in node modules and package.json to be used in other part of the project. Is that the only way?

**Comment by onechiporenko** [comment]
You may use block content:

```handlebars
{{#models-table data=data columns=columns as |mt|}}
  {{mt.global-filter}}
  {{mt.columns-dropdown}}
  {{mt.table}}
  {{#mt.footer as |footer|}}
    {{footer.summary}}
    {{footer.size-select}}
      {{#footer.pagination-numeric as |pn|}}
         {{! ... your code here }}
      {{/footer.pagination-numeric}}
    {{/if}}
  {{/mt.footer}}
{{/models-table}}
```

**Comment by SakuDivya** [comment]
Thank u very much...  pn.visiblePageNumbers, pn.themeInstance are working but actions like pn.gotoCustomPage is not working(had no action handler for: pn.gotoCustomPage).Any other way shd i call ?

**Comment by onechiporenko** [comment]
https://ember-twiddle.com/0af521b41a24bf24173b97accbbcb943?fileTreeShown=false&openFiles=templates.application.hbs%2C

**Comment by SakuDivya** [comment]
Thank u very much
