### ISSUE TITLE
Make table subcomponents customizable

### ISSUE THREAD

**Issue by CrushedPixel** [onechiporenko/ember-models-table#259]
It would be useful if we could specify the exact component used for a table row, cell, the table body etc, similar to how we can specify a column's component.

This way, we could easily extend the addon's components and tell the `models-table` to use them.

Example use case: Customize table row class based on content of the row - I'd like to apply the `state-error` class to a table row if the "state" column of the row contains an error.

This could work by replacing the `models-table/row` component in [`table-body.hbs`](https://github.com/onechiporenko/ember-models-table/blob/9ab0c68ca1930bed5d6ec951ff81c4affe374933/addon/templates/components/models-table/table-body.hbs#L64) with a component helper, like so:

```hbs
{{component rowComponent
    record=record
    visibleProcessedColumns=visibleProcessedColumns
    index=index
    [...]
}}
```

We'd then set the `rowComponent` parameter on the `models-table` component like so:
```hbs
{{models-table rowComponent="myCustomRow"}}
```

The parameter of course has to be reached down to `table-body`, which in turn could also be a variable component, to allow for maximum customization.

**Comment by onechiporenko** [comment]
@CrushedPixel, you may override `components/models-table/row.js` and `templates/components/models-table/row.hbs` in your application.

**Comment by CrushedPixel** [comment]
How would I do so, and then use it with models-table?

**Comment by onechiporenko** [comment]
Check pls this demo - https://ember-twiddle.com/471b15cc58812b2a7da932f393677b37?fileTreeShown=false&openFiles=components.expand-all-toggle.js%2Ctemplates.components.expand-all-toggle.hbs.
It shows how you may override `models-table/*` components for your own purposes.

**Comment by onechiporenko** [comment]
Theming is improved in the 2.0.0-beta.4. Check it pls

**Comment by zardaloop** [comment]
Hi @onechiporenko ,

After creating a new component. How do we then assign the new component? 
I am using version 1 and I want to override row.js, I have doen something like this : 

`
import Row from 'ember-models-table/components/models-table/row'
import { get, set, computed } from '@ember/object';

export default Row.extend({
  classNameBindings: ['rowSelectedClass', 'rowExpandedClass','inspection'],
  "bg-green": computed("record.Inspection", function(){
    return "hello";
  }),
  inspection: computed("record.Inspection", function(){

      if( get(this, 'record.Inspection') === "PASS"){

        return "bg-green";

      }else if(get(this, 'record.Inspection') === "FAIL"){

        return "bg-red";

      }else{
        return "";
      }
  })
});
`

how do I then assign it to models-table component to use the new component instead? I can't understand that from the example. 

Many thanks in advance.

**Comment by onechiporenko** [comment]
@zardaloop v1 doesn't use components, only v2 does. Please use v2.
