### ISSUE TITLE
2.0 - Data undefined in select-all-rows-checkbox example

### ISSUE THREAD

**Issue by steverhoades** [onechiporenko/ember-models-table#261]
https://github.com/onechiporenko/ember-models-table/blob/b5985f170ca52c32fefd9df3799d8c64f52eac50/tests/dummy/app/templates/components/select-all-rows-checkbox.hbs#L1

Just an FYI - the `checkbox` will never show as `themeInstance.select-all-rows` as the data property is undefined.

**Comment by onechiporenko** [comment]
Thanks, @steverhoades. Going to check/fix/file bug.
