### ISSUE TITLE
2.0 Feature Request - Ability to reset selected items

### ISSUE THREAD

**Issue by steverhoades** [onechiporenko/ember-models-table#264]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**
Currently you may pass in `preselectedItems` but you cannot reset any existing selected items.

* **[Feature] What is the motivation / use case for changing the behavior?**
I have a table that contains a multiple-select table and mass action buttons.  Once the mass actions have been performed there is no way to de-select the currently selected items.

* **Please tell us about your environment:**

- `ember-models-table` version: 2.0
- `ember` version: 2.15
- `ember-data` version: 2.14.2 
- `ember-cli` version:  2.15
- `node` version: 6
- `npm` or `yarn` version: npm 5+

It's probably not apparent to me at the moment, but whats the advantage of having `preselectedItems` and `_selectedItems` as private instead of just having `selectedItems` ?

**Comment by onechiporenko** [comment]
@steverhoades, thanks for submit this request and sorry for long delay. Dropping `_selectedItems` is useful scenario. I have to think about combining `_selectedItems` and `predefinedItems`. PR is always welcome :)

**Comment by onechiporenko** [comment]
Done in #290
