### ISSUE TITLE
Column filtering should be case insensitive

### ISSUE THREAD

**Issue by steverhoades** [onechiporenko/ember-models-table#265]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
When filtering a non-server paginated table, it is case sensitive. For instance, with a filter for  `american` will not show the cell `American`.

* **[Bug] What is the expected behavior?**
Expect results to be matched by case insensitivity.

Perhaps this was originally the desired behavior?  I'll provide a PR shortly for review.

**Comment by onechiporenko** [comment]
@steverhoades, I think you need this one [ModelsTable#filteringIgnoreCase](http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTable.html#property_filteringIgnoreCase)

**Comment by steverhoades** [comment]
@onechiporenko sorry - not sure how I missed that one.  Thanks for the quick reply.
