### ISSUE TITLE
`filterWithSelect`-box should show `filterPlaceholder` when there is no filterString

### ISSUE THREAD

**Issue by arnebit** [onechiporenko/ember-models-table#267]
* **I'm submitting a ...**

  - bug report (or, arguably, feature request)

* **What is the current behavior?**
If a column specification includes both
```
filterWithSelect: true,
filterPlaceholder: "(all of 'em)",
```
the default state of the filter box and topmost select option is still empty. The value of `filterPlaceholder` seems to be ignored.

* **[Bug] What is the expected behavior?**

If a `filterPlaceholder` is specified together with `filterWithSelect`, the value of the `filterPlaceholder` should be the default dropdown option (i.e. the one that selects all/resets the filter).

* **Please tell us about your environment:**

- `ember-models-table` version: 1.13.0
- `ember` version: 2.14.2
- `ember-data` version: 2.14.?
- `ember-cli` version:  2.14.?
- `node` version: 6.8.?
- `npm` version: 5.4.?

**Comment by onechiporenko** [comment]
Hi, @arnebit. Yes, `filterPlaceholder` should be applied to the `select`-filter.
