### ISSUE TITLE
2.0 Feature Request - dbclick & hover on rows

### ISSUE THREAD

**Issue by apanag** [onechiporenko/ember-models-table#268]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behaviour?**
Right now, there is an option to click on a row and select it. It would be convenient to support additional actions like double-click or hover on rows.

* **If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

* **[Bug] What is the expected behaviour?**
n/a

* **[Feature] What is the motivation/use case for changing the behaviour?**
n/a

* **[Support] What exactly you try to do?**
-- While hovering on table rows, I try to display additional information in other components.
-- Whereas with a double-click, I try to enable/disable row edit as well.

* **Please tell us about your environment:**
-- `ember-models-table` version:  2.0.0
-- `ember` version: 2.16
-- `ember-data` version: 2.16.2
-- `ember-cli` version:  2.16.2
-- `node` version: 6.11.3
--`npm` or `yarn` version: 5.5.1 / 1.2.1

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, gitter, etc)
n/a

**Comment by onechiporenko** [comment]
@apanag, thanks for submitting a request.
I can provide an action sending on double click or hover, but any other specific handlers should be done by you.

**Comment by apanag** [comment]
@onechiporenko Sounds great. Really appreciate it.

**Comment by onechiporenko** [comment]
Done in @2.1.0
