### ISSUE TITLE
CoIumns sort bug 

### ISSUE THREAD

**Issue by listepo** [onechiporenko/ember-models-table#27]
Version 1.3.6
![capture image](https://cloud.githubusercontent.com/assets/2510800/10904573/e378b180-821c-11e5-84eb-f483686d6f16.png)

**Comment by onechiporenko** [comment]
@listepo, what was the order of sorting?

**Comment by listepo** [comment]
@onechiporenko no difference, the main thing that was already the arrow. When you click on another column previous not then removed

**Comment by onechiporenko** [comment]
Actually, then won't.
Multi-columns sorting was done in https://github.com/onechiporenko/ember-models-table/issues/5

**Comment by listepo** [comment]
@onechiporenko how you can switch to the previous version? or is it impossible?

**Comment by onechiporenko** [comment]
Something like this:
```
npm uninstall ember-models-table --save
npm install ember-models-table@1.3.5 --save
```

**Comment by listepo** [comment]
@onechiporenko I thought it somehow be possible in 1.3.6

**Comment by onechiporenko** [comment]
Well, I'll think about possibility to turn on/off multi-columns sorting.

**Comment by listepo** [comment]
thanks
