### ISSUE TITLE
wrap text inside Some html tag

### ISSUE THREAD

**Issue by ankitmadhwani24** [onechiporenko/ember-models-table#273]
Hi 

I want to wrap the text that coming inside the <th> into some html tag like (span)

pls check the screen shot for same 
![untitled](https://user-images.githubusercontent.com/23015801/32376928-31a5ce70-c0cc-11e7-9c0a-3f080a1378b4.png)

**Comment by bgantzler** [comment]
This should be easy to do once the table cell component pull request is merged.

**Comment by cah-briangantzler** [comment]
Im sorry, this was in a TH not a TD. #274 would not solve this.

**Comment by onechiporenko** [comment]
@ankitmadhwani24, there are two ways to do this:
1. `componentForSortingCell` may be used for this (check docs).
2. Set `components.row-sorting-cell` to your custom component. It may extends original `components/models-table/row-sorting-cell`.
