### ISSUE TITLE
Sorting by computed properties?

### ISSUE THREAD

**Issue by planetexpress69** [onechiporenko/ember-models-table#28]
I HEREBY REVOKE MY STUPID QUESTION! Thanks for making such a nice table!

Hi Oleg,

I discovered that computed properties aren't sortable. Any way to enable that? Or is it possible to hint the column to sort a computed property by using a real one?

Kindest regards,
Martin

**Comment by onechiporenko** [comment]
@planetexpress69, columns is sortable if `propertyName` or `sortedBy` is provided in the column-config.

**Comment by planetexpress69** [comment]
Yes, meanwhile I managed to read the doc. Stupid me! Thank you, nevertheless.

**Comment by onechiporenko** [comment]
Sure, np.

**Comment by csprocket777** [comment]
How was this solved? I'm trying to change the sort direction of a column using a computed property and it's not responding.
