### ISSUE TITLE
Column filter for custom templates

### ISSUE THREAD

**Issue by mervinva** [onechiporenko/ember-models-table#282]
**I'm submitting a ...**
  - [x] support request

- `ember-models-table` version: 1.13.0
Hi,
How can I give a column filter for custom templates?

**Comment by cah-briangantzler** [comment]
Im not sure I understand the question.

Do you perhaps mean `componentForFilterCell` when defining a column http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Utils.ModelsTableColumn.html

**Comment by onechiporenko** [comment]
@mervinva, you may use `filterFunction` in the `column` (check http://onechiporenko.github.io/ember-models-table/v.1/ pls). Small example is in the tests - https://github.com/onechiporenko/ember-models-table/blob/v1.x/tests/integration/components/models-table-test.js#L727

**Comment by mervinva** [comment]
Thanks. I will check it.
