### ISSUE TITLE
Comment on Actions as closures

### ISSUE THREAD

**Issue by bgantzler** [onechiporenko/ember-models-table#284]
Sorry for opening an issue, but didn't know how to email you.

I saw the commits on the actions as closures and if you want to deprecate them, I would suggest putting the deprecation's in getter/setters of the values like below. This will throw the deprecation message at assignment and not wait til use and possibly give less messages as assign should happen less than use. Will also cover the send flag if they happen to set that and the action as a closure.

You can then remove the deprecation's from the use code.

```
sendDisplayChangedAction: computed({
  get() {
    return false;
  },
  set(k, v) {
    /* deprecate message for the sendDisplayChangedAction */
    return v;
  }
}),

displayChangedActionAction: computed({
  get() {
    return "displayChangedAction";
  },
  set(k, v) {
    if (typeof v !== 'function') {
      /* insert deprecate message */
    }
    return v;
  }
})
```

Also could you review and talk about PR https://github.com/onechiporenko/ember-models-table/pull/277 Have plans to enhance that once accepted to solve the issues of access to selected items.

Thanks

**Comment by onechiporenko** [comment]
Hi, @bgantzler. It's a good idea. Thanks!
