### ISSUE TITLE
Remove column from columns dropdown

### ISSUE THREAD

**Issue by mervinva** [onechiporenko/ember-models-table#285]
* **I'm submitting a ...**
  - [x] support request

* **Please tell us about your environment:**

- `ember-models-table` version: 1.13.0

Hai @onechiporenko ,
I don't want a column to visible in the columns dropdown . I tried adding `"mayBeHidden":true` , but it is not working.

**Comment by onechiporenko** [comment]
You should set `mayBeHidden` to `false`

**Comment by mervinva** [comment]
Thanks @onechiporenko .
