### ISSUE TITLE
Disable global filtering

### ISSUE THREAD

**Issue by mervinva** [onechiporenko/ember-models-table#286]
* **I'm submitting a ...**
  - [x] support request

* **Please tell us about your environment:**

- `ember-models-table` version: 1.13.0

Hai ,
How can I disable global filtering option in the table? Is there any option for that?

**Comment by onechiporenko** [comment]
http://onechiporenko.github.io/ember-models-table/v.1/
Prop `showGlobalFilter` set to `false` will hide global filter and user won't be able to use it
