### ISSUE TITLE
Sorting needs to be done by custom icon instead of whole column

### ISSUE THREAD

**Issue by vishalpareek** [onechiporenko/ember-models-table#294]
I need to use a default sort icon instead of the whole column to sort the table,is there any way to do it in existing design?

Also is it possible to have a sort icon for all the columns which are sortable.

**Comment by vishalpareek** [comment]
@onechiporenko Could you please comment on this,is this possible to have sort functionality available on a sort icon instead of whole table header.

**Comment by cah-briangantzler** [comment]
The easiest way to do this would be to create a new component and replace the row-sorting-cell component, you can create a new one named the same in the correct directory "ember g component  models-table/row-sorting-cell" or name it anything you want and [override the entry](https://github.com/onechiporenko/ember-models-table/blob/master/addon/themes/default.js#L51) in your own theme. If you look at the code for that component, it would be relatively easy to implement what you ask.
