### ISSUE TITLE
Toggle all selection is broken

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#295]
* **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**

"Toggle all selection" doesn't work

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Click "toggle-all selection".

* **[Bug] What is the expected behavior?**

Rows selection must be toggled.

- `ember-models-table` version:  2.3.0
- `ember` version: 2.18.
- `ember-data` version: 2.18 
- `ember-cli` version:  2.18
- `node` version: 8
- `npm` or `yarn` version: 5

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by beastmst** [comment]
still have bug with this?!  my example not working.. 

https://ember-twiddle.com/33a6d6f9139325301b9a35053db33f85?openFiles=routes.index.js%2Ctemplates.components.adk-location-select-all-rows.hbs
