### ISSUE TITLE
sorting by clicked component

### ISSUE THREAD

**Issue by beastmst** [onechiporenko/ember-models-table#296]
I used the checkbox to do some selection...
is it a way to put the clicked item at the beginning of the table?  once I click selected, it move the field to page 1..?

* **I'm submitting a ...**

  - [ ] bug report
  - [V] feature request
  - ~[V] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **[Bug] What is the expected behavior?**

* **[Feature] What is the motivation / use case for changing the behavior?**

* **[Support] What exactly you try to do?**

* **Please tell us about your environment:**

- `ember-models-table` version: 
- `ember` version: 
- `ember-data` version: 
- `ember-cli` version:  
- `node` version:
- `npm` or `yarn` version:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by onechiporenko** [comment]
@beastmst, you may `data` like sorted by some flag-field array. Then you should add click-handler for rows and toggle this flag for clicked rows. In this case, selected rows should appears on top
