### ISSUE TITLE
Make last row bold text

### ISSUE THREAD

**Issue by hsiasat** [onechiporenko/ember-models-table#297]
Hi Guys,

I have a table that will display amount of orders but I want to make last row (total) to be in bold. How do I do that with models-table?

Regards

**Comment by cah-briangantzler** [comment]
It appears the table-footer component does not supply anything on default. That would be preferable. Have to look into fixing that. Once done it would be an easy option

I explored using block syntax but the needed properties (visibleProcessedColumns and data were not yielded (need to fix that))

Last choice I see if writing a cell replacement component, using the index, and if the row is the last index, use a different class. Not the way I would suggest.

Let me see if I cant put in a couple pull requests.

**Comment by bgantzler** [comment]
https://github.com/onechiporenko/ember-models-table/pull/298 should help with at least using the block syntax, some work but doable. Once request is accepted can show more

**Comment by bgantzler** [comment]
So.... playing with the data, would you want the footer shown at the bottom no matter what page is currently being shown, or are you preferring that your total always be the last record on the last page, and that record somehow marked differently?

**Comment by hsiasat** [comment]
currently the total will show on the last row of the table since we don't have much data to show. when the time comes when pagination is needed that would be different requirement for us on how to show the total. but for now "total always be the last record on the last page".

**Comment by bgantzler** [comment]
For the time being I would extend the row component, wrote this quickly, didnt actually test it. hopefully its mostly correct

ember g component models-table/row  

That should create a new component that overrides the default one. The extend the default one as below.

```
import Row from 'ember-models-table/components/models-table/row'
import { get } from '@ember/object';

export default Row.extend({
  classNameBindings: ["totalRowClass"],

  totalRowClass: computed("record.isTotalRow", {
    get() {
      return get(this, 'record.isTotalRow') ? "yourtotalrowclass" : '';
    }
  })
});
```

On your object that is the total row, there has to be something that marks it as such, some property. In my example there is a property on the object called isTotalRow. 

This will place a class on the TR of the total row only. I would think that would be enough to get what you want. If for some reason you need to apply the class to individual cells, then I would extend models-table/cell instead.

When it comes to showing the data in pages, the total will be on the last page still marked. If you would then need it somewhere else, would depend on where that is.

**Comment by hsiasat** [comment]
thank you very much.

**Comment by hsiasat** [comment]
one last thing. this solution is only applicable for v2 right? will this work with v1.x?

**Comment by bgantzler** [comment]
Yes, 2.x

Never used 1.x, looking at the code though, you would have to copy the entire partial template row into your own. Then modify that. You would probably need to use ember-composable-helpers to determine last record. Not as pretty but maybe doable.

**Comment by zardaloop** [comment]
I know this ticket is closed but I would appreciate if you could please advise me on this.

I am trying to follow this approach but I can't override anything. 


I have already created a new component called form-table by extending models-table like below: 

```
import modelsTableComponent from 'ember-models-table/components/models-table';
import InboundActions from 'ember-component-inbound-actions/inbound-actions';
import moment from 'moment';
import Ember from 'ember';

const { inject: { service } } = Ember;

export default modelsTableComponent.extend(InboundActions, { ...
```

So can I still override the row component the same way as recommended here or I need a different approach? 

Many thanks.
