### ISSUE TITLE
add a new record or create a model after load data ?

### ISSUE THREAD

**Issue by GrupossiDT** [onechiporenko/ember-models-table#300]
* **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **[Feature] What is the motivation / use case for changing the behavior?**

i`m triing to add a new button on top of the table and add a new record but im stuck , i can`t push a object into the  data after load all the info of my back-end how i do that?  you think add this functionaliti to your addon?  if posible create a model and load this data from your addon?
I appreciate your collaboration tnx.

* **Please tell us about your environment:**

- `ember-models-table` version: 2.0
- `ember` version:  3.0
- `ember-data` version: 2.18.0
- `ember-cli` version:  2.18.2
- `node` version:8.9.4
- `npm` or `yarn` version: 1.3.2

**Comment by onechiporenko** [comment]
@GrupossiDT, this can't be done in the `ember-models-table`-scope. `data` passed to the component may be received from any place (e.g. from `store` or be just a simple array).

So, you should add a new record to the `data` used in the table:

```js
const newRecord = get(this, 'store').createRecord('some-type', {/* ... */});
get(this, 'tableData').pushObject(newRecord);
```

`tableData` is bound to the `models-table` like:

```hbs
{{models-table data=tableData}}
```

`newRecord` will automatically appears in the table.

**Comment by GrupossiDT** [comment]
@onechiporenko  that's right we just call our api and after save de data to DB push the object and the table automatically show the record. 

you have in maind add this new fwature and create a model from the data ?
