### ISSUE TITLE
Add a "summary"-row for grouped rows

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#303]
* **I'm submitting a ...**

  - [x] feature request

* **[Feature] What is the motivation / use case for changing the behavior?**

Table-footer shows summary-info for all rows, however there is no way to show summary for grouped rows. `groupingRowComponent` is added. Usage example:

```hbs
{{models-table 
  data=model
  columns=columns
  multipleSelect=true
  useDataGrouping=true
  dataGroupProperties=dataGroupProperties
  currentGroupingPropertyName=currentGroupingPropertyName
  displayGroupedValueAs=displayGroupedValueAs
  pageSize=25

  groupingRowComponent=(component "group-summary-row")
}}
```

```js
// app/components/group-summary-row.js
import layout from '../templates/components/group-summary-row';
import GroupSummaryRow from './models-table/group-summary-row';

export default GroupSummaryRow.extend({
  layout
});
```

```hbs
{{! app/templates/components/group-summary-row.hbs }}
{{#each visibleProcessedColumns as |column index|}}
  <td>
    Column #{{index}}.
    <span class="expanded">{{expandedGroupedItems.length}}</span>
    <span class="visible">{{visibleGroupedItems.length}}</span>
    <span class="selected">{{selectedGroupedItems.length}}</span>
  </td>
{{/each}}
```

**Comment by cah-briangantzler** [comment]
Shouldn't that have have been a property
```
useGroupSummaryRow=true
```
and then the component placed in theme like all other components?

Could also provide a fallback as 
```
components=(hash groupSummaryRow=(component ....))
```
Like column components to allow for override IF you needed to pass additional properties or actions

**Comment by cah-briangantzler** [comment]
Since we are talking about the summary row. Its currently rendered as the last row of the table, meaning you have to go to the last page to see it. For the table summary row only, would be nice if it could be rendered just above the footer (where page is displayed) so that it would be present always. 

Not sure how this would work with paginated though. If I skip from page one to page 20 (last page) does the table summary row show the correct data? Only 2 pages were loaded.

**Comment by onechiporenko** [comment]
@cah-briangantzler, `groupingRowComponent` will be used if it's provided, so there is no need to use additional flag. Table summary is shown in the table footer and not as a last row in the last page (see demo [Inline edit and columns summary](https://ember-twiddle.com/99e1630b806bd4bd6edb5682429079a8?fileTreeShown=false&numColumns=0)). You can pass any additional data or action handlers in `groupingRowComponent=(component "group-summary-row")`.

**Comment by cah-briangantzler** [comment]
Hmmm, I thought I had tried that somewhere and the row was shown as last...Sorry.

While I agree that as implemented theres no need for the additional flag. Was more asking for consistency should this component follow the same standard as other components and it be placed in the theme. (Placing it in the theme is what is requiring the additional property)

**Comment by onechiporenko** [comment]
Themes contain some "internal" components. So, `expandedRowComponent` and `groupingRowComponent` are not placed there. And new `groupingRowComponent` is also not added to theme and is placed in the `models-table`
