### ISSUE TITLE
Keep semantic versioning standards

### ISSUE THREAD

**Issue by Martodox** [onechiporenko/ember-models-table#306]
Hey,
This is not an issue per say, but a request for the maintainers.
Since this is an ember addon with 5,312 downloads in the last month, please, use semantic versioning as it is supposed to be used.

v.2.4.0 should have been released as v3.0.0 since it brought "[BREAKING]" changes, which actually broke some of our builds :D

👍 +1 for keeping the release log nice and clean.

If you need someone to keep the semantic versioning in check, let me know - I am more than happy to help out :)

**Comment by onechiporenko** [comment]
Hi, @Martodox. Thanks for your feedback. I agree that semantic versioning is important. However in this case I might use `[CLEANUP]` instead of `[BREAKING]`. I've removed items that are marked as "deprecated" for about 3 months.
Anyway, I got your suggestion and appreciate it.
