### ISSUE TITLE
[Support] columns-dropdown hide & show

### ISSUE THREAD

**Issue by Biggsz** [onechiporenko/ember-models-table#307]
I'm trying to make a custom theme for ember-models-table but I can't find how to bind an action to the colums-dropdown button to show & hide the columns-dropdown.

**Comment by lincolnpahwa** [comment]
I would imagine it can be achieved by toggling `showColumnsDropdown` property using a flag from the component/controller invoking the models-table.

**Comment by cjrjscgallo** [comment]
I have not been able to get the dropdown to show any columns. This is from my template:

`  {{models-table-server-paginated
    data=model
    columns=columns
    showColumnsDropdown=true
    showGlobalFilter=false
    metaPagesCountProperty=metaPagesCountProperty
    metaItemsCountProperty=metaItemsCountProperty
  }}`

This is from my controller:

`  columns: [
    {
      "propertyName": "accountNumber",
      "title": "Account",
      "className": "cs-pull-right cs-narrow",
      "mayBeHidden": true
    }`
