### ISSUE TITLE
Setting pageSize programmatically in PageSizeSelect fails due to type mismatch

### ISSUE THREAD

**Issue by sihuang** [onechiporenko/ember-models-table#312]
* **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**
When trying to set a table's pageSize programmatically using a value (say 25) obtained from another table's PageSizeSelect component, the table's pageSize stays at default (10).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Table A with PageSizeSelect enabled, default options [10, 25, 50], pageSize=globals.pageSize
2. Table B with PageSizeSelect enabled, default options [10, 25, 50], pageSize=globals.pageSize
3. Select a non-default size, say 25, which updates globals.pageSize
4. Navigate to Table B, observe that page size dropdown stays at default 10

* **[Bug] What is the expected behavior?**
Table B's page size dropdown is set at 25

* **[Feature] What is the motivation / use case for changing the behavior?**
The root problem is in templates/components/models-table/select.hbs, the is-equal helper is expecting  numbers (type="number")
```javascript
<option value="{{option.value}}" selected={{is-equal value option.value type}}>{{option.label}}</option>
```
while in components/models-table/select.js, jQuery val() returns the value as a string,
```javascript
  change() {
    this.set('value', this.$('option:selected').val());
  }
```

* **[Support] What exactly you try to do?**

* **Please tell us about your environment:**

- `ember-models-table` version: 2.3.1
- `ember` version: 
- `ember-data` version: 
- `ember-cli` version:  2.12.2
- `node` version:
- `npm` or `yarn` version:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Currently this can be worked around by doing a parseInt() conversion on globals.pageSize in the model hook of Table B.

**Comment by sihuang** [comment]
@onechiporenko thanks for fixing this. Any idea when the next release will be available?

**Comment by onechiporenko** [comment]
@sihuang v2.6.1 is published
