### ISSUE TITLE
Problems faced while updating from v1 to v2

### ISSUE THREAD

**Issue by mayank8318** [onechiporenko/ember-models-table#313]
* **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - ~[x] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **[Support] What exactly you try to do?**
We have been using ember-models-table v1 in our project https://github.com/fossasia/open-event-frontend along with Semantic-UI. The code for that looks something like this -
```javascript
const defaultCssClasses = {
  outerTableWrapper              : 'ui ui-table',
  innerTableWrapper              : 'ui segment column sixteen wide inner-table-wrapper',
  table                          : 'ui tablet stackable very basic table',
  globalFilterWrapper            : 'ui row',
  columnsDropdownWrapper         : 'right floated columns-dropdown',
  columnsDropdownButtonWrapper   : 'buttons',
  columnsDropdown                : 'ui dropdown right floated',
  theadCell                      : 'ui',
  theadCellNoSorting             : 'table-header-no-sorting',
  theadCellNoFiltering           : 'table-header-no-filtering',
  tfooterWrapper                 : 'table-footer ui stackable grid',
  footerSummary                  : 'text muted table-summary',
  footerSummaryNumericPagination : 'column four wide',
  footerSummaryDefaultPagination : 'column four wide',
  pageSizeWrapper                : 'ui column eight wide grid',
  pageSizeSelectWrapper          : 'left aligned',
  paginationWrapper              : 'ui column right floated',
  paginationWrapperNumeric       : 'column four wide',
  paginationWrapperDefault       : 'column four wide',
  buttonDefault                  : 'ui basic button',
  noDataCell                     : '',
  collapseRow                    : 'collapse-row',
  collapseAllRows                : 'collapse-all-rows',
  expandRow                      : 'expand-row',
  expandAllRows                  : 'expand-all-rows',
  thead                          : '',
  input                          : '',
  clearFilterIcon                : 'remove circle icon',
  clearAllFiltersIcon            : 'remove circle outline icon',
  globalFilterDropdownWrapper    : 'ui row stackable grid'
}; 
```

We want to update to ember-models-table v2. On doing so, I realised that the newer version doesn't have the `innerTableWrapper` and the `outerTableWrapper` tags and hence the table isn't being rendered properly. I couldn't find any resources on this and also couldn't log into the Slack workplace, so I am posting it here. Really sorry about that.

* **Please tell us about your environment:**

- `ember-models-table` version: 
2.5.0
- `ember` version: 
- `ember-data` version: 
- `ember-cli` version:  
3.1.2
- `node` version:
8.10.0
- `npm` or `yarn` version:
npm - 3.5.2
yarn - 1.6.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Please guide me as to what I am missing or point me to any useful resources. :)
Thanks

**Comment by cah-briangantzler** [comment]
There are several ways to handle this, all have potential drawbacks. The first suggestion would be try to refactor the CSS to not require these DIVs as they are extra needless DIVs. 

If you cant do that the second way would be to everywhere you are using models table in the templates replace it with the contextual components, then add you divs as indicated here http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTable.html

It kinda sucks that you will have to reproduce this every place, but I cant come up with an easier way without complicating future changes.

```
{{#models-table data=data columns=columns as |mt|}}
<div class="outer-wrapper-class">
  {{mt.global-filter}}
  {{mt.data-group-by-select}}
  {{mt.columns-dropdown}}
  <div class="inner-wrapper-class">
     {{mt.table}}
  </div>
  {{mt.footer}}
</div>
```

**Comment by cah-briangantzler** [comment]
I saw that it didnt work for you, but was not sure exactly why to help. It also appeared that you were having problems with the classes. In v2 the class strings were moved to themes, I did not see from the screen shot that you had converted that. I see that you were merging into a classes property, but do not know how you were using that.

Let me know if I can be of any more help

**Comment by mayank8318** [comment]
@cah-briangantzler Thank you for the help. I tried to use the in-built semantic ui theme by using this - 
`import Semantic from 'ember-models-table/themes/semanticui';` and then ` themeInstance: Semantic,` but for some reason this isn't working. I also took reference from https://gist.github.com/onechiporenko/471b15cc58812b2a7da932f393677b37 . Please help me find out what I am doing wrong here.
Thanks

**Comment by cah-briangantzler** [comment]
The theme instance you import is a definition not an object. You have to create it. You would do the same thing the actual component is doing. It looks like you are doing the import correctly, but define the themeInstance property the same as here https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L421-L423

**Comment by mayank8318** [comment]
@cah-briangantzler Thank you for your patience and help. The gist was really helpful. I think I have managed to successfully update to v2. I also found a kinda semi guide for the conversion -> http://kronus.me/2017/10/theming-ember-models-table-2-x/
