### ISSUE TITLE
Pass ember object on propertyName

### ISSUE THREAD

**Issue by ultimatelocal** [onechiporenko/ember-models-table#316]
Hi Guys

I just want to ask on how to pass  DSPromiseObject on a property name, and access it's element on a component? 

When I passed the object to the `propertyName`: `DSPromiseObject` it is displayed on columncells like this : `<DS.PromiseObject:ember2314>` Thank you

 - `ember-models-table` version:  1.9.0

**Comment by cah-briangantzler** [comment]
Could you provide a little more detail on what you are attempting to do. I could see needed a computed property on property name, but I don’t understand why property name would ever be a promise

**Comment by ultimatelocal** [comment]
HI, 

Maybe because I'm passing a related model on the `propertyName` with `async:true` but I want to know if is it possible to pass an `ember object` thru `propertyName` then access it's elements normally on component? Thank you!

**Comment by cah-briangantzler** [comment]
Im going to take a guess at what you mean.

I think you are saying that one of the properties of your main object is also an object and can you access properties on this second object. Yes you can. 

Given
```
person = {
   firstName: "myName",
   address: {
        city: "myCity"
   }
}
```

you can build a column list as 
```
[
     { propertyName: "firstName" },
     { propertyName: "address.city" }
]
```

This example is for simplicity, but yes, address could be a promiseObject.

Is this the answer to your question?

**Comment by ultimatelocal** [comment]
Hi, 

Is it possible to do it like this : 
```
[
  { propertyName: 'address'}
]
```

and access `city` on the component where I assigned it? Because I'm gonna need to edit the whole object and save it on my api.

**Comment by cah-briangantzler** [comment]
What do you mean by on the component I assigned it. Do you have
```
[
  { propertyName: 'address', component: "some-component" }
]
```
If so, the component will receive a property called record, that property is the entire parent object, not just the address.

See http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTableCell.html for a list of all the properties and events that will be passed to your component. You see you will have access to your theme as well for styling.

If you are not doing this, please try to detail exactly what you are doing, what you are passing and as much relevant code as you can to get you your answer faster.

**Comment by ultimatelocal** [comment]
Hi sorry for the confusion but here's the exact scenario that I wan to implement. 

```
controller.js
columns : Ember.computed('address', function() {
  return [
      { propertyName: 'address', component: "some-component" }
  ]
})
```

```
template.hbs (some-component)
  <label> columns.address.city </label> // on my template on some-component I want to access the properties of the address object.
```

**Comment by cah-briangantzler** [comment]
change your component hbs to 
```
<label> record.address.city </label> 
```


Note: The property name of the current column, in this case "address", is passed in column.propertyName if you wanted to make your component more generic. When the cells normally display the string value of columns, if uses a component also, cell-content-display, here is the template for that component https://github.com/onechiporenko/ember-models-table/blob/master/addon/templates/components/models-table/cell-content-display.hbs
