### ISSUE TITLE
Build fails for lazily loaded engine

### ISSUE THREAD

**Issue by sfbwalder** [onechiporenko/ember-models-table#317]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**
When using ember-table-models in a lazily loaded engine, the build fails with:
```
- codeFrame: ENOENT: no such file or directory, open 'C:\dev\ember\Associations-UI\tmp\source_map_concat-input_base_path-5Z6A0ntn.tmp\vendor\ember-models-table\register-version.js'
- errorMessage: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. ðŸ’¥
ENOENT: no such file or directory, open 'C:\dev\ember\Associations-UI\tmp\source_map_concat-input_base_path-5Z6A0ntn.tmp\vendor\ember-models-table\register-version.js'
- errorType: Build Error
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a new addon, set it up as a lazily loaded engine, install ember-table-models, then the build fails.

* **[Bug] What is the expected behavior?**
The build should not fail.  See Other information below.

* **Please tell us about your environment:**

- `ember-models-table` version:  2.6.1
- `ember` version:  3.1.3
- `ember-data` version: N/A
- `ember-cli` version:  3.1.4
- `node` version: 8.11.1
- `npm` or `yarn` version: npm 5.6.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Based on [ember-engines #320](https://github.com/ember-engines/ember-engines/issues/320) and [ember-engines #544](https://github.com/ember-engines/ember-engines/issues/544), `app.import(...)` in [index.js](https://github.com/onechiporenko/ember-models-table/blob/master/index.js) need to be `this.import(...)`.
I hacked this change locally in `node_modules/ember-models-table/index.js`, and the build work.

**Comment by onechiporenko** [comment]
@sfbwalder check pls master. If it works for you, I'll publish new version.

**Comment by cah-briangantzler** [comment]
Any idea on the backward compatibility of this? I am assuming this is based on ember-cli, what version of ember-cli will this fail on? (ie it use to pass app, meaning at some point "this" was not a valid value)

There was also the issue the the if code checking the app.app, this I believe was for when this addon is included in another addon. Will the updated code still work for that situation?

It is interesting that the ember-cli docs for the current version still show using app.import https://ember-cli.com/extending/#importing-dependency-files 

Dont want to see a release that works for engines but breaks for everyone else.

**Comment by sfbwalder** [comment]
@cah-briangantzler The backwards compatibility does need checked out.  The story for using `this`, `app` and `app.pp` is not clear to me, but I am mostly a newbie.  Perhaps someone who knows more can provide guidance.

**Comment by cah-briangantzler** [comment]
@sfbwalder its been changing over time and getting better, but its pretty muddy for me as well which is why I raised the issue but didn't offer a solution.

Someone may have to ask in the ember slack channels and get a better insight

**Comment by onechiporenko** [comment]
@cah-briangantzler you are right. Backward compatibility is important. Personally I'm not so familiar with ember-cli. I see very dummy solution like this:

```js
// index.js

'use strict';

module.exports = {
  name: 'ember-models-table',

  included: function(app) {
    this._super.included.apply(this, arguments);

    // see: https://github.com/ember-cli/ember-cli/issues/3718
    if (typeof app.import !== 'function' && app.app) {
      app = app.app;
    }
    try {
      app.import('vendor/style.css');
      app.import('vendor/ember-models-table/register-version.js');
    }
    catch(e) {
      this.import('vendor/style.css');
      this.import('vendor/ember-models-table/register-version.js');
    }
  }

};
```
