### ISSUE TITLE
Help getting models-table-server-paginated working

### ISSUE THREAD

**Issue by shivani2692** [onechiporenko/ember-models-table#318]
I am trying to get models-table-server-paginated working in my product.

Defined a component - custom-table.js
```
import {computed} from '@ember/object';
import ServerModelsTable from 'ember-models-table/components/models-table-server-paginated';

export default ServerModelsTable.extend({
    metaPagesCountProperty: 'count',
    metaItemsCountProperty: 'itemsCount',
    filterQueryParameters: computed(function() {
        return {
            page: 'page',
            pageSize: 'pageSize'
        };
    })
});
```
My template file - log-details.hbs looks like :
```
 {{custom-table
    data=model
    columns=columns
    filterQueryParameters=filterQueryParameters
    useFilteringByColumns=false
    useNumericPagination=true
    showColumnsDropdown=false
    showGlobalFilter=false
    showPageSize=false
  }}
```
My controller - log-details.js file looks like:
```
import Controller from '@ember/controller';
import { inject } from '@ember/service';
import { LOG_COLUMNS } from '../utils/constants';

export default Controller.extend({
  /**
   * ember-simple-auth session, main interface to the library
   * http://ember-simple-auth.com/api/classes/SessionService.html
   */
  session: inject(),
  pageSize: 10,
  queryParams: [
    'vertical',
    'modelName',
    'modelVersion',
    'artifactName',
    'artifactVersion'
  ],

  /**
   * Columns to be displayed in the logs table
   */
  columns: LOG_COLUMNS
});
```

My routes file - log-details.js looks like:
```
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';
import Route from '@ember/routing/route';
import { inject } from '@ember/service';

export default Route.extend(AuthenticatedRouteMixin, {
  /**
   * ember-simple-auth session, main interface to the library
   * http://ember-simple-auth.com/api/classes/SessionService.html
   */
  session: inject(),

  queryParams: {
     page: {
      refreshModel: true
    }
  },

  /**
   * Use the url params to fetch the log data
   * @param  {Object} params     URL query params
   */
  model: function(params) {
    return this.store.query('log', params);
  },

  setupController(controller) {
    this._super(...arguments);
    controller.set('meta', {'itemsCount': 100, 'pagesCount': 10})
  },

  resetController(controller, isExiting) {
    if (isExiting) {
      controller.setProperties({
        pageSize: 10
      });
    }
  }
});
```

 My model - log.js looks like:
```
import DS from 'ember-data';

const { Model, attr } = DS;

export default Model.extend({
  vertical: attr('string'),
  modelName: attr('string'),
  modelVersion: attr('string'),
  artifactName: attr('string'),
  artifactVersion: attr(),
  logCreated: attr(),
  creator: attr('string'),
  state: attr('string'),
  message: attr('string'),
  logType: attr('string')
});
```

My query command does not return any meta. 
For now, I am hard-coding that we have 100 items and 10 pages. i.e. 10 items per page.

The table is loading, but I still see only one page in the table. Also, page and pageSize are not being added to my query parameters. 
Can you please help me understand what am I missing and get this working?

* **My environment:**

- `ember-models-table` version: 2.3.1
- `ember-data` version: 2.18.0
- `ember-cli` version:  2.18.2
- `node` version: 6.9.1

**Comment by onechiporenko** [comment]
Hi, @shivani2692. You can't use `models-table-server-paginated` without meta-info about overall records count and current page.

**Comment by shivani2692** [comment]
Hi @onechiporenko, I fixed the meta-info and the table is now rendering. But when I click on page 2, it does not take all the query parameters. It just takes one of the query parameter and adds page and pageSize as well. 

How can I make sure it takes all the query params that the route takes?

**Comment by shivani2692** [comment]
Since the query params were matching column names, the query params were being removed if no filter string is provided.

Setting 'useFilteringByColumns' to false, helped resolve the issue and get all query params.

Is there any way we can have all query params and get results based on that in the table. Then apply filtering only on the data retrieved (without changing names)?

**Comment by shivani2692** [comment]
I referred [#219](https://github.com/onechiporenko/ember-models-table/issues/219), 

If `useFilteringByColumns` is set to true, and query params and column names are the same

**Comment by shivani2692** [comment]
With useFilteringByColumns set to true, can we make sure it uses all other query params and just update the value for the query param where we provide a filter string?

**Comment by nag9329** [comment]
Hey @shivani2692 may I know how did you render the server side paginated table? I tried to give the meta info as below, but still when I use the server-table in my hbs, I don't see a table rendering.


`import modelsTableServerComponent from 'ember-models-table/components/models-table-server-paginated';

export default modelsTableServerComponent.extend({
  metaPagesCountProperty: 20,
  metaItemsCountProperty: 200,
  filterQueryParameters: {
		globalFilter: 'search',
		sort: 'sortcolumn',
		sortDirection: 'sortorder',
		page: 'pagenumber',
		pageSize: 'pagesize'
	},
});
`
