### ISSUE TITLE
Per-row custom classes

### ISSUE THREAD

**Issue by artsyca** [onechiporenko/ember-models-table#32]
I'd like to add a class to the row based on criteria of the `record`.
For example if `record.isFinalized` I'd like to add `is-finalized` to the `tr` (or each of its children)

Currently I can modify the template directly to add my class based on `record` like:

```
<tr class="{{if record.isFinalized "is-finalized"}}">
```

and it works, but it requires copying the `templates/models-table.hbs` into my project manually.. A configuration option would be most welcome here.

**Comment by onechiporenko** [comment]
Hi, @artsyca.
I'm thinking about your suggestion and can't find a best way to implement it.
Most simple way it's move:
```handlebars
<tr>
              {{#each processedColumns as |column|}}
                {{#if column.isVisible}}
                  <td class={{column.className}}>
                    {{#if column.template}}
                      {{partial column.template}}
                    {{else}}
                      {{get record column.propertyName}}
                    {{/if}}
                  </td>
                {{/if}}
              {{/each}}
            </tr>
``` 
to the separated template.

**Comment by artsyca** [comment]
Yes. I like the control of overriding templates as long as it can be done in a future proof way.

So far this addon fits my needs very closely and works great with Ember 2.1.

**Comment by KirillSuhodolov** [comment]
+ 1 to have this feature built-in.

**Comment by onechiporenko** [comment]
`rowTemplate`-property now is available.
