### ISSUE TITLE
No option to show/hide data-group-by-select

### ISSUE THREAD

**Issue by sihuang** [onechiporenko/ember-models-table#320]
There's the showGlobalFilter flag for global-filter component. I can't seem to find a flag for hiding data-group-by-select component. In my case, I'm grouping by only one field, hence don't need the "Group By" selection.

Is this possibly a missing feature?

**Comment by onechiporenko** [comment]
@sihuang you can create an empty template `templates/components/models-table/data-group-by-select.hbs`.

**Comment by sihuang** [comment]
Thanks @onechiporenko that works 👍
