### ISSUE TITLE
models-table-server-paginated - How to display a loader when page is loading from server

### ISSUE THREAD

**Issue by shivani2692** [onechiporenko/ember-models-table#321]
I am using models-table-server-paginated as follows:

Defined a component - custom-table.js
```
import {computed} from '@ember/object';
import ServerModelsTable from 'ember-models-table/components/models-table-server-paginated';

export default ServerModelsTable.extend({
    filterQueryParameters: computed(function() {
        return {
            page: 'page',
            pageSize: 'pageSize'
        };
    })
});
```

custom-table.hbs
```
{{#if isLoading}}
    {{loading-comp}}
{{/if}}
```

My template file - log-details.hbs looks like :
```
{{custom-table
    data=model
    columns=columns
    showColumnsDropdown=false
    showGlobalFilter=false
    useNumericPagination=true
    useFilteringByColumns=false
    showPageSize=false
    pageSize=10
    view="viewRecord"
    class="model-table"
}}
```

* **My environment:**

- `ember-models-table` version: 2.3.1
- `ember-data` version: 2.18.0
- `ember-cli` version:  2.18.2
- `node` version: 6.9.1

With these changes, the table does not load at all. If I remove custom-table.hbs file, then the table loads fine but without loader.

Can you please help me to get the loader working?

**Comment by cah-briangantzler** [comment]
Templates do not extend. Since you extended the models-table, you have to either have NO template as you found out, or duplicate the entire template from models table which would make upgrading problematic.

For what you are trying to do the best best is to put the loading if in the template that the log details template and put the models table in the else. (If you are using the loading if a lot, make it into a component and yield on the else, then you can wrap the models table in the loading component

**Comment by shivani2692** [comment]
Adding an if in the template log-details.hbs as shown below did not work.

```
{{#if isLoading}}
  {{loading-comp}}
{{else}}
  {{custom-table
    data=model
    columns=columns
    showColumnsDropdown=false
    showGlobalFilter=false
    useNumericPagination=true
    useFilteringByColumns=false
    showPageSize=false
    pageSize=10
    view="viewRecord"
    class="model-table"
  }}
{{/if}}
```

Am I missing something here?

**Comment by cah-briangantzler** [comment]
You are still using the extended custom-table. Have you removed the custom-table.hbs? I dont understand what the custom table is actually adding, you might be able to just use model-server-paginated-table directly.

I also assume that isLoading is changing appropriately.

Given that the custom-table.hbs does not exist, that should work. Could you be more specific on what doesnt work, and maybe repost some of the new relevant code.

**Comment by shivani2692** [comment]
Sorry for the typo. Yes, I understand that custom-table is not adding any value and did try using model-server-paginated-table directly.

Here is the contents on my log-details.hbs
```
{{#if isLoading}}
    {{table-loading}}
  {{else}}
    {{models-table-server-paginated
      data=model
      columns=columns
      showColumnsDropdown=false
      showGlobalFilter=false
      useNumericPagination=true
      useFilteringByColumns=false
      showPageSize=false
      pageSize=10
      class="model-table"
    }}
  {{/if}}
```

Even with this changes, the loader does not appear. The table and its contents in each page is rendered correctly.

**Comment by cah-briangantzler** [comment]
Ok, so if the loader is NOT appearing,  would have to assume isLoading is false.  Is {{table-loading}} just a string or a component? if component is there possibly a problem there?

You can insert {{log }} into the template to see things. I would update it to this 
```
{{log "isLoading: " isLoading}}
{{#if isLoading}}
    {{log "Im in the loading if"}}
    {{table-loading}}
  {{else}}
    {{log "Im displaying the table"}}
    {{models-table-server-paginated
      data=model
      columns=columns
      showColumnsDropdown=false
      showGlobalFilter=false
      useNumericPagination=true
      useFilteringByColumns=false
      showPageSize=false
      pageSize=10
      class="model-table"
    }}
  {{/if}}
```

check the console as to what is being printed and what is not. That may help you determine where the problem is. Based on the template alone, it appears correct. But I dont have the specs for isLoading and table-loading.

**Comment by shivani2692** [comment]
table-loading is a component, that has just a spinner image and "loading.." text.

I used the code snippet provided by you and the values printed on console are as follows:
1. When the route log-details.hbs is loaded
```
isLoading: undefined
Im displaying the table
```

2. Once the route is loaded and table is visible, clicking on page number 2 does not log anything on the console.

I just copied the entire template from https://github.com/onechiporenko/ember-models-table/blob/master/addon/templates/components/models-table.hbs and created a new file custom-table.hbs. Added the isloading if and in else part the contents of this file. With this change on clicking the next page, we see the loader and its working.

But I do not want to use this method. Hence trying if I can make it work without copying the contents of models-table.hbs

**Comment by cah-briangantzler** [comment]
So as you can see, the variable isLoading is undefined. That will equate to false. Thats why the isLoading spinner is never displayed. You will have to check your into that more as to where that variable is being defined and why it does not have a value, and that value is not being updated.
