### ISSUE TITLE
Add a column title when displayGroupedValueAs is set to 'column'

### ISSUE THREAD

**Issue by sihuang** [onechiporenko/ember-models-table#322]
In the "Grouped Rows" demo, when displayGroupedValueAs='column', the title of this grouped column (Bahamas, Bahrain, Belarus, etc.) is blank. I thought it would be nice to show "Country" as title above Bahamas, Bahrain, etc. How do I go about doing that? Which component should I extend? Thanks a lot.

**Comment by onechiporenko** [comment]
Now 'titlelized' property name is shown in this case. `groupHeaderCellComponent` component can be used to replace it:

```hbs
{{models-table
  groupHeaderCellComponent=(component "some-component")
}}
```

Component will receive such options:

* `currentGroupingPropertyName` - property name used to group rows in the current moment

**Comment by onechiporenko** [comment]
This feature will be in the next release (2.7.0)
