### ISSUE TITLE
toggleAllSelection() giving a javascript error

### ISSUE THREAD

**Issue by jpoiri** [onechiporenko/ember-models-table#325]
* **I'm submitting a ...**

  - [1 ] bug report

HI there,

I am trying to reproduce your example with multiple rows selected(http://onechiporenko.github.io/ember-models-table/v.2/#/examples/select-rows-with-checkboxes) but I am  getting this error when calling the toggleAllSelection() action:

EmberError {stack: "Error: Assertion Failed: The third argument to rep…(http://localhost:4300/assets/vendor.js:41194:14)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: The third argument to replace needs to be an array.", …}

* **Please tell us about your environment:**

- `ember-models-table` version:  2.6.1
- `ember` version:  2.18.2
- `ember-data` version: 2.18.1
- `ember-cli` version:  2.18.2
- `node` version:  6.9.1
- `npm` or `yarn` version: 3.10.8

**Comment by onechiporenko** [comment]
Hello, @jpoiri. I can't help here without reproduction demo. Could you create it on https://ember-twiddle.com ? Thanks

**Comment by beastmst** [comment]
hi.. i am facing the same problem.. i think it is when use result from ember data..

"Error: Assertion Failed: The third argument to replace needs to be an array.
    at Array.replace (http://localhost:4200/assets/vendor.js:53164:113)
    at Array.pushObjects (http://localhost:4200/assets/vendor.js:53008:12)
    at Class.toggleAllSelection (http://localhost:4200/assets/vendor.js:420526:44)


  replace | @ | array.js:734
  pushObjects | @ | array.js:578
  toggleAllSelection | @ | models-table.js:2173


sound like the toogleAllSelection... can you help to identify it? 
try created a ember twiddle.. but seems it is working as i am using the normal array in the twiddle

https://ember-twiddle.com/61ed78d22bd0dd68fbea2f85a9e79add?openFiles=components.select-all-rows-checkbox.js%2C

so guess when it use with ember data.. then something happen there

**Comment by beastmst** [comment]
Hi... quite confirm it is because the ember-data ... when use a pure array, the function work.
but when use record return by ember data, the error occured .. so I use this:

this.set('company', returnModel.toArray());  then everything work fine

**Comment by onechiporenko** [comment]
@beastmst could you please provide a demo with `ember-data`? I can't get repro using local env

**Comment by beastmst** [comment]
https://github.com/beastmst/ember-model-table

here you go

**Comment by onechiporenko** [comment]
@beastmst you are right. It's a bug that I missed in demo-app, because of `.slice`-usage in the route `example`. So, every example works with Array and not with `ember-data`-specific classes. I'm going to fix this.
