### ISSUE TITLE
Extract `sortMap` as component's property

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#327]
* **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**

`sortMap` currently is declared in the `sort` action in both `models-table` and `models-table-server-paginated`. It should be extracted to the `models-table`.

* **[Feature] What is the motivation / use case for changing the behavior?**

Extracting `sortMap` will allow to override without copy-paste whole action-handler `sort`

* **Please tell us about your environment:**

- `ember-models-table` version: 2.6.1
- `ember` version: 3.3.0
- `ember-data` version: 3.1.0
- `ember-cli` version: 3.3.0
- `node` version: 9.4
- `npm` or `yarn` version: 5

**Comment by cah-briangantzler** [comment]
Why would you ever want to override this map?

**Comment by onechiporenko** [comment]
I have a question in slack about changing order of sorting. Before this commit you can't change order to `none-desc-asc` without overriding the whole sort-method.
