### ISSUE TITLE
column sortDirection is reversed

### ISSUE THREAD

**Issue by Travelinglight** [onechiporenko/ember-models-table#332]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
The columns sort order is reversed during column setup

* **The minimal demo of the problem**
[Ember Fiddle](https://ember-twiddle.com/213573a63a455e003a1672e4c3db418a?openFiles=components.my-table.js%2Ctemplates.components.my-table.hbs)
Please see `components/my-table.js`, where the `sortDirection` of `sort_order` is defined as "asc"

* **What is the expected behavior?**
The rows should be sorted in the same order as specified in `columns`.

* **Please tell us about your environment:**
  - `ember-models-table` version: 2.6.1
  - `ember` version: 3.3.2
  - `ember-data` version: 3.3.0
  - `ember-cli` version: 3.3.0
  - `node` version: 6.14.4
  - `npm` version: 3.10.10

* **The reason**
I believe this bug was introduced in merge #308, specifically in file `models-table.js`, at the end of the function `_setColumns`. This merge removed the "unnecessary" initial sort and used the `sort` action instead. However, the `sort` action does a mapping before setting `sortProperties`, for example, "asc" would be mapped to "desc". This reverses the sort order.

**Comment by onechiporenko** [comment]
Hi, @Travelinglight! Thanks for submitting a bug report!

**Comment by onechiporenko** [comment]
@sly7-7 could you check this please?
