### ISSUE TITLE
Change size of page selector

### ISSUE THREAD

**Issue by flyrev** [onechiporenko/ember-models-table#338]
* **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**
With 4 pages, the page selector collapses into 1,2,...,4.

* **[Feature] What is the motivation / use case for changing the behavior?**
It would be good to say "collapse after N pages".

* **Please tell us about your environment:**

- `ember-models-table` version: 2.7.0
- `ember` version: 3.5.0
- `ember-data` version: 3.4.2
- `ember-cli` version:  3.5.0
- `node` version: v10.11.0
- `npm` version: 6.4.1

**Comment by onechiporenko** [comment]
Property `collapseNumPaginationForPagesCount` is added to the `models-table`. Its default value is `1`. Feel free to set it `4` or any other needed value:

```hbs
{{models-table data=model columns=columns collapseNumPaginationForPagesCount=4}}
```

**Comment by flyrev** [comment]
Great stuff, thanks!

When will you bump the version number again?

**Comment by onechiporenko** [comment]
Done. 2.8.0 is published

**Comment by flyrev** [comment]
Sorry to comment again on this: but having 7 pages and the setting set to 4 will give the initial menu of 1,2,...,7.

Any way to make the initial list at least 5 also? Ideally 1,2,3,...,7,8 or 1,2,...,7,8 would both be good. Or simply have a setting for "on each side" initially (for example setting it to 2 would give 1,2,...,7,8).

**Comment by onechiporenko** [comment]
Well, it's another issue :)
You can implement it in your project by overriding `components/models-table/numeric-pagination`.
