### ISSUE TITLE
`filterWithSelect: true` creates unexpected exception on route away and modifying table data

### ISSUE THREAD

**Issue by hbrysiewicz** [onechiporenko/ember-models-table#342]
**I'm submitting a bug report**

**What is the current behavior?**

Upgrading `ember-models-table` to 2.8.0 from 2.3.0.
App is on Ember 3.6, Ember Data 3.6.

Application creates a models-table with one of the columns defined to use `filterWithSelect: true` and *without* `predefinedFilterOptions` set. The models-table renders and behaves as expected. User routes to a different page, a form for one of the items listed in the models-table on the previous route, and edits some of the data. This error is thrown: 

```
"Assertion Failed: Cannot create a new chain watcher for `<connectui@component:models-table::ember787>` after it has been destroyed."
```

When the models-table was initialized on route 1, `filterOptions` is set for this column to the dynamic CP created by `getFilterOptionsCP` here: https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L1427

Routing away from route 1 properly destroys the models-table component as expected, but for some reason the observer on this column still exists. 

https://github.com/onechiporenko/ember-models-table/blob/7fb6a30747e1f9e1bee6a690fdf6f6584fe4d3c5/addon/utils/column.js#L500-L514

When the User fills out the form and edits the record that was displayed in the models-table on route 1, it triggers this observer to fire, which requests the `filterOptions`, which then throws the previously mentioned error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I am working on a smaller isolated example of this behavior but have described in length above steps to reproduce in theory. Any info while generating smaller example would be much appreciated.

**Update**

Here is a working example of the bug: https://github.com/hbrysiewicz/filter-with-select-example

To reproduce:
0. Clone the repo.. `npm i` and all that jazz
0. Launch the app with `ember s`
0. Visit http://localhost:4200 in your browser of choice
0. Select the `Edit` button for any record
0. Change the "Status" value for a record

![](http://g.recordit.co/R3zgAGWhzF.gif)

**[Bug] What is the expected behavior?**

Expected behavior is for this observer not to fire because the models-table component is is trying to watch no longer exists.

**Please tell us about your environment:**

- `ember-models-table` version: 2.8.0
- `ember` version: 3.6.0
- `ember-data` version: 3.6.0 
- `ember-cli` version:  3.6.0
- `node` version: 8.14.0
- `npm` or `yarn` version: npm 6.5.0

**Comment by onechiporenko** [comment]
Hi, @hbrysiewicz. Thanks for such detailed report! Going to work on fix

**Comment by onechiporenko** [comment]
Fix is already in master.

**Comment by hbrysiewicz** [comment]
Awesome! Thanks so much for the fast fix, @onechiporenko! Will there be a patch release tagged for this?

**Comment by onechiporenko** [comment]
I think it's possible to create a `2.9.0-beta.1` for this. Some extra features are already in master and ready to be published. New release will be in a day or two

**Comment by jlblcc** [comment]
@hbrysiewicz :1st_place_medal: Thanks for tracking this down!
