### ISSUE TITLE
Missing component usage in v2 demo

### ISSUE THREAD

**Issue by CezaryH** [onechiporenko/ember-models-table#344]
Please add component usage examples to v2 demo.
That would be very helpful.

Thanks

**Comment by onechiporenko** [comment]
README.md has links for several demos in the ember-twiddle. All of them are for v2. Did you check them?

**Comment by MLeganes** [comment]
@onechiporenko 
I forgot about this demos. You are right. Thank you so much for your fast replay.

**Comment by MLeganes** [comment]
@onechiporenko 
It is good ember-twiddle. In the demo, a brief of the configuration details it was useful and more accurate, I think It was a good extra documentation to have there it.
Thank you for big work and effort.

**Comment by CezaryH** [comment]
@onechiporenko ok, I haven't check that, my bad.
Maybe it's good idea to add those links to examples page.

Thanks for answering.
