### ISSUE TITLE
Remove jquery usages

### ISSUE THREAD

**Issue by BenDoan** [onechiporenko/ember-models-table#348]
I'm looking to add ember-models-table to an app I'm working on, but I'm looking to avoid bundling jquery. It looks like ember-models-table uses jquery just a couple times. Would you be open to a PR that removed these uses?

**Comment by onechiporenko** [comment]
Hi, @BenDoan. I thought that jQuery is used only in dev-mode. I did some code changes to remove jQuery usage (#324). PR would be great if I've missed something.

**Comment by BenDoan** [comment]
Heh, you're right, I guess it's been a while since I re-pulled my ember-models-table checkout.

Thanks for the awesome work!
