### ISSUE TITLE
Server Side Pagination

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#35]
How difficult would it be to support server side pagination? In my case I am using ember-data and have some cases where there are tens of thousands of records. Pulling them all into the frontend is not possible.

From #34

**Comment by listepo** [comment]
@onechiporenko see http://jsonapi.org/format/#fetching-pagination for Ember Data

**Comment by cimtico** [comment]
It might also be worth looking into https://github.com/mharris717/ember-cli-pagination

**Comment by KirillSuhodolov** [comment]
@onechiporenko if there is any success with implementation this feature?

**Comment by stonetwig** [comment]
What is the status on this feature @onechiporenko ?
