### ISSUE TITLE
I want to disable internal scroll and change column widths of my table

### ISSUE THREAD

**Issue by kushthedude** [onechiporenko/ember-models-table#361]
* **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**

Currently, i am not able to disable internal scroll and change the column widths, Which is depreciating UI for my App

* **[Bug] What is the expected behavior?**

Please provide the way to do such operations

* **[Feature] What is the motivation / use case for changing the behavior?**
Improve the UI for certain Apps

* **Please tell us about your environment:**

- `ember-models-table` version: 2.5.0
- `ember` version: .6.0
- `ember-data` version: 3.3.1
- `ember-cli` version:  3.10
- `node` version:4.5 || 6.* || >= 7.*
- `npm` or `yarn` version:>= 1.0.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
#### Screenshot
![image](https://user-images.githubusercontent.com/44091822/57859139-fd3d3400-780f-11e9-9c39-af0185f0e270.png)

**Comment by onechiporenko** [comment]
Hi, @kushthedude. You are able to set custom css-classes for each table cell and add a custom styles for them (`width` etc). Also you can set `overflow` for block-elements.
Custom styling is not a thing that `ember-models-table` provides itself.
