### ISSUE TITLE
input fields missing label element

### ISSUE THREAD

**Issue by MelSumner** [onechiporenko/ember-models-table#369]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
The input fields used for filtering data doesn't have an associated label. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/4587451/63051502-f8396080-bea2-11e9-9849-7fa4c8c454b4.png)

* **[Bug] What is the expected behavior?**
Even if the `<label>` element is not visible, it should still exist. 
- `<input>` should have an `id` attribute with a valid value
- `<label>` element should have a `for` attribute whose value is the same as the `<input>` element
- if it is desirable to visually hide the `<label>` element,  a CSS class that makes the content available for screen readers only (see Bootstrap's `.sr-only` CSS class)

**Comment by cah-briangantzler** [comment]
I dont know if the label can be in different cells, but shouldnt the cell above the filter input be the the content wrapped in the label?

**Comment by MelSumner** [comment]
@cah-briangantzler 

1. you could definitely check to see if you can associate the two by using the `aria-describedby` attribute on the `<input>` field where the value is the `id` of the column header text. 

2. however, for increased usability you'd want it to be more descriptive, which is why I'd suggest the label element that is only visible to other machines (like screen readers). One idea could be something like `<label for={{@input-id}} class="sr-only">Filter the results for the {{this.columnLabel}} column</label>` or similar, with the caveat that ideally you'd provide a method to internationalize the text.

**Comment by onechiporenko** [comment]
Hi, @MelSumner. Thanks for your submission. I guess it's for both `v.2` and `v.3`?
If you find any other issues with accessibility of `ember-models-table` fill free to open other issues. I'm open to provide any needed things for accessibility, however I'm not familiar with it. You comments about possible solutions are very helpful to me.

**Comment by onechiporenko** [comment]
Done. Going to be in the next release.

**Comment by onechiporenko** [comment]
`v2.11.0` and `3.0.0-beta.2` are published
