### ISSUE TITLE
Model data not getting populated in table

### ISSUE THREAD

**Issue by opoudel** [onechiporenko/ember-models-table#38]
Hi, 
Awesome component, this is what I was looking for, I am relatively new in ember and I have following function in controller

reg: function() {
    	console.log(this.get('content'))
    	return this.get('content');
    }.property('content.[]'),

and my template has 

{{models-table columns=columns data=reg.content filteringIgnoreCase=true}}

template renders columns but not data. 

This may not be an issue, I must be missing something but there is no place where I can ask question so submitting as issue.

My environment:

version: 1.13.8
node: 3.2.0
npm: 2.13.4
os: darwin x64

Cheers

**Comment by onechiporenko** [comment]
@opoudel,  `data=reg.content` should be `data=content` or `data=reg`.

**Comment by opoudel** [comment]
I tried that as well when I do data=content or data=reg, I get "Uncaught Error: Assertion Failed: A helper named 'get' could not be found"

**Comment by onechiporenko** [comment]
Oh, I've added `ember-get-helper` as dev-dependency. Try execute:
```
ember install ember-get-helper
```

**Comment by opoudel** [comment]
Perfect Thanks!
