### ISSUE TITLE
isExpanded is undefined in block content

### ISSUE THREAD

**Issue by jimmyNg** [onechiporenko/ember-models-table#389]
* **I'm submitting a ...**

  - [x] bug report

* **What is the current behavior?**
I am trying to access `isExpanded` in block content. But the value is always `undefined`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
This is the code:
```hbs
  <table.body as |body|>
  {{#if body.visibleContent.length}}
    {{#each body.visibleContent as |record index isExpanded|}}
      <body.row @record={{record}} @index={{index}} @isExpanded={{isExpanded}} as |row|>
        {{log row.cell.isExpanded}}
        {{log row.isExpanded}}
        {{#each row.visibleProcessedColumns as |column index|}}
          <row.cell @column={{column}} @index={{index}}/>
        {{/each}}
      </body.row>
      {{#if (exists-in body.expandedItems record)}}
        <body.row-expand @record={{record}} @index={{index}} />
      {{/if}}
    {{/each}}
  {{else}}
    <body.no-data />
  {{/if}}
</table.body>
```

* **[Bug] What is the expected behavior?**
If I am doing this wrong then what is the correct way to access isExpanded or some flagging indicating row is expanded? thanks

**Comment by onechiporenko** [comment]
Could you try to remove `isExpanded` from `|record index isExpanded|`? Also remove ` @isExpanded={{isExpanded}}` from the next line.
Value for `isExpanded` is calculated inside `row` components ans it's not "yielded". Check `(exists-in body.expandedItems record)` is correct and should help you

**Comment by jimmyNg** [comment]
Thanks @onechiporenko the `exists-in` will do the job.
