### ISSUE TITLE
sort and filter by hasMany field

### ISSUE THREAD

**Issue by cresg820** [onechiporenko/ember-models-table#39]
I think that is useful to add sort and filter on hasMany field.
Currently i'm achieving this using a computed property like this
```
orgs : Ember.computed('organizations.[]', function(){
    var o= '';
    this.get('organizations').forEach(function(item){
      o +=' ' + item.get('symbol');
    });
    return o;
  }),
```
where organizations is the hasMany field.

**Comment by onechiporenko** [comment]
@cresg820, could you create a demo in the jsfiddle or jsbin and show what exactly needed? Currently, I can't understand.
