### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by avdmatamoros** [onechiporenko/ember-models-table#40]
Would it be possible to have the grid work with https://github.com/miguelcobain/ember-paper or https://github.com/mike-north/ember-material-lite instead of only bootstrap?

**Comment by onechiporenko** [comment]
@avdmatamoros, could you provide a list of changes that need to be done in the `ember-models-table` to support grid from `ember-paper` or `ember-material-lite`?
Thanks

**Comment by avdmatamoros** [comment]
it is mostly css, such as the column classes.
however the big one that "broke" was the columns drop down.

I'll try to get some changes done locally to get a better idea as to exatly needs to be done, but I'm not sure when I might have it ready.

**Comment by onechiporenko** [comment]
@avdmatamoros, I've committed some changes that allow to customize css-classes used in the component-markup.

**Comment by cimtico** [comment]
hey
I was able to play around with the templates a bit and make it look/work with ember paper
https://github.com/cimtico/ember-models-table

https://github.com/cimtico/ember-models-table/commit/ee6f9f3b6f4397b5df2634f3d229fbc7153b5544

I also used a bit of cutom css to adjust a couple things that might be solved better with your newer changes.

    .models-table-wrapper {
      .table-footer {
        padding: 10px 5px;
        border-top: 1px solid #d0d0d0;
      }
      table {
        padding: 10px 5px;
    
        thead {
          tr {
            td, th {
              padding-bottom: 0;
            }
            &:last-child {
              td, th {
                padding-top: 5px;
              }
    
              input {
                height: auto;
              }
            }
          }
        }
      }
      > .pull-left {
        padding: 10px 5px 0;
        input {
          height: auto;
        }
      }
    }
