### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by kafkahw** [onechiporenko/ember-models-table#402]
* **I'm submitting a ...**

  - [* ] bug report
  - [ ] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**
In README.md, all the examples under the section `More complex usage-examples` can't be opened.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Click any examples under [More complex usage-examples](https://github.com/onechiporenko/ember-models-table/blame/master/README.md#L85) in chrome or firefox.

* **[Bug] What is the expected behavior?**
Examples mentioned above can be accessed successfully.

* **[Feature] What is the motivation / use case for changing the behavior?**
It will significantly help library consumers better understand how to use this library.

* **[Support] What exactly you try to do?**
Update README doc.

* **Please tell us about your environment:**
N/A
- `ember-models-table` version: 
- `ember` version: 
- `ember-data` version: 
- `ember-cli` version:  
- `node` version:
- `npm` or `yarn` version:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by onechiporenko** [comment]
@kafkahw I was able to open all of the examples and didn't get any issues. What kind of problem did you get?

**Comment by kafkahw** [comment]
thanks for looking into this @onechiporenko . I think the issue was intermittent and it works fine to me now. I'm closing this issue.
