### ISSUE TITLE
Lots of questions...

### ISSUE THREAD

**Issue by Subaku** [onechiporenko/ember-models-table#414]
Hi,

This addon looks great! I'm running afoul of many things however and can't seem to get what I want working and the API docs confuse me with certain properties seemingly not working or just from the lack of examples to common situations.

For reference I'm running the latest versions of Ember and this addon:
Ember: 3.17.0
Ember Data: 3.17.0
Ember Models Table: 3.0.1

1. Does setting `sortProperties` directly on the ModelsTable do anything? When i give it something like `['propertyOne:asc', 'propertyTwo:desc']` nothing happens.
2. I'm trying to get basic multi column sorting to work. My columns:
```
[
  { sortDirection: 'asc', sortPrecedence: 1, simple: true, title: 'Asset Type', propertyName: 'asset.assetType' },
  { sortDirection: 'desc', sortPrecedence: 0, simple: true, title: 'Last Seen On', propertyName: 'whenSeen'},
]
```
This appears to work except when I swap the precedence I get the following error:
`Error: Property set failed: object in path "asset" could not be found.`
Besides what appears to be a bug I'm also wondering how I might disable a user from click sorting the table. My goal is to load the table with a default sorting and leave it be.
3. Am I using `sortFunction` wrong?
`  { sortFunction: function(a1, a2) {console.log(a1, a2); return -1}, sortPrecedence: 1, simple: true, title: 'Asset Type', propertyName: 'asset.assetType', slug: 'asset-type' },`
When I added this but left my "whenSeen" column alone the console logs the values for the "whenSeen" column! Wat.
4. Smaller question, the `simple` option in my columns above I like. I have a lot of rows to render. Are there any options similar to that for the other table components? I.e. Don't use a component to render each cell etc.
5. Is there any way to disable pagination?
6. Is there an option for having the table headers sticky? Or am I left up to styling it myself to accomplish this?
7. I assume in light of doing something like Occlusion for lots of rows the solution is to paginate. Makes sense. If using ModelsTableServerPaginated however to handle loading lots of rows am I allowed to do multi sort? The API docs seem to say no but there was a closed ticket that seemed to allow this.

Sorry for wall of text. Came from Ember-Table and was just trying to get something basic working to replace it but running into a wall pretty quickly...

**Comment by onechiporenko** [comment]
Hello, @Subaku. Sorry, for late response.

1. `sortProperties` is a protected property and should not be set directly.
2. Property `disableSorting` should be set to `true` for column to prevent its sorting.
3. You are using `sortFunction` correctly.
4. Block-form can be used in this case:
```hbs
<ModelsTable @data={{this.model}} @columns={{this.columns}} as |MT|>
  <MT.GlobalFilter/>
  <MT.ColumnsDropdown/>
  <MT.Table as |Table|>
    <Table.Header/>
    <Table.Body as |Body|>
      {{#if MT.allColumnsAreHidden}}
        <Body.ColumnsHidden/>
      {{else}}
        {{#each MT.visibleContent as |record index|}}
          <Body.Row @record={{record}} @index={{index}}>
            {{#each MT.visibleProcessedColumns as |column|}}
              <td>{{get record column.propertyName}}</td>
            {{/each}}
          </Body.Row>
        {{else}}
          <Body.NoData/>
        {{/each}}
      {{/if}}
    </Table.Body>
  </MT.Table>
  <MT.Footer/>
</ModeldTable>
```
5. You can use block-form:
```hbs
<ModelsTable @pageSize={{100500}} @data={{this.model}} @columns={{this.columns}} as |MT|>
  <MT.GlobalFilter/>
  <MT.ColumnsDropdown/>
  <MT.Table/>
  <MT.Footer as |Footer|>
    <Footer.Summary />
  </MT.Footer>
</ModelsTable>
```
6. Nope, you should do it yourself for now.
7. Yes, component `ModelsTableServerPaginated` should be used in the cases when table's data is not loaded fully. So, sorting, filtering and pagination cause some requests to the server to get needed list of records to show.
Two thing need to be done to use it. Firstly, `data` should be a result of `store.query` execution. Secondly, `filterQueryParameters` should provided to the component. It contains names for query parameters.
For multiple sorting you should set `multipleColumnsSorting` (component's attr) to `true`.

**Comment by eccegordo** [comment]
The block form explains a lot now.

It would be helpful if in the docs somewhere maybe there was a new section "custom styles and class names with block helpers". 

What is kind of tricky to follow is all the abstractions in the dummy app. So it takes a bit to follow along exactly how the custom theming works. 

Even better would be a stand alone example app in a different repo.

**Comment by onechiporenko** [comment]
@eccegordo here is entry-point for [API docs](http://onechiporenko.github.io/ember-models-table/v.3/docs/classes/Components.ModelsTable.html). Every component has a section with block and non-block usage.
Also there is a demo for block usage - http://onechiporenko.github.io/ember-models-table/v.3/bs4/#/examples/block-usage
It has two examples - simple and "not simple" :)
