### ISSUE TITLE
Get table information

### ISSUE THREAD

**Issue by tricia421** [onechiporenko/ember-models-table#416]
Question: I am trying to get information on the table's status before going to a new page. This is so that when I go back I can make sure the table is in the same state. I need to know how the table is sorted, if there is a search, and what the current page is. How do I do this?

**Comment by onechiporenko** [comment]
Hi, @tricia421. Please, check demo [Action: Display Data Changed](http://onechiporenko.github.io/ember-models-table/v.3/bs3/#/examples/display-data-changed-action) or more complex example [Query Parameters](http://onechiporenko.github.io/ember-models-table/v.3/bs3/#/examples/query-params)
