### ISSUE TITLE
Lots of Question regarding custom components in rows

### ISSUE THREAD

**Issue by sutharmonil** [onechiporenko/ember-models-table#421]
I am using ember models table v 3.0.1 with Ember v 3.18. 
I am trying to build some custom actions for each row like edit, delete etc. 
I tried to follow this sample: http://onechiporenko.github.io/ember-models-table/v.3/bs4/#/examples/custom-components-in-cell

But I ended up more confused than ever. Please let me know if there are any example or tutorials I can learn from. 

What I basically needs is a table that supports actions like click on the Edit button -> Takes the user to a page to edit, click on the delete button show a confirm popup and delete the item via some API call.

**Comment by cah-briangantzler** [comment]
refer to this issue, I hope that better explains how contextual components are being used. https://github.com/onechiporenko/ember-models-table/issues/349

**Comment by sutharmonil** [comment]
How does one:
1. Remove the search label and place a text as a placeholder inside the search box?
2. How to display a sort order icon on the column headers?
3. Also, would like to know if there is a setting to center the pagination's number of rows dropdown.
4. Also, default number of rows setting.
