### ISSUE TITLE
#useFilter computed property was just overriden

### ISSUE THREAD

**Issue by ulyssessantos** [onechiporenko/ember-models-table#424]
* **Deprecation report**

  - [x] deprecation report
  - [ ] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

console log:
DEPRECATION: The <(unknown):ember190>#useFilter computed property was just overridden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
        at logDeprecationStackTrace (http://localhost:4201/assets/vendor.js:47313:21)
        at HANDLERS.<computed> (http://localhost:4201/assets/vendor.js:47410:9)
        at raiseOnDeprecation (http://localhost:4201/assets/vendor.js:47340:9)
        at HANDLERS.<computed> (http://localhost:4201/assets/vendor.js:47410:9)
        at invoke (http://localhost:4201/assets/vendor.js:47422:9)
        at deprecate (http://localhost:4201/assets/vendor.js:47378:28)
        at ComputedProperty.clobberSet (http://localhost:4201/assets/vendor.js:26461:49)
        at ComputedProperty.set (http://localhost:4201/assets/vendor.js:26429:21)
        at ModelsTableColumn.CPSETTER_FUNCTION [as useFilter] (http://localhost:4201/assets/vendor.js:25390:25)

- `ember-models-table` version: 3.2.0
- `ember` version: 3.18.1
- `ember-data` version: 3.18
- `ember-cli` version:  3.19.0
- `node` version: 10.13.0
- `npm` or `yarn` version: npm 6.4.1, yarn 1.22.4

**Comment by ulyssessantos** [comment]
So, apparently there is still some computed property that has not been converted? does anyone else go through this?

**Comment by onechiporenko** [comment]
Hi, @ulyssessantos. You should set `disableFiltering=true` for column. `useFilter` is a protected computed property and should not be set directly

**Comment by ulyssessantos** [comment]
The property was not set directly, only @data and @column, as below:
<ModelsTable
  @data={{this.data}}
  @columns={{this.columns}}>

**Comment by onechiporenko** [comment]
What is inside `this.columns` ?

**Comment by ulyssessantos** [comment]
import Route from '@ember/routing/route';
import fetch from 'fetch';
import { get, set } from '@ember/object';
import { getOwner } from '@ember/application';

export default class ModelsTableDataRoute extends Route {
    async model() {
        let response = await fetch('/events.json');
        let data = await response.json();
        return data.events;
    }

    setupController(controller, model) {
        super.setupController(controller, model);

        set(controller, 'columns', [
            { "propertyName": "id" },
            { "propertyName": "created_at" }
        ])
        const owner = getOwner(this);
        const theme = owner.lookup('component:models-table').themeInstance;
        get(controller, 'columns').unshiftObject({
            component: theme.rowSelectCheckboxComponent,
            useFilter: false,
            mayBeHidden: false,
            componentForSortCell: theme.rowSelectAllCheckboxComponent
        });
    }
}

**Comment by onechiporenko** [comment]
> useFilter: false,
should be `disableFiltering: true`

**Comment by ulyssessantos** [comment]
I should have seen this, thank you very much!
