### ISSUE TITLE
select.hbs `type` isn't used anymore

### ISSUE THREAD

**Issue by kwliou** [onechiporenko/ember-models-table#431]
* **I'm submitting a ...**

  - [ X ] bug report
  - [ ] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**
After this PR https://github.com/onechiporenko/ember-models-table/pull/428
the ember-truth-helpers `is-equal` (takes 2 arguments) is being used instead of your custom `is-equal` in select.hbs which takes 3 arguments.
```
selected={{is-equal this.value opt.value this.type}}>
```

The `type` parameter doesn't have any documentation so I suppose there wasn't any guaranteed behavior.
https://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTableSelect.html

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **[Bug] What is the expected behavior?**

* **[Feature] What is the motivation / use case for changing the behavior?**

* **[Support] What exactly you try to do?**
Just saw an unused `type` in the hbs so you could just remove it? Users can just pass a string instead of a number in `filterOptions` but I wasn't using older versions. If it was existing documented logic then I guess you could add back your own is-equal or convert the value to string first
```
    selected={{is-equal this.value (concat opt.value)}}>
```
I noticed the previous custom is-equal converted both to numbers so "" was "equal" to 0, was that desired?

* **Please tell us about your environment:**

- `ember-models-table` version: 
- `ember` version: 
- `ember-data` version: 
- `ember-cli` version:  
- `node` version:
- `npm` or `yarn` version:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by onechiporenko** [comment]
Hello, @kwliou. Thanks for your feedback.

I think I just forget to remove third parameter from `is-equal`. `Select` has a `type`-property used to track numbers. So, if `<ModelsTable::Select>` will get  `@type="number"`, its selected value will be converted to `number`.

Well, I can't promise that users won't pass "stringified" numbers to `options`, but I think it's not a `Select`'s problem :)

I'll remove unneeded param `type` shortly.
