### ISSUE TITLE
Option to hide top search and column dropdown button.

### ISSUE THREAD

**Issue by ehariprasad** [onechiporenko/ember-models-table#44]
Hi,

Is there any options provided such that top search and column buttons should not be loaded. 

Just a plain listview along with bottom navigations is required at some places for me in my application.

Its awesome plugin...

Cheers,

**Comment by onechiporenko** [comment]
Hi, @ehariprasad.
Option `showColumnsDropdown` allow to hide columns dropdown
Option `showGlobalFilter` allow to hide global filter
Option `useFilteringByColumns` allow to hide column filters
