### ISSUE TITLE
The `customClasses` option is incorrectly documented

### ISSUE THREAD

**Issue by Davidhidalgo** [onechiporenko/ember-models-table#46]
Change the `customClasses` option on your docs. You are pointing to `customCssClasses` and the correct option is `customClasses`
<img width="693" alt="screen shot 2015-12-04 at 12 48 22" src="https://cloud.githubusercontent.com/assets/532985/11589046/92745c7c-9a85-11e5-8fbe-2c287c53c9a2.png">

**Comment by onechiporenko** [comment]
Fixed, thanks!
