### ISSUE TITLE
Dynamic columns not working.

### ISSUE THREAD

**Issue by KirillSuhodolov** [onechiporenko/ember-models-table#47]
it will be great something like this: 

 ```
  setupColumns: Ember.on('init', Ember.observer('columns.@each.propertyName', function() {
    this._setupColumns();
  })),
```

Due to that I have columns based on computed properties.

Same for sortBy, template and others.

**Comment by Davidhidalgo** [comment]
Agree with this!

**Comment by onechiporenko** [comment]
I've spent some time to find out best way to implement this feature and found out next:
* This feature should be toggleable (`disabled` by default)
* It's pretty easy to make `_setupColumns` observer for some `columns`-fields
* `_setupColumns` should not observe hardcoded fields
* `_setupColumns` should be called only once (using `Ember.run.once`)
* It's pretty difficult to restore `processedColumns` states like sorting, filtering, visibility etc

What is implemented:
* `columnsAreUpdateable`-property is determine should `processedColumns` be updated if `columns`
are changed
* `columnFieldsToCheckUpdate` - it is a list of `columns`-fields that may trigger `_setupColumns`. This list is setup on component-init and won't be checked any more after init. By default list is  `['propertyName', 'template']`.

Usage example:
```hbs
{{models-table data=data columns=columns columnsAreUpdateable=true columnFieldsToCheckUpdate=['propertyName', 'template']}}
```
