### ISSUE TITLE
Custom messages not refreshed on the table

### ISSUE THREAD

**Issue by jpoiri** [onechiporenko/ember-models-table#49]
Hi there,

I have an application that support both English and French and I would like to be able to change the customMessages based on the locale selected, to implement this I have a computed property that returns the custom messages based on the locale. When the locale is changed the computed property is called however the table is not refreshed.

Controller:

    messages: Ember.computed('i18n.locale', function() {
		let i18n = this.get('i18n');
		return Ember.Object.create({
			'searchLabel': '' + i18n.t('component.mx_data_grid.label.search'),
			'columns-title': '' + i18n.t('component.mx_data_grid.label.columns'),
			'columns-showAll': '' + i18n.t('component.mx_data_grid.label.show_all'),
			'columns-hideAll': '' + i18n.t('component.mx_data_grid.label.hide_all'),
			'columns-restoreDefaults': '' + i18n.t('component.mx_data_grid.label.restore_defaults'),
			'tableSummary': '' + i18n.t('component.mx_data_grid.label.table_summary'),
			'allColumnsAreHidden': '' + i18n.t('component.mx_data_grid.label.all_columns_hidden'),
			'noDataToShow': '' +i18n.t('component.mx_data_grid.label.no_data')
		});
	}),

Template:

     {{models-table customIcons=icons customMessages=messages columns=participantColumns data=model}}

**Comment by onechiporenko** [comment]
Actually, table won't refresh messages. They are set on the init-phase.
But I'll try to implement your suggestion.

**Comment by jpoiri** [comment]
Ok thank you

**Comment by onechiporenko** [comment]
It works now if whole object is updated.
