### ISSUE TITLE
column template

### ISSUE THREAD

**Issue by acerov** [onechiporenko/ember-models-table#50]
Hi there,

how to make one generic column template for all numeric columns?

I tried to reference current column with `{{record.column}}` and `{{column}}` without success

documentation says:

{{!`record` - row from content, current column is available as `column`}}

**Comment by onechiporenko** [comment]
@acerov, you may set custom template for cell. See "Table with custom template in the cell" in the http://onechiporenko.github.io/ember-models-table/

**Comment by acerov** [comment]
@onechiporenko, yes I saw that and it works ok with `{{record.myColumnName}}` but I have many columns that need the same template so I was hoping I can do `{{record.column}}`

**Comment by onechiporenko** [comment]
You may define custom template for multiple columns:
```javascript
columns: [
  {
    "propertyName": "firstName",
    "title": "First Name"
  },
  {
    "template": "custom/mynumerictemplate",
    "title": "Numeric 1"
  },
  {
    "template": "custom/mynumerictemplate",
    "title": "Numeric 2"
  }
]
```

**Comment by acerov** [comment]
```javascript
columns: [
    {
        "propertyName": "quantity",
        "title": "Quantity"
        "template": "custom/mynumerictemplate",
    },
    {
        "propertyName": "price",
        "title": "Price"
        "template": "custom/mynumerictemplate",
    }
]
```
what to put in custom/mynumerictemplate.hbs ?
this works just for "price"
```javascript
{{record.price}}
```
and how cover both "price" and "quantity", this does not work
```javascript
{{record.column}}
```

**Comment by onechiporenko** [comment]
Does `column` (not `record.column`) is not available in the the partial template?

**Comment by acerov** [comment]
tried `{{column}}` but it outputs something like `<Ember.Object:ember2571>`

**Comment by onechiporenko** [comment]
This one may be used in the `custom/mynumerictemplate` to avoid directly accessing `record.price` or `record.quantity`:
```handlebars
{{get record column.propertyName}}
```

**Comment by acerov** [comment]
@onechiporenko you nail it :smiley: 
I have now:
`{{format-number (get record column.propertyName) precision=2}}`
and it is working like a charm :+1:
