### ISSUE TITLE
Conditional shading of rows

### ISSUE THREAD

**Issue by scottaric** [onechiporenko/ember-models-table#504]
Apologies if this is the incorrect place for this question...

I've using v3.  Is it possible to conditionally change the background color of a row depending on the state of a record?  Is it only possible through the use of template cells or inline block usage?

Thanks in advance.

**Comment by onechiporenko** [comment]
Hello, @scottaric. I think it's possible with block-usage. Some examples are at https://github.com/onechiporenko/ember-models-table/blob/v3.4.0/tests/dummy/app/templates/examples/block-usage.hbs

**Comment by scottaric** [comment]
Wow, thanks for the quick reply!  

Wasn't sure if there was a more direct way that I was missing.  I'll give Block Usage a shot. Thanks again.
