### ISSUE TITLE
summary footer

### ISSUE THREAD

**Issue by acerov** [onechiporenko/ember-models-table#51]
Hi,
how to sum column values in footer?
Thnx

**Comment by onechiporenko** [comment]
You may create your own table footer and display there any information. Just set property `tableFooterTemplate` as path to it.

**Comment by gep13** [comment]
@onechiporenko @acerov would either of you happen to have an example of how this can be achieved?  Thanks in advance.

**Comment by onechiporenko** [comment]
[Inline edit and columns summary](https://ember-twiddle.com/99e1630b806bd4bd6edb5682429079a8?fileTreeShown=false&numColumns=0)

**Comment by gep13** [comment]
@onechiporenko thank you for doing this!  I will take a look.
