### ISSUE TITLE
Problem when selecting the currentPageNumber

### ISSUE THREAD

**Issue by armin11** [onechiporenko/ember-models-table#510]
* **I'm submitting a ...**

  - [ x] bug report
  - [ ] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**
After selecting an arbitrary pagenumber the selected pagenumber is 1 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
http://onechiporenko.github.io/ember-models-table/v.4/bs5/#/examples/query-params?page=4
First select page 1 - after that select page 5 - the selection will show 1 - not 5

* **[Bug] What is the expected behavior?**
It should show the selected pagenumber

* **[Feature] What is the motivation / use case for changing the behavior?**

* **[Support] What exactly you try to do?**
Use ember with an existing json:api interface 

* **Please tell us about your environment:**

- `ember-models-table` version: 
"ember-models-table": "^4.5.0",
- `ember` version: 
Ember      : 4.6.0
- `ember-data` version: 
Ember Data : 4.4.1
- `ember-cli` version:  
"ember-cli": "~4.6.0",
- `node` version:
"node": "14.* || >= 16"
- `npm` or `yarn` version:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by armin11** [comment]
https://user-images.githubusercontent.com/1188234/193861214-2c31259c-2507-4530-8ec2-e115adfc7090.mp4

**Comment by onechiporenko** [comment]
Hello, @armin11. Thanks for demo!
What OS/browser are you using?
I'm using Win10/Chrome 106.0.5249.91 and issue does not appear :/

**Comment by armin11** [comment]
hi @onechiporenko - i used firefox 102.3.0esr (64-Bit) under debian 11 - the problem also occured in ff under windows 10 but i don't know the used version. so it seems to be a firefox problem. i tested it under chrome 106.0.5249.61 and there everything works as expected ;-)

**Comment by onechiporenko** [comment]
Thanks. Going to test with FF

**Comment by onechiporenko** [comment]
Manually updating `this.model` in the Controller was a not good idea.

**Comment by armin11** [comment]
thanx a lot ;-)
