### ISSUE TITLE
demo and documentation app for v4 is broken

### ISSUE THREAD

**Issue by jelhan** [onechiporenko/ember-models-table#527]
The demo and documentation app for v4 seems to be broken. This link is not working: http://onechiporenko.github.io/ember-models-table/v.4/plain-html/ I see many 404 errors in the developer tools.

The landing page and other versions seem to not be affected. This links all work fine:

- https://onechiporenko.github.io/ember-models-table/
- http://onechiporenko.github.io/ember-models-table/v.1/
- http://onechiporenko.github.io/ember-models-table/v.2/#/examples
- http://onechiporenko.github.io/ember-models-table/v.3/plain-html/#/examples

**Comment by elwayman02** [comment]
Can confirm I'm seeing this as well

**Comment by onechiporenko** [comment]
Hi. Thanks for reporting!
Going to fix.

**Comment by onechiporenko** [comment]
Fixed.
