### ISSUE TITLE
tfooterWrapper appears unused

### ISSUE THREAD

**Issue by elwayman02** [onechiporenko/ember-models-table#531]
* **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - ~[ ] support request~ Ask in the [official Ember Discord server](https://discord.gg/zT3asNS).

* **What is the current behavior?**

The `tfooterWrapper` class does not get applied anywhere, despite being defined in the default and bootstrap3 themes:

https://github.com/onechiporenko/ember-models-table/blob/master/addon/services/emt-themes/default.ts#L461-L464
https://github.com/onechiporenko/ember-models-table/blob/master/addon/services/emt-themes/bootstrap3.ts#L61

These are the only two references to that variable anywhere in the project. Was this deprecated and never removed? If so, is `tfooterInternalWrapper` the intended replacement for it?

* **[Bug] What is the expected behavior?**

The class should either be applied somewhere in a template or removed with a documented replacement.

**Comment by onechiporenko** [comment]
Hi, thanks for reporting!
