### ISSUE TITLE
Crash with ember 5

### ISSUE THREAD

**Issue by pulien** [onechiporenko/ember-models-table#548]
* **I'm submitting a ...**

  - [ ] bug report

* **What is the current behavior?**
Crash at start :
```sh
Cannot read properties of undefined (reading 'ember-cli-sass')


Stack Trace and Error Report: /tmp/error.dump.57758056bc34d055bf6b25cbd73800a5.log
```

The issue is due to ember-basic-dropdown coming from ember-power-select : https://github.com/cibernox/ember-basic-dropdown/issues/706
To fix it, you'd need to update ember-power-select in depencencies

* **Please tell us about your environment:**

- `ember-models-table` version: 
- `ember` version: 5.1.1
- `ember-data` version: 5.1.0
- `ember-cli` version:  5.1.0
- `node` version: 16.18
- `pnpm` version: 8.6.7

**Comment by onechiporenko** [comment]
@pulien. Please try with latest `5.0.0-beta.1`

**Comment by pulien** [comment]
It works with this version, thanks
