### ISSUE TITLE
Ember Font Awesome support??

### ISSUE THREAD

**Issue by LumenMicho** [onechiporenko/ember-models-table#556]
Does ember models table support the SVG version of font awesome? or is it only the outdated image class="" version?

**Comment by onechiporenko** [comment]
I think for now, there is only `class=""`-support. It's a good idea to have `svg` support.

**Comment by LumenMicho** [comment]
> I think for now, there is only `class=""`-support. It's a good idea to have `svg` support.

What is the recommended way to import it? Looks like it doesn't work with https://github.com/FortAwesome/ember-fontawesome. Which is font awesome's recommended import.

**Comment by onechiporenko** [comment]
@LumenMicho with `ember-models-table@5.1.0` (latest for now) you can override components with icons and use them in the custom theme (please, check [custom theme service](https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/services/custom-themes/plain-html-with-custom-fa.js)). Demo in the GH pages doesn't work now.
For `ember-models-table@5.0.0` or below you should import font and css-file to your app.

**Comment by LumenMicho** [comment]
Awesome thank you. Looks like we will just import the CSS file for now and use ember-fontawesome when/if it gets added. Appreciate your help
