### ISSUE TITLE
Add actions when displayed data changes

### ISSUE THREAD

**Issue by mydea** [onechiporenko/ember-models-table#57]
It would be very useful to have an action which is called whenever the displayed data changes with the new filtered & sorted data.

eg:

```hbs
{{ember-models-table data=model update=(action 'dataUpdated')}}
```

```js
dataUpdated: function(filteredData) {
  // do something
}
```

So basically whenever I filter something or change the sorting, this action would be called. 
My use case for this is the following: I have a table, and below the table I have a chart which displays the data visually. I would like the chart to only show the data which is currently displayed in the table, so if I filter a column and only 2 records remain, only these two records would be displayed in the chart. Right now, I would have to do the filtering and sorting outside of ember-models-table and actually lose most of the things that make it so useful.

**Comment by mydea** [comment]
Awesome!

**Comment by Datamance** [comment]
@mydea @onechiporenko just saw this. It looks like the new feature only passes the table settings to the action callback. Where can I access the sorted data?
