### ISSUE TITLE
Global search didn't work properly

### ISSUE THREAD

**Issue by YuliaZaiats** [onechiporenko/ember-models-table#6]
When you try to search something through Global search and yours table with custom template in the cell. Column search works fine :smirk:

![screen shot 2015-07-17 at 10 43 32](https://cloud.githubusercontent.com/assets/4838046/8742722/f2b2d984-2c70-11e5-86bd-0abac805a0c9.jpg)

**Comment by artsyca** [comment]
I'm still not seeing all the expected results when global searching with a custom template..

**Comment by onechiporenko** [comment]
Search is done only if column has `propertyName` or `sortedBy` field.

**Comment by artsyca** [comment]
I understood a bit about the global search feature. It seems it will search `propertyName` as a string, but it might fail if you have certain content in a cell template.

My workaround is to create a searchable string property on the record that I can then feed into the table only for global search purposes.
