### ISSUE TITLE
Seems to break with Ember 2.4.x (LTS release)

### ISSUE THREAD

**Issue by stonetwig** [onechiporenko/ember-models-table#64]
Hey,

awesome plugin and we have tremendous use of it.
We have noticed that the data for the table doesn't auto-update with the ember model.

When the promise resolves, no data is ever shown in the table. Unsure on why this happens. But it works with Ember 2.3 and as soon as you make the jump to 2.4 it breaks.

Best wishes,
Markus

**Comment by onechiporenko** [comment]
Hi, Markus. 
Thanks for response. Yes, such problem exists (I see it on the Travis CI).
Currently working on it, but can't give any estimates.

**Comment by stonetwig** [comment]
No worries and you shouldn't have to give any estimates, it's open source and I would gladly help if I knew how. Unfortunately at this time I cannot dig into a new project.

**Comment by onechiporenko** [comment]
@stonetwig, @nicozimmermann94, @rkuzsma, could you test latest code from repo please? I've added fix to correctly init table data. As @rkuzsma mentioned in the https://github.com/onechiporenko/ember-models-table/issues/70#issuecomment-198998019 - content is correctly updated when some sorting is done (table-header cell is clicked). I can't understand why exactly it happens. I tried to investigate `computed.sort`, but I've found only one thing (described in the  https://github.com/emberjs/ember.js/issues/13037).
So, what I've done. Until now table should always be sorted initially. If user didn't provide column to sort, table'll be sorted by the first column. It's kind of restriction, but I can't find another way.
If you find any other related bugs fill free to ask here or open another issues. Thanks

**Comment by rkuzsma** [comment]
I confirmed the table is loading properly with Ember 2.4.1 in the latest code from the repo today. Thanks @onechiporenko !

**Comment by stonetwig** [comment]
Hello,

I just also want to confirm that this works with the latest version of Ember!
