### ISSUE TITLE
Custom columns fields 

### ISSUE THREAD

**Issue by Micke5** [onechiporenko/ember-models-table#65]
Hi!

Thanks for an awesome addon!

I was wondering if adding custom columns fields would break anything?

```javascript
columns: [
  {
    propertyName: 'name',
    title: 'Name',
    type: 'foo'
  },
 ]
```

If it breaks something it would be a very useful feature :)

**Comment by onechiporenko** [comment]
Hi, @Micke5. I don't think that some extra-fields may break something.
Column are "re-mapped" in https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L709 on component init.

**Comment by Micke5** [comment]
@onechiporenko, Alright thats sweet! 
The added attribute makes it easy to create a general template with link-to different models :)
