### ISSUE TITLE
Cannot add link-to to cell data

### ISSUE THREAD

**Issue by talhaobject90** [onechiporenko/ember-models-table#67]
I wonder , if we could have links connected to the data of tables to another page with parameters. 
This seems to be a basic requirement , but as the columns are configured in another way , i cannot append the links ,

Any idea.?

**Comment by onechiporenko** [comment]
Hi, @talhaobject90. You may create custom template for cells with link and use it. See, `column.template` in the http://onechiporenko.github.io/ember-models-table/

**Comment by talhaobject90** [comment]
Thanks, i that was helpful.
Sorry , I have one more doubt,
 
how to remove the search boxes at each columns? for me the search box at top is enought. i need to remove the remaining search boxes at each columns.

Thanks in advance!!

**Comment by onechiporenko** [comment]
set `useFilteringByColumns` to `false` for your component.

**Comment by talhaobject90** [comment]
Thanks , that worked for me , i forgot to reply.
