### ISSUE TITLE
Update values when hiding columns?

### ISSUE THREAD

**Issue by stonetwig** [onechiporenko/ember-models-table#68]
Hello,

I am controlling which columns are to be hidden via a query param that gets sent into a component like this:
  `{{search-result model=model hiddenColumns=hiddenColumns}}`

In the component I make use of the `didRecieveAttrs()` method that Ember provides in order to update the columnsArray:
```
didReceiveAttrs() {
    this._super(...arguments);
    let cols = this.get('hiddenColumns');
    let hiddenColumns = typeof cols === 'string' ? cols.split(',') : [];
    hiddenColumns.forEach(col => {
      this.get('columsArray').forEach(v=> {
        if (v.id === col) {
          v.isHidden = true;
        } else {
          v.isHidden = false;
        }
      });
    });
  },
```

The issue I have is that I don't know how to make it update this value when having user actions on hiding the different columns. I tried to make use of `didUpdateAttrs()` but it doesn't seem like Ember models table updates the array?

Is it possible today to in some way create an action when the user are deselecting/selecting which columns should be shown?

Thanks!

**Comment by onechiporenko** [comment]
Hi, @stonetwig.
I guess my comment here https://github.com/onechiporenko/ember-models-table/issues/47#issuecomment-176761910 may be useful. You may use `isHidden`-property for columns initializing. Set `columnsAreUpdateable` to `true` and `columnFieldsToCheckUpdate` to `['propertyName', 'template', 'isHidden']`. So, when some column's `isHidden` will be updated "outside", columns will be reinitialized.

**Comment by stonetwig** [comment]
Hello @onechiporenko and thank you so much for the reply,

But when I try setting `columnFieldsToCheckUpdate` to the array you specified, it returns this error:
`"Assertion Failed: `columnFieldsToCheckUpdate` should be an array of strings"` which is very weird since that is exactly what it is set to?

I will try to find what the issue is and update this thread if I find a resolution (for other folks that may have the same issue).

**Comment by onechiporenko** [comment]
Wow... Here is this assertion (https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L683). Actually it checks only for `array`-type (and not even type of the each element).
I have checked locally and didn't get such error. It's strange :)

**Comment by stonetwig** [comment]
Yeah,
I verified that the array should result as an "array" when doing an `Ember.typeOf`, but using the Chromes debugger I found that the value is undefined for some reason..

```
{{my-models-table
        data=model.domains
        columns=columnsDomain
        useFilteringByColumns=false
        filteringIgnoreCase=true
        customClasses=customClasses
        useNumericPagination=true
        columnsDropdownTemplate='partials/my-modals-table-buttons'
        customMessages=messages
        columnsAreUpdateable=true
        columnFieldsToCheckUpdate=['propertyName', 'template', 'isHidden']
      }}
```

That is how I initiate the table. Going to research it further, I don't know if I am the wrongdoer here yet but probably ;)

**Comment by onechiporenko** [comment]
Could you try to do 
````handlebars
{{my-models-table
    columnFieldsToCheckUpdate=somePredefinedArray
}}
````

instead of
````handlebars
{{my-models-table
    columnFieldsToCheckUpdate=['propertyName', 'template', 'isHidden']
}}
````

**Comment by stonetwig** [comment]
That of course solved it, thanks!

**Comment by stonetwig** [comment]
One more question, when updateing the `isHidden` field, you mention that it fires `_setupColumns` but is it possible to override it and hook into the actual process of updating? Because I want side effects to happen when updating that field.

I am thankful for any answer! :)

**Comment by onechiporenko** [comment]
As for me, it's almost impossible to store current sort, filter, pagination and visibility options while columns updating. There are too much possible cases that may not be covered.
