### ISSUE TITLE
Broken filter

### ISSUE THREAD

**Issue by nicozimmermann94** [onechiporenko/ember-models-table#70]
Hello!
As it seems the filter function (global and columns) is somewhat broken. Sometimes it works, sometimes it does not. I cannot even reproduce it. I am using the newest ember 2.4, maybe that is the cause.
It seems some update function does not get triggered. The only hint I can give is when I click on a table header to sort it, then the filter function gets triggered.

Sorry if this is not enough help.

**Comment by onechiporenko** [comment]
Hi, currently this addon is not working with latest 2.4 (I'm working on this).

**Comment by rkuzsma** [comment]
If it helps, my observation in Ember 2.4.1:
After you click a column header at least once, any changes you make to the underlying table data are automatically reflected in the table. Before you've clicked a column header, changes to the underlying table data are not reflected in the table.
