### ISSUE TITLE
Disable per column filtering

### ISSUE THREAD

**Issue by nicozimmermann94** [onechiporenko/ember-models-table#71]
Enhancement:
I want to disable the filter input fields for each column. It seems like there is no option. Can you please add such an option?

**Comment by mydea** [comment]
Actually, I added this in https://github.com/onechiporenko/ember-models-table/pull/69, which has been merged into master :)

**Comment by nicozimmermann94** [comment]
Thank you all!

**Comment by Micke5** [comment]
If this is for the global filter it is not working for me :( 
`  Ember.Object.create({
      propertyName: 'tstamp',
      title: 'Created',
      sortDirection: 'desc',
      sortPrecedence: 1,
      disableFiltering: true,
      template: 'partials/date-cell'
    }),`
And this column still effect the filter...
