### ISSUE TITLE
Columns dropdown and filtering does not work

### ISSUE THREAD

**Issue by josefguenther** [onechiporenko/ember-models-table#72]
The problem: I installed `ember-models-table`, added a table, and it seems like events are not firing for the filtering and the dropdown. I have a very very simple project, so I would be surprised if there is a conflict that is causing this.

```
Ember 2.4.2
Ember Data 2.4.0
Ember Bootstrap 0.6.4
Ember Models Table 1.5.0 (just installed, so I assume it's the latest)
```

I just tried simple vanilla code:
```
{{models-table
    data      = model
    columns   = columns
}}
```

It displays perfectly, but if I type something in the filter fields nothing happens (if I press Return on the `Search` field, it reloads the page); when I click the Columns dropdown it does not display (but if I manually clear the `display:none` on the dropdown, I see it rendered perfectly).

I tried using a custom row template with a `{{link-to}}` helper and that fires correctly, so I assume events are working overall. Sorting columns also works correctly.

I checked all my CSS rules (I only have a few) and could not find a conflict.

Am I missing any dependencies?

**Comment by onechiporenko** [comment]
Hi, @josefguenther. Thanks for opening the issue.
There is an issue (https://github.com/onechiporenko/ember-models-table/issues/64) about this. `computed.sort` behavior was changed in the `Ember`, so I had to do some changes in the code (and do a lot of invastigations).
Currently, I've committed changes to fix plugin (not yet in the npm). Now, I'm waiting for response from guys (in the #64). Could you also check repo-code for your needs (`npm i onechiporenko/ember-models-table`)? If it works and there are no issues, I'll pull new version to the npm in the day or two/
Thanks

**Comment by josefguenther** [comment]
Ok I tested against the latest commit...

The filtering issue is fixed.
**The columns dropdown issue is still not fixed.**

I believe this is a different issue than #64 . That has to do with data not showing up at all (?), for me the data always showed up fine. It could be the same underlying root cause though.

**Comment by onechiporenko** [comment]
@josefguenther, could you disable Ember Bootstrap and test again?

**Comment by josefguenther** [comment]
I disabled bootstrap; the columns dropdown is permanently visible and the button does not collapse it.

**Comment by onechiporenko** [comment]
I mean not disable Bootstrap totally and just don't use Ember Bootstrap. And leave raw-Bootstrap.

**Comment by josefguenther** [comment]
Ok, still not working. I only have it nested inside two container-fluid blocks, that's all. I removed those, didn't help. I also tried removing all my own styles (not that many) and still didn't work...

Do you not experience this issue at all? Can you test using the same version of ember?

**Comment by josefguenther** [comment]
If it helps, here's my package.json:
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-bootstrap": "0.6.4",
    "ember-cli": "2.4.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-load-initializers": "^0.5.0",
    "ember-models-table": "github:onechiporenko/ember-models-table#213f83e2de44cfe6604ad1b99e990c341a1bd27b",
    "ember-moment": "6.1.0",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0-beta.3",
    "loader.js": "^4.0.0"
  }
```

**Comment by josefguenther** [comment]
This might be the issue.

I am using: **kaliber5/ember-bootstrap**.

It specifically says "it provides a set of native Ember components (no use of Bootstrap JavaScript!).".

I think that might be the issue. Has anyone else used that bootstrap plugin and got the columns dropdown to work?

Or should I be using a different plugin for bootstrap?

**Comment by onechiporenko** [comment]
I think, in this case you need to write your own [columns-dropdown.hbs](https://github.com/onechiporenko/ember-models-table/blob/master/app/templates/components/models-table/columns-dropdown.hbs) using ember-bootstrap.

**Comment by manukbenjamin** [comment]
I also have the same issue. Column drop down is not working and I am using ember- bootstrap in my project. As a work around i modified column-dropdow n.hbs and added my own code to toggle display when use select show columns.

**Comment by josefguenther** [comment]
Ok, I created a new columns dropdown template. I am pasting this below... perhaps this will help someone, or perhaps you could make an option for using ember-bootstrap and including this template instead of the original...

```

<div class="{{classes.columnsDropdownWrapper}}">
  <div class="{{classes.columnsDropdownButtonWrapper}}">
    {{#bs-dropdown}}
      {{#bs-dropdown-button}}
        {{messages.columns-title}} <span class="{{icons.caret}}"></span>
      {{/bs-dropdown-button}}
      {{#bs-dropdown-menu}}
        <li><a {{action "showAllColumns" column bubbles=false}} href="#">{{messages.columns-showAll}}</a></li>
        <li><a {{action "hideAllColumns" column bubbles=false}} href="#">{{messages.columns-hideAll}}</a></li>
        <li><a {{action "restoreDefaultVisibility" column bubbles=false}} href="#">{{messages.columns-restoreDefaults}}</a></li>
        <li class="divider"></li>
        {{#each processedColumns as |column|}}
          {{#if column.mayBeHidden}}
            <li>
              <a {{action "toggleHidden" column bubbles=false}} href="#">
                  <span class="{{if column.isVisible icons.column-visible icons.column-hidden}}"></span> {{column.title}}
              </a>
            </li>
          {{/if}}
        {{/each}}
      {{/bs-dropdown-menu}}
    {{/bs-dropdown}}
  </div>
</div>
```

**Comment by harleyjj** [comment]
Hi Folks, I just wanted to post a solution for people using older versions of Ember and ember-bootstrap (my case).  This custom template worked for me:

`<div class="{{classes.columnsDropdownWrapper}}">
  <div class="{{classes.columnsDropdownButtonWrapper}}">
    {{#bs-dropdown as |dd|}}
      {{#dd.button}}
        {{messages.columns-title}}<span class="caret"></span>
      {{/dd.button}}
      {{#dd.menu as |ddm|}}
        {{#ddm.item}}
          <a {{action "showAllColumns" column bubbles=false}} href="#">{{messages.columns-showAll}}</a>
        {{/ddm.item}}
        {{#ddm.item}}
          <a {{action "hideAllColumns" column bubbles=false}} href="#">{{messages.columns-hideAll}}</a>
        {{/ddm.item}}
        {{#ddm.item}}
          <a {{action "restoreDefaultVisibility" column bubbles=false}} href="#">{{messages.columns-restoreDefaults}}</a>
        {{/ddm.item}}
        {{#each processedColumns as |column|}}
          {{#if column.mayBeHidden}}
            {{#ddm.item}}
              <a {{action "toggleHidden" column bubbles=false}} href="#">
                  <span class="{{if column.isVisible icons.column-visible icons.column-hidden}}"></span> {{column.title}}
              </a>
            {{/ddm.item}}
          {{/if}}
        {{/each}}
      {{/dd.menu}}
    {{/bs-dropdown}}
  </div>
</div>`
