### ISSUE TITLE
Filtering by 1 or 0 does not work

### ISSUE THREAD

**Issue by josefguenther** [onechiporenko/ember-models-table#73]
Like title says, entering just `1` or just `0` in the Search box does not filter the results (as in, nothing happens). Entering any other single digit or letter works correctly.

Additionally, entering multiple 0s does not filter either... such as `000`.

I know it is a small issue, but it is an issue nonetheless... :)

**Comment by josefguenther** [comment]
Apologies, it does work correctly. It filters based on hidden columns as well, which had the data in question... is this intended functionality? If so, please close. It would be nice to be able to disable that feature though.

**Comment by onechiporenko** [comment]
I think it's not difficult to add option to enable/disable filtering by hidden columns
