### ISSUE TITLE
Table doesn't refresh if delete row goes first

### ISSUE THREAD

**Issue by bedrosenator** [onechiporenko/ember-models-table#76]
Table doesn't refresh if delete cell goes first(search, delete row, add row). For example 
columns: [
{
    "title": "Delete",
    "template": "custom/delete"
  },
  {
    "propertyName": "id",
    "title": "ID"
  },
  {
    "propertyName": "firstName",
    "title": "First Name"
  },
  {
    "propertyName": "lastName",
    "title": "Last Name"
  },
  {
    "propertyName": "city",
    "title": "City"
  }
]

I've got this trouble when I tried to put delete button in the first cell

**Comment by onechiporenko** [comment]
Fixed
