### ISSUE TITLE
Server paginated error layout

### ISSUE THREAD

**Issue by cmonzon44** [onechiporenko/ember-models-table#77]
Hello, when i try to load models-table-server-paginated component in my template with data, 
it throw an error in console, 

`Error: Could not find module templates/components/models-table imported from ember-models-table/components/models-table-server-paginated`

in my template: 
```
{{models-table-server-paginated
      data=model
      columns=mycolumns
      show='showRecord'
      useNumericPagination=true
      filteringIgnoreCase=true
      customMessages=customMensajes
      customClasses=customClases
    }}
```
these function is complete? or it is in development  now?

[https://github.com/onechiporenko/ember-models-table/tree/master/addon/components]

thanks.

**Comment by onechiporenko** [comment]
@mydea, is it enough to add template
`app/templates/components/models-table/models-table-server-paginated.hbs`:
```hbs
{{yield}}
```
and remove `layout`-field from `addon/components/models-table-server-paginated.js` ?

**Comment by onechiporenko** [comment]
@cmonzon44, this function  is complete, but I guess some changes were done in the Ember 2.5 (or even 2.4) that should be handled in this addon.

**Comment by mydea** [comment]
I'm not sure how inheritance of templates work? Does it use the models-table template by default if the ModelsTable component is extended? If so, then I guess we could just remove the whole `layout: layout` part, as well as the models-table-server-paginated template?

**Comment by onechiporenko** [comment]
@cmonzon44 , could you install this addon from git (`npm i onechiporenko/ember-models-table`) and check if this fix is enough? Thanks

**Comment by cmonzon44** [comment]
hello @onechiporenko, sorry for late answer. Yes, I update addon and error has disappear but my table don't show. 
I need to do a template? similar for models-table or what information i need to agree in my json to server-paginated works fine?
Thanks

**Comment by saygun** [comment]
Having same issue here. Any update on this? 
Thanks

**Comment by stonetwig** [comment]
Just updated to 1.7.0 and can confirm this is no longer an issue @saygun

**Comment by albertonavarro087** [comment]
I'm having the same issue as cmonzon44, table don't show, do I need to add something into my project?
