### ISSUE TITLE
I think the main contributor has a bad git setup

### ISSUE THREAD

**Issue by lcpriest** [onechiporenko/ember-models-table#78]
I think your local github email is different to your account, your commits have not been assigned to you.
https://github.com/onechiporenko/ember-models-table/graphs/contributors

You can just add your local email to your github emails and it will pick it up https://github.com/settings/emails

**Comment by lcpriest** [comment]
@onechiporenko

**Comment by onechiporenko** [comment]
Hi, @lcpriest . Sometimes I need to do commits as "I am not I" :)
