### ISSUE TITLE
Checkbox for each table row

### ISSUE THREAD

**Issue by onmondo** [onechiporenko/ember-models-table#82]
Hi,

How can I include checkboxes per row?
Aside from using a template.

Thanks,
John

**Comment by onechiporenko** [comment]
Hi, @onmondo. I think there is only one way to do this - add template to the cell.

**Comment by onmondo** [comment]
Hi, thanks for the reply. 

Yep, already tried that one and it works perfectly. How about putting a checkbox in the header. I have an application that requires multi select checkbox that enable users to select or deselect all records from the table.

**Comment by onechiporenko** [comment]
Currently it's possible only with your own table template.

**Comment by onmondo** [comment]
Hi @onechiporenko, Is there a possible enhancement to support this feature in the near future?

**Comment by onechiporenko** [comment]
Add possibility to have custom templates for column headers (cells with titles and not with filters). Am I right?

**Comment by onmondo** [comment]
Yep. That will do :)

**Comment by nag9329** [comment]
This is not working with ember-models-table 1.10.1. When I add action to the checkbox, Im able to see the record being passed to the action method but the UI is not updating as checked. Reopening the issue and also can I see any sample code how to include the checkbox in the header to select all or deselect all.
