### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by mydea** [onechiporenko/ember-models-table#83]
I just saw that the behavior for default sorting has changed (https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table.js#L812).

Is there no way to return to the previous behavior, where default sorting was basically just the order of the data? I think this new behavior is kind of confusing and often not what I would want/expect.

**Comment by onechiporenko** [comment]
Hi, @mydea. It's not possible because `computed.sort` with calc `arrangedContent` only after first sorting. 
If sorting is not done, filtering results won't be "visible" on the page

**Comment by mydea** [comment]
Ok, then I'll need to work around it.

If anyone else has this problem, I ended up doing this:

```js
{
  propertyName: '',
  sortedBy: 'defaultSortPosition',
  title: '',
  sortPrecedence: 0,
  sortDirection: 'asc'
}
```

And then added a field `defaultSortPosition` to each array element which is the array index.

I also changed the template for the header cells a bit:

```hbs
{{#if column.title}}
  <th class="{{classes.theadCell}}" {{action "sort" column}}>
    {{column.title}}
    <span class="{{if column.sortAsc icons.sort-asc}} {{if column.sortDesc icons.sort-desc}}"></span>
  </th>
{{else}}
  <th class="{{classes.theadCell}} no-padding"></th>
{{/if}}
```

Because otherwise the sort icon would appear over the empty column.
