### ISSUE TITLE
External filters for model breaks sorting and resets per page value

### ISSUE THREAD

**Issue by bedrosenator** [onechiporenko/ember-models-table#84]
I'm using external filters (filter method) in my code. Before model was changed - it was ok, sorting works well, per page value saves well http://joxi.ru/vn2YYdZInDQ526
But if I start to filter model, per page value resets to default value and sorting arrows dissapears. Sorting works only for id.
http://joxi.ru/K823gLzT5pbY2O

**Comment by onechiporenko** [comment]
Hi, @bedrosenator. Could you please provide `columns` that use used, data source and component declaration (like `{{models-table .... }}`). Thanks

**Comment by bedrosenator** [comment]
{{models-table
          data=filteredPaymentData
          columns=paymentTable.columns
          pageSizeValues=perPage
          pageSizeTemplate='components/models-table/page-size'
          useFilteringByColumns=false
          columnsAreUpdateable=true
          showColumnsDropdown=false
          expandTableRowAction='expandTableRow'
          collapseTableRowAction='collapseTableRow'
          delete='deleteTableRecord'
          sendReplyAction='sendReply'
          useNumericPagination=true
          rowTemplate='components/models-table/paymentRow'
          rowTemplateExpanded='components/models-table/paymentRowExpanded'
          selectedRows=selectedRows
          isRowsExpandable=true
          numericPaginationTemplate='components/models-table/numeric-pagination'
          tableFooterTemplate='components/models-table/table-footer'
          pageSize=5
          icons=tableIcons
          globalFilterTemplate='components/models-table/global-filter'
          customClasses=customTableClasses
        }}


filtersChanged: Ember.observer('filterBy.requestAmount', 'filterBy.id', 'filterBy.paidAmount', 'filterBy.status', 'filterBy.paymentType', 'filterBy.requestDate', 'filterBy.lastUpdate', function() {
    var model = this.get('model');
    var id = this.get('filterBy.id');
    var requestAmount = this.get('filterBy.requestAmount');
    var paidAmount = this.get('filterBy.paidAmount');
    var status = this.get('filterBy.status');
    var paymentType = this.get('filterBy.paymentType');
    var requestDate = this.get('filterBy.requestDate');
    var lastUpdate = this.get('filterBy.lastUpdate');

    if (id) {
      model = this.filterRecords(model, 'id', id);
    }

    if (requestAmount) {
      model = this.filterRecords(model, 'requestAmount', requestAmount);
    }

    if (paidAmount) {
      model = this.filterRecords(model, 'paidAmount', paidAmount);
    }

    if (status) {
      model = this.filterRecords(model, 'status', status);
    }

    if (paymentType) {
      model = this.filterRecords(model, 'paymentType', paymentType);
    }

    if (requestDate) {
      model = this.filterRecords(model, 'requestDate', requestDate);
    }

    if (lastUpdate) {
      model = this.filterRecords(model, 'lastUpdate', lastUpdate);
    }

    this.set('filteredPaymentData', model);
  }),

paymentTable: {
    columns: [
      {
        "propertyName": "id",
        "title": "id"
      },
      {
        "propertyName": "userId",
        "title": "userId"
      }, {
        "propertyName": "labelId",
        "title": "labelId"
      }, {
        "propertyName": "label",
        "title": "label"
      }, {
        "propertyName": "requestAmount",
        "title": "requestAmount"
      }, {
        "propertyName": "paidAmount",
        "title": "paidAmount"
      }, {
        "propertyName": "status",
        "title": "status",
        "template": 'components/models-table/payments/status'
      }, {
        "propertyName": "paymentType",
        "title": "paymentType"
      }, {
        "propertyName": "requestDate",
        "title": "requestDate"
      }, {
        "propertyName": "lastUpdate",
        "title": "lastUpdate"
      }, {
        "propertyName": "comment",
        "title": "comment"
      }, {
        "propertyName": "commentReply",
        "title": "commentReply"
      }
    ]
  }

var filteredPaymentData = [
  {
  comment: null,
  commentReply: null,
  firstName: "EugAndMax",
  id: "1",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00"
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},

{
  comment: null,
  commentReply: null,
  firstName: "EugAndMax",
  id: "2",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},

{
  comment: null,
  commentReply: null,
  firstName: "EugAndMax 2",
  id: "3",
  label: "WL 12",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},
{
  comment: null,
  commentReply: null,
  firstName: "Euczczx gAndMax",
  id: "3",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKi dsa dsa dsa ",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "300.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},
{
  comment: null,
  commentReply: null,
  firstName: "xcvb",
  id: "4",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00"
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},

{
  comment: null,
  commentReply: null,
  firstName: "jhgfhg ",
  id: "5",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},

{
  comment: null,
  commentReply: null,
  firstName: "gfd 2",
  id: "6",
  label: "WL 12",
  labelId: "1",
  lastName: "GelfKir",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "200.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
},
{
  comment: null,
  commentReply: null,
  firstName: "asd",
  id: "7",
  label: "WL 1",
  labelId: "1",
  lastName: "GelfKi dsa dsa dsa ",
  lastUpdate: null,
  level: "1",
  network: "IB",
  paidAmount: "300.00",
  paymentType: "PayPal",
  requestAmount: "500.00",
  requestDate: "2016-05-05 12:34:59",
  status: "pending",
  userId: "1",
}
]

**Comment by onechiporenko** [comment]
Thanks. I' going to check and try to find out what is wrong.

**Comment by bedrosenator** [comment]
Thanks, it would be nice

**Comment by onechiporenko** [comment]
@bedrosenator, currently I can't understand what is going wrong.

**Comment by bedrosenator** [comment]
Can you reproduce this bug?

**Comment by Ramblurr** [comment]
@bedrosenator did you ever find a work around for this bug? I too am trying to implement a global filter over models-table

**Comment by bedrosenator** [comment]
@Ramblurr I found it a year ago and I don't have access to that source code. And don't remember exactly what was that. But if I remember correctly I've set some parameter in {{models-table}} and it started work well

**Comment by Ramblurr** [comment]
Thanks @bedrosenator, @onechiporenko any suggestion on what that property might be?
