### ISSUE TITLE
Select Column Filter breaks when propertyName contains a period

### ISSUE THREAD

**Issue by jakemoves** [onechiporenko/ember-models-table#86]
(loving this component, it's fantastic!)

If the propertyName for a column contains a period (i.e. if you're using any nesting in the data structure), using a select filter throws an error, because the dot breaks the CSS selector on line 1123 of models-table.js.

I fixed it by adding `.replace('.', '-')` to that line, and by making a tiny helper to do the same on line 37 of models-table.hbs.

Can't submit a PR right now because of too many other changes, sorry.

**Comment by onechiporenko** [comment]
Is it similar to https://github.com/onechiporenko/ember-models-table/pull/85 or it's the same?

**Comment by jakemoves** [comment]
Similar but not the same. It's the jQuery selector on line 1123 that fails, because if a property name is something like 'tableData.field', it resolves `$('.changeFilterForColumn.tableData.field')` as a search for a DOM element like

`<select class="changeFilterForColumn tableData field">`

So I solved it by changing tableData.field to tableData-field in both models-table.js (using .replace) and in the template (using a simple helper).
