### ISSUE TITLE
Issue extending the component

### ISSUE THREAD

**Issue by rhyek** [onechiporenko/ember-models-table#88]
I'm trying to setup some defaults for the component by extending it, but when using my component nothing is rendered and I get no errors:

```
// app/pods/components/my-models-table/component.js
import modelsTableComponent from 'ember-models-table/components/models-table';

export default modelsTableComponent.extend({
    useFilteringByColumns: false,
    showGlobalFilter: false,
    showTableFooter: false,
    multipleColumnsSorting: false,
    pageSize: 1000000
});

//app/pods/administration/users/template.hbs
{{my-models-table
    data=model.users
    columns=columns
    }}
```

**Comment by onechiporenko** [comment]
@rhyek, I'm not familiar with Ember pods. 
Maybe it should be `{{my-models-table/component` and not `{{my-models-table`?

**Comment by andrei-sheina** [comment]
@rhyek Extending works fine. I'm using it in my project. Try 
{{#my-models-table
   data=model.users
   columns=columns}}
content goes here
{{/my-models-table}}
Also check out it you are actually passing something as data and columns. Maybe you have no data loaded before passing to the component

**Comment by rhyek** [comment]
Hi. Sorry for not answering earlier as I've been on vacation and didn't get a chance to run some tests. This isn't an issue with your addon. Sadly, when extending a component you also have to set its layout as the parent's explicitly with the `layout` property.

I'm closing this issue.
