### ISSUE TITLE
Filter is broken if there are no columns sorted

### ISSUE THREAD

**Issue by andrei-sheina** [onechiporenko/ember-models-table#89]
Can reproduce in examples from website. http://onechiporenko.github.io/ember-models-table/ For example Filtering ignore case. Turn of sorting by ID column and try to enter any value to the filter. It's broken.

**Comment by onechiporenko** [comment]
HI, @andrei-sheina. Thanks for report.

**Comment by andrei-sheina** [comment]
@onechiporenko Can you please also update npm package, so we can use it with this bug fix right away?

**Comment by onechiporenko** [comment]
Currently I'm working on few other issues  before releasing new version.
You can install code from git using `npm i onechiporenko/ember-models-table`
