### ISSUE TITLE
Pagination and Loading of data

### ISSUE THREAD

**Issue by mtangoo** [onechiporenko/ember-models-table#90]
Does the addon support loading data cummulatively. Let say I have 1million rows and I want to load 100 per page. Does addon support that? Any example or docs to that if any?

**Comment by onechiporenko** [comment]
Hi, @mtangoo. 
https://github.com/onechiporenko/ember-models-table/blob/master/addon/components/models-table-server-paginated.js
I guess this component may help you.
Short description available here - https://github.com/onechiporenko/ember-models-table/pull/62

**Comment by mtangoo** [comment]
thanks
