### ISSUE TITLE
disable sorting while model has dirty attrs

### ISSUE THREAD

**Issue by andrei-sheina** [onechiporenko/ember-models-table#91]
I have multiple rows with inputs. This rows are always sorted (max at the top by default). And when i change value in one of the input, it gets automatically resorted and cause rows to "jump". Can we add some kind of option to disable sorting until model will be saved?

**Comment by KirillSuhodolov** [comment]
@onechiporenko @andrei-sheina I have some issue. My tables have around 50 rows and they blinking at edit.

**Comment by andrei-sheina** [comment]
@onechiporenko to visualize the problem:
![11](https://cloud.githubusercontent.com/assets/11193254/15456212/18852ac2-2072-11e6-882c-a0ea7acc8a02.jpg)
![22](https://cloud.githubusercontent.com/assets/11193254/15456213/1b05e958-2072-11e6-9ed8-006893ef979e.jpg)

**Comment by andrei-sheina** [comment]
@onechiporenko to visualize the problem:
![11](https://cloud.githubusercontent.com/assets/11193254/15456228/8d848584-2072-11e6-9d8b-1039666f8e58.jpg)
![22](https://cloud.githubusercontent.com/assets/11193254/15456229/91dee1ba-2072-11e6-8db9-f3ae3dfb502a.jpg)
So it would be great to have an opportunity to freeze sorting until model, represented by a row is saved.

**Comment by onechiporenko** [comment]
I understand a problem and see possible solution - using `_internalModel` for sorting `DS.Model`-instances. I need to do some tests to check if it's a good way.

**Comment by onechiporenko** [comment]
@andrei-sheina, @KirillSuhodolov could you pls add initializer to your project and check it on your apps:
```javascript
// app/initializers/ds-model.js

import Model from 'ember-data/model';
import Ember from 'ember';

const {get} = Ember;

export function initialize(/* application */) {
  // application.inject('route', 'foo', 'service:foo');
  Model.reopen({

    get() {
      const key = arguments[0];
      const type = get(this, '_internalModel.type');
      const attrs = get(type, 'attributes')._keys.list;
      if (attrs.indexOf(key) !== -1) {
        const changedAttributes = this.changedAttributes();
        if (changedAttributes[key]) {
          return changedAttributes[key][0]; // old value
        }
      }
      return this._super(...arguments);
    }

  });
}

export default {
  name: 'ds-model',
  initialize
};
```

**Comment by andrei-sheina** [comment]
@onechiporenko this solution cause problems with relations between models. Btw, is it right solution to change ember instead of fixing the library itself?

**Comment by andrei-sheina** [comment]
@onechiporenko Solution that i implemented in my project:
I've created model mixin that fires when on model didLoad and didUpdate events. I iterate through model's attributes, duplicate their values and save in the model under solidAttributes namespace. And then i am sorting columns using solidAttributes.attributeName, and not just attributName. Don't know if it's the best solution, but it works fine.

**Comment by andrei-sheina** [comment]
Mixin code itself:
`import Ember from 'ember';

export default Ember.Mixin.create({
  setSolidAttributes: Ember.on('didLoad', 'didUpdate', function() {
    this.set('solidAttributes', {});
    this.eachAttribute((attr) => {
      this.set(`solidAttributes.${attr}`, this.get(attr));
    });
  })
});`

**Comment by bgantzler** [comment]
After they are done editing and hit save, I am assuming you also would not want the sort, or the record would still jump. Seems sorting should be be done when a column header is clicked and only then, All other sorting should not be happening.
