### ISSUE TITLE
Add support for multi-row header?

### ISSUE THREAD

**Issue by DavidVotrubec** [onechiporenko/ember-models-table#92]
I have a table with 2 rows header, like in the attached picture. 
Is it possible to achieve something like that with ember-models-table? 

![image](https://cloud.githubusercontent.com/assets/454429/15454166/7db189dc-2030-11e6-85bb-23c50ff351ce.png)

**Comment by onechiporenko** [comment]
Hi, @DavidVotrubec. Currently it's possible only with defining your own template for component. I think I'll separate it to some parts like `table-header`, `table-body` etc.

**Comment by onechiporenko** [comment]
Option `groupedHeaders` is added. Usage:
```javascript
groupedHeaders: [
  [{title: 'Row1 Group1', colspan: 5}], // first row
  [{title: 'Row2 Group1', colspan: 2}, {title: 'Row2 Group2', colspan: 3}], // second row
] 
```
`groupedHeaders` doesn't affects 'default' column headers.
Also when you are using `groupedHeaders`-options, it's a good idea to set `showColumnsDropdown` to `false` (to avoid markup breaking).

**Comment by DavidVotrubec** [comment]
Thanks,

I have used another approach in the meantime -
https://github.com/DavidVotrubec/ember-models-table/commit/2c6015fd265a27a514f179a1d46bc4d825869b88
(fork of your component)

It uses "columnGroups" property, which when provided by user will be used
instead of the "columns"
The good think is that you do not need to provide colspan property, it is
computed automatically.
The down side is that it does not work yet with the hideable columns
(simply because I do not use the "hide column feature")


<https://htmlsig.com/signatures/001BSZWH2>

David Votrubec / Freelance Web Developer
https://davidjs.com

[image: Twitter]  <https://twitter.com/DavidVotrubec> [image: Stack
Overflow]
<http://stackoverflow.com/users/552194/david-votrubec?tab=profile> [image:
My Blog]  <http://blog.davidjs.com>[image: Github]
<https://github.com/DavidVotrubec>
