### ISSUE TITLE
extending the component

### ISSUE THREAD

**Issue by skaterdav85** [onechiporenko/ember-models-table#95]
Hi! I noticed that when I extend the component in my application, the template won't extend along with it. I'm doing something like this:

```js
// app/components/my-table.js
import TableComponent from './models-table';

export default TableComponent.extend({
  useFilteringByColumns: false,
  showTableFooter: false,
  showGlobalFilter: false,
  showColumnsDropdown: false
});
```

I want the template to just be the addon's template, but nothing shows up on the screen when I try and render `{{my-table ...}}`.

Looking at other component addons, I noticed that the templates folder lived inside of `addons/templates/components` instead of `app/templates/components`.

**Comment by onechiporenko** [comment]
Hi, @skaterdav85! Thanks for the report. I'm going to check it.

**Comment by onechiporenko** [comment]
@skaterdav85, you should add `layout` to your code:
```javascript
// app/components/my-table.js
import TableComponent from './models-table';
import layout from '../templates/components/models-table';

export default TableComponent.extend({
  layout,
  useFilteringByColumns: false,
  showTableFooter: false,
  showGlobalFilter: false,
  showColumnsDropdown: false
});
```
