### ISSUE TITLE
Is it possible to show a one to many relationship with this module? 

### ISSUE THREAD

**Issue by portugaleren** [onechiporenko/ember-models-table#98]
I have not seen this kind of table shown in any of the examples, is it possible and how will it be done?

Author | Books
-------- | -------
Caden Leuschke | - Fantastic Soft Salad Cookbook
Johnathan Murazik | - Handmade Concrete Bike Cookbook
 | - Small Cotton Bike Cookbook
 | - Gorgeous Plastic Chicken Cookbook
 | - Tasty Granite Towels Cookbook
 | - Rustic Frozen Mouse Cookbook
 | - Refined Granite Sausages Cookbook
 | - Incredible Soft Soap Cookbook
 | - Gorgeous Cotton Chicken Cookbook
 | - Rustic Fresh Chair Cookbook

**Comment by onechiporenko** [comment]
Hi, @portugaleren. Currently it's not possible "by default". To show it in this way you should remap your data.

**Comment by portugaleren** [comment]
Ok, thank you.
