### ISSUE TITLE
How to put Slno. in loop

### ISSUE THREAD

**Issue by talhaobject90** [onechiporenko/ember-models-table#99]
This is more a question ,  I would like to know how to put slno. in the first column as auto-increment.

Say if an array of objects has 5 objects. i would like to list them down with first column as 1, 2, 3, 4, 5

I tried the custom template option  , but no luck

**Comment by onechiporenko** [comment]
Hi, @talhaobject90. Sorry for long delay.
Currently it is possible only if data shown in the table has some field that is AI on it.

Do you need static AI on the table? Should it be changed on sorting/filtering?
